Repository mempool/mempool, pull requests merged in 2021-11, with the labels that each got.

#890 UI/UX: Fix buttons positions at graphs page.
  frontend/cypress/integration/mainnet/mainnet.spec.ts
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.scss
Labels: bug

#905 UI/UX: Add 2y and 3y statistics time span.
  backend/src/api/statistics.ts
  backend/src/index.ts
  backend/src/routes.ts
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.ts
  frontend/src/app/services/api.service.ts
Labels: enhancement

#897 UI/UX: Fix rtl mobile header menu.
  frontend/src/app/components/master-page/master-page.component.scss
  frontend/src/app/components/search-form/search-form.component.scss
  frontend/src/styles.scss
Labels: bug

#902 Doc: Fix nginx package name.
  README.md
Labels: documentation

#921 Fix menu button styles.
  frontend/src/app/components/master-page/master-page.component.scss
Labels: bug

#898 Localization: Add localize strings at echarts tooltip.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: i18n

#932 Fix: mempool empty block.
  frontend/cypress/integration/liquid/liquid.spec.ts
  frontend/cypress/integration/mainnet/mainnet.spec.ts
  frontend/cypress/integration/signet/signet.spec.ts
  frontend/cypress/integration/testnet/testnet.spec.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
Labels: bug

#935 Fix: op_return tooltip position.
  frontend/cypress/integration/mainnet/mainnet.spec.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
Labels: UI/UX

#942 Enable i18n locale Thai (th)
  frontend/README.md
  frontend/angular.json
  frontend/src/app/app.constants.ts
  frontend/src/locale/messages.th.xlf
  nginx.conf
  production/nginx.conf
Labels: enhancement, i18n

#943 Delete nginx logs after 10 days and explain this in our Privacy Policy
  frontend/src/app/components/privacy-policy/privacy-policy.component.html
  production/newsyslog-mempool-nginx.conf
Labels: legal, ops

#950 Fix time span menu styles.
  frontend/src/app/components/statistics/statistics.component.scss
Labels: bug
