Repository mempool/mempool, pull requests merged in 2021-09, with the labels that each got.

#716 Improvements to API documentation and examples
  frontend/src/app/components/api-docs/api-docs.component.html
  frontend/src/app/components/api-docs/api-docs.component.ts
  frontend/src/app/components/api-docs/code-template.component.html
  frontend/src/app/components/api-docs/code-template.component.ts
Labels: documentation

#769 Fix api-docs incorrect API path for fees related methods
  frontend/src/app/components/api-docs/api-docs.component.ts
Labels: bug, documentation

#772 Fix API docs examples for Raspberry Pi users using romanz/electrs
  frontend/src/app/components/api-docs/api-docs.component.ts
Labels: bug

#776 Add newsyslog.conf for nginx log rotation - delete logs after 90 days
  production/newsyslog-mempool-backend.conf
  production/newsyslog-mempool-nginx.conf
Labels: ops

#738 Feature: New charts library.
  frontend/cypress/integration/mainnet/mainnet.spec.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.constants.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/fee-distribution-graph/fee-distribution-graph.component.html
  frontend/src/app/components/fee-distribution-graph/fee-distribution-graph.component.scss
  frontend/src/app/components/fee-distribution-graph/fee-distribution-graph.component.ts
  frontend/src/app/components/incoming-transactions-graph/incoming-transactions-graph.component.html
  frontend/src/app/components/incoming-transactions-graph/incoming-transactions-graph.component.ts
  frontend/src/app/components/mempool-block/mempool-block.component.html
  frontend/src/app/components/mempool-block/mempool-block.component.scss
  frontend/src/app/components/mempool-graph/mempool-graph.component.html
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
  frontend/src/app/components/statistics/chartist.component.scss
  frontend/src/app/components/statistics/chartist.component.ts
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.scss
  frontend/src/app/components/statistics/statistics.component.ts
  frontend/src/app/components/television/television.component.html
  frontend/src/app/components/television/television.component.scss
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/styles.scss
Labels: enhancement, UI/UX

#789 Disable mouseover legend for mobile users.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug

#791 Add new locale: Romanian (ro)
  frontend/angular.json
  frontend/src/app/app.constants.ts
  frontend/src/locale/messages.ro.xlf
  nginx.conf
  production/nginx.conf
Labels: i18n

#792 Add new locale: Macedonian (mk)
  frontend/angular.json
  frontend/src/app/app.constants.ts
  frontend/src/locale/messages.mk.xlf
  nginx.conf
  production/nginx.conf
Labels: i18n

#803 Add Zeus LN as Community Integration
  frontend/src/app/components/about/about.component.html
  frontend/src/resources/profile/zeus.png
Labels: about

#805 Update the URL for Unchained Capital to unchained.com
  frontend/src/app/components/about/about.component.html
Labels: about

#809 Update production backend configuration files
  production/mempool-config.bisq.json
  production/mempool-config.liquid.json
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
Labels: ops

#810 L-BTC in circulation dashboard widgete
  frontend/src/app/app.module.ts
  frontend/src/app/components/lbtc-pegs-graph/lbtc-pegs-graph.component.html
  frontend/src/app/components/lbtc-pegs-graph/lbtc-pegs-graph.component.ts
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
Labels: enhancement, network:Liquid

#823 Fix tooltip mempool chart hover selection.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug

#825 Fix the focus effect on the mempool graph.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug

#837 Remove circle symbols when hovering the series.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug

#838 Fix parse numbers localized.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug

#839 Fix lint 'no-shadowed-variable'.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug

#843 Fix total percentage bar value.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug

#840 Fix confirmations button positioning.
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/styles.scss
Labels: bug

#846 Remove vbytesPipe from series data.
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: bug
