Repository mempool/mempool, pull requests merged in 2021-07, with the labels that each got.

#626 UI/UX - Blocks not visible on the TV page.
  frontend/cypress/integration/mainnet/mainnet.spec.ts
  frontend/src/app/components/television/television.component.html
  frontend/src/app/components/television/television.component.ts
Labels: bug

#627 UI/UX - Fix arrow position.
  frontend/src/app/app.module.ts
  frontend/src/app/bisq/bisq-transfers/bisq-transfers.component.html
  frontend/src/app/bisq/bisq-transfers/bisq-transfers.component.scss
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.scss
Labels: bug

#643 Update nginx configuration for cache settings and new locales
  nginx-mempool.conf
  nginx.conf
  production/nginx-mempool.conf
  production/nginx.conf
Labels: enhancement

#647 Add new page for Trademark Policy and Guidelines
  LICENSE
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/terms-of-service/terms-of-service.component.html
  frontend/src/app/components/trademark-policy/trademark-policy.component.html
  frontend/src/app/components/trademark-policy/trademark-policy.component.scss
  frontend/src/app/components/trademark-policy/trademark-policy.component.ts
  frontend/src/resources/mempool-blocks.png
  frontend/src/resources/mempool-space-logo-horizontal.png
Labels: legal

#654 Doc: Add new endpoints to api documentation.
  frontend/src/app/components/api-docs/api-docs.component.html
  frontend/src/app/components/api-docs/api-docs.component.ts
  frontend/src/app/components/api-docs/code-template.component.html
Labels: documentation

#650 Bugfix: Change mempool block time precision.
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/time-since/time-since.component.ts
  frontend/src/app/components/time-span/time-span.component.ts
  frontend/src/app/components/time-until/time-until.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
Labels: bug

#655 Add previous adjustment retarget.
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
Labels: enhancement

#671 Fix colorized unblinded transaction.
  frontend/cypress/integration/liquid/liquid.spec.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
Labels: bug

#674 Bugfix: show blocks on tv screen (mobile).
  frontend/cypress/integration/mainnet/mainnet.spec.ts
  frontend/src/app/components/television/television.component.scss
Labels: bug

#675 Fix concurrent asynchronous calls.
  frontend/cypress/integration/mainnet/mainnet.spec.ts
  frontend/cypress/support/websocket.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/television/television.component.html
  frontend/src/app/components/television/television.component.ts
Labels: bug
