Repository mempool/mempool, pull requests merged in 2022-11, with the labels that each got.

#2646 Configure zero base fee as default for core lighting
  production/install
Labels: ops, cla-signed

#2673 Use relative import paths in the frontend
  frontend/src/app/components/block-audit/block-audit.component.ts
Labels: cla-signed

#2676 [ops] Fix nvidia-driver package name
  production/install
Labels: ops, cla-signed

#2674 Update staging hosts for testing
  frontend/proxy.conf.staging.js
Labels: cla-signed

#2703 Proxy config for running esplora locally
  frontend/angular.json
  frontend/package.json
  frontend/proxy.conf.local-esplora.js
Labels: cla-signed

#2547 Click to close search dropdown
  frontend/src/app/components/search-form/search-form.component.html
  frontend/src/app/components/search-form/search-form.component.ts
Labels: cla-signed

#2337 Updated mempool debug log
  backend/src/api/mempool.ts
Labels: cla-signed

#2378 Disable mempool config
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/config.ts
  backend/src/index.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
  production/mempool-config.mainnet-lightning.json
  production/mempool-config.signet-lightning.json
  production/mempool-config.testnet-lightning.json
Labels: cla-signed, docker

#2564 [Feature] Search for block by timestamp
  backend/src/api/mining/mining-routes.ts
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#2617 Initial frontend runtime config support
  .gitignore
  docker/frontend/Dockerfile
  docker/frontend/entrypoint.sh
  frontend/angular.json
  frontend/generate-config.js
  frontend/src/index.bisq.html
  frontend/src/index.liquid.html
  frontend/src/index.mempool.html
  nginx-mempool.conf
  production/nginx/server-common.conf
Labels: cla-signed

#2663 Block audit tweaks
  backend/src/api/audit.ts
  backend/src/api/blocks.ts
  backend/src/api/mining/mining-routes.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksAuditsRepository.ts
  frontend/src/app/components/block-audit/block-audit.component.html
  frontend/src/app/components/block-audit/block-audit.component.ts
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.scss
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2667 Rescan unresolved LN channel force closes
  backend/src/api/database-migration.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2670 Show node tlv data & liquidity ads
  backend/src/api/database-migration.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/lightning/clightning/clightning-convert.ts
  backend/src/api/lightning/lightning-api.interface.ts
  backend/src/repositories/NodeRecordsRepository.ts
  backend/src/tasks/lightning/network-sync.service.ts
  frontend/src/app/lightning/node/liquidity-ad.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
  frontend/src/app/lightning/node/node.component.ts
Labels: cla-signed

#2678 fix error when navigating to huge transactions
  frontend/src/app/components/transaction/transaction-preview.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#2675 Update Docker GHA dependencies
  .github/workflows/on-tag.yml
Labels: dependencies, cla-signed, docker

#2681 Add support for renaming a mining pool without changing regex or address
  backend/src/api/pools-parser.ts
  frontend/src/app/app.constants.ts
Labels: cla-signed

#2684 Only show python example tab on ws tab
  frontend/src/app/docs/code-template/code-template.component.html
Labels: cla-signed

#2687 Add general-purpose disclaimer to top of faq
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.scss
Labels: cla-signed

#2689 resize block visualization instantly on window zoom and resize
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/block-scene.ts
Labels: cla-signed

#2694 calculate & show avg channel distance on node page
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/shared/common.utils.ts
Labels: cla-signed

#2649 Extend flow diagram to differentiate spent and unspent TXOs
  frontend/src/app/components/transaction/liquid-ublinding.ts
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction-preview.component.scss
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.scss
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.html
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.html
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.scss
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2664 db migration to clear obsolete block audit data
  backend/src/api/database-migration.ts
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#2698 enable new tx selection algorithm in own thread with config setting
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/blocks.ts
  backend/src/api/mempool-blocks.ts
  backend/src/api/mempool.ts
  backend/src/api/tx-selection-worker.ts
  backend/src/api/websocket-handler.ts
  backend/src/config.ts
  backend/src/index.ts
Labels: cla-signed

#2700 Add nunchuk to community integrations
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/profile/nunchuk.svg
Labels: cla-signed

#2705 better representation of zero-value outputs in flow diagram
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.html
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.scss
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2706 Fix tx preview alignment
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction-preview.component.scss
Labels: cla-signed

#2716 Reverse the direction of the flow diagram for RTL locales
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.html
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.scss
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2708 Support Maxmind Lite
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
Labels: cla-signed

#2654 Only show active nodes is isp page
  backend/src/api/explorer/nodes.api.ts
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.html
Labels: cla-signed

#2711 Remove FTX from the price feeds
  backend/src/tasks/price-feeds/ftx-api.ts
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#2679 "show more" instead of "show all" button for transaction inputs/outputs
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#2721 fix squashed tx flow diagram
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2723 Fix nginx redirects for /liquid etc.
  production/nginx/location-redirects.conf
Labels: ops, cla-signed

#2514 Feature: Add endpoint for PSBT nonWitnessUtxo inclusion
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/index.ts
Labels: cla-signed

#2728 Change imports to relative paths
  frontend/src/app/components/asset-circulation/asset-circulation.component.ts
  frontend/src/app/components/asset/asset.component.ts
  frontend/src/app/components/assets/assets-nav/assets-nav.component.ts
  frontend/src/app/components/assets/assets.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/services/assets.service.ts
Labels: cla-signed

#2722 Optimize force close penalty scans
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/config.ts
  backend/src/index.ts
  backend/src/tasks/lightning/forensics.service.ts
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2734 Fix bugs on the new block page
  backend/src/api/audit.ts
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/api/mining/mining-routes.ts
  backend/src/api/websocket-handler.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksAuditsRepository.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/block-audit/block-audit.component.html
  frontend/src/app/components/block-audit/block-audit.component.scss
  frontend/src/app/components/block-audit/block-audit.component.ts
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.html
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/interfaces/websocket.interface.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2726 Fix incorrect "Genesis" heading while loading the block page
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#2739 Fix broken tests on liquid
  backend/src/api/blocks.ts
Labels: cla-signed

#2740 update proxy.conf.staging target
  frontend/proxy.conf.staging.js
Labels: cla-signed

#2744 don't use block.extras on liquid
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#2742 Upgrade to Angular 14
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/server.run.ts
  frontend/server.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/bisq/bisq-market/bisq-market.component.html
  frontend/src/app/bisq/bisq-market/bisq-market.component.ts
  frontend/src/app/bisq/bisq-transactions/bisq-transactions.component.ts
  frontend/src/app/components/assets/assets-nav/assets-nav.component.ts
  frontend/src/app/components/assets/assets.component.ts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.html
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.html
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
  frontend/src/app/components/language-selector/language-selector.component.ts
  frontend/src/app/components/ngx-bootstrap-multiselect/ngx-bootstrap-multiselect.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/components/push-transaction/push-transaction.component.ts
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.ts
  frontend/src/app/docs/docs.routing.module.ts
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.ts
  frontend/src/app/lightning/group/group.component.html
  frontend/src/app/lightning/group/group.component.ts
  frontend/src/app/lightning/node-statistics-chart/node-statistics-chart.component.ts
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.html
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/main.server.ts
  frontend/src/styles.scss
  frontend/tsconfig.server.json
Labels: cla-signed

#2743 Disable ON UPDATE for blocks.blockTimestamp field
  backend/src/api/database-migration.ts
Labels: cla-signed

#2737 show CPFP info for mined transactions
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/api/blocks.ts
  backend/src/api/common.ts
  backend/src/api/database-migration.ts
  backend/src/api/mempool-blocks.ts
  backend/src/api/tx-selection-worker.ts
  backend/src/config.ts
  backend/src/indexer.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/CpfpRepository.ts
  backend/src/repositories/TransactionRepository.ts
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction-preview.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#2748 Upgrading some more frontend packages
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#2683 Lightning linked channel forensics
  backend/src/api/database-migration.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/api/lightning/lightning-api.interface.ts
  backend/src/tasks/lightning/forensics.service.ts
  backend/src/tasks/lightning/network-sync.service.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/lightning/channel/channel-close-box/channel-close-box.component.html
  frontend/src/app/lightning/channel/channel-close-box/channel-close-box.component.scss
  frontend/src/app/lightning/channel/channel-close-box/channel-close-box.component.spec.ts
  frontend/src/app/lightning/channel/channel-close-box/channel-close-box.component.ts
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channel/channel.component.ts
  frontend/src/app/lightning/lightning.module.ts
Labels: cla-signed

#2749 Mempool GBT config
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/websocket-handler.ts
  backend/src/config.ts
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
Labels: cla-signed

#2750 [ops] Increase nginx max concurrent streams
  production/nginx/http-basic.conf
Labels: ops, cla-signed

#2753 Remove annoying frontend console log
  frontend/src/app/components/bisq-master-page/bisq-master-page.component.ts
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.ts
  frontend/src/app/components/master-page/master-page.component.ts
Labels: cla-signed

#2751 Revert community integration icon size increase
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
Labels: cla-signed

#2731 save db schema version after each successful migration
  backend/src/api/database-migration.ts
Labels: cla-signed
