Repository mempool/mempool, pull requests merged in 2022-01, with the labels that each got.

#1085 Add Citadel as Community Integration on About page
  frontend/src/app/components/about/about.component.html
  frontend/src/resources/profile/runcitadel.svg
Labels: about

#1081 Update production configurations + README for v2.3
  production/README.md
  production/nginx-bisq.conf
  production/nginx-liquid.conf
  production/nginx-mempool-ssr.conf
  production/nginx-mempool.conf
  production/nginx.conf
  production/nginx/http-basic.conf
  production/nginx/http-language.conf
  production/nginx/http-proxy-cache.conf
  production/nginx/location-api-v1-contributors.conf
  production/nginx/location-api-v1-donations-images.conf
  production/nginx/location-api-v1-donations.conf
  production/nginx/location-api.conf
  production/nginx/location-liquid-api.conf
  production/nginx/location-liquidtestnet-api.conf
  production/nginx/location-redirects.conf
  production/nginx/location-signet-api.conf
  production/nginx/location-testnet-api.conf
  production/nginx/nginx.conf
  production/nginx/server-bisq.conf
  production/nginx/server-common.conf
  production/nginx/server-electrs.conf
  production/nginx/server-liquid.conf
  production/nginx/server-mempool.conf
  production/nginx/upstream-electrs.conf
  production/nginx/upstream-mempool.conf
Labels: ops

#1111 Add production Tor configuration to repo
  production/nginx/nginx.conf
  production/torrc
Labels: ops

#1134 Add nginx cache warmer script for production use
  production/nginx-cache-warmer
  production/nginx/http-proxy-cache.conf
  production/nginx/location-api.conf
Labels: ops

#1140 Fix newsyslog.conf owner and pidfile location
  production/newsyslog-mempool-nginx.conf
Labels: ops

#1144 Update production nginx.conf resource cache times
  production/nginx/server-common.conf
Labels: ops

#1176 Update Liquid tests
  .github/workflows/cypress.yml
  frontend/cypress/integration/liquid/liquid.spec.ts
  frontend/cypress/integration/liquidtestnet/liquidtestnet.spec.ts
  frontend/package.json
  frontend/src/app/components/transactions-list/transactions-list.component.html
Labels: network:Liquid, dev-environment

#1175 Update Cypress to v9.3.1
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies, dev-environment

#1177 Fix broken link on the Bisq transaction page
  frontend/src/app/bisq/bisq-transaction/bisq-transaction.component.html
Labels: bug

#1193 Increase nginx send_timeout and keepalive_requests
  nginx.conf
  production/nginx/http-basic.conf
Labels: ops

#1198 Enable nginx warm cache for mining pools API data
  production/nginx-cache-warmer
  production/nginx/location-api.conf
Labels: ops

#1199 Let backend set its own HTTP cache time headers for APIs
  production/nginx/location-api.conf
Labels: ops
