Repository mempool/mempool, pull requests merged in 2022-02, with the labels that each got.

#1208 Replaced /mining/pools?interval=X by /mining/pools/X
  backend/src/index.ts
  backend/src/routes.ts
  frontend/src/app/services/api.service.ts
  production/nginx-cache-warmer
Labels: cla-signed

#1207 Set proper mining pool page title - Rename "Name" to "Pool"
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#1160 outputs of genesis coinbase are always unspent
  backend/src/api/bitcoin/bitcoin-api.ts
Labels: cla-signed

#1215 Proxy all /api and /api/v1 requests to local nodejs server
  frontend/proxy.conf.local.js
Labels: cla-signed

#1212 Wrap custom blocks fields into a sub object of IEsplora.Blocks
  backend/src/api/blocks.ts
  backend/src/api/websocket-handler.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/components/tx-fee-rating/tx-fee-rating.component.ts
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/interfaces/electrs.interface.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/interfaces/websocket.interface.ts
  frontend/src/app/services/electrs-api.service.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#1219 Adding a "mixed" dev proxy
  frontend/angular.json
  frontend/package.json
  frontend/proxy.conf.mixed.js
Labels: cla-signed

#1218 Local dev proxy working with all base modules
  frontend/proxy.conf.local.js
Labels: cla-signed

#1213 Fetch conversion rates over Tor
  README.md
  backend/mempool-config.sample.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/fiat-conversion.ts
  backend/src/config.ts
  backend/tsconfig.json
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#1228 Run tests in Staging
  .github/workflows/cypress.yml
  frontend/angular.json
  frontend/package.json
  frontend/proxy.conf.js
  frontend/proxy.conf.staging.js
Labels: cla-signed

#1224 Featured assets and asset groups
  backend/src/index.ts
  backend/src/routes.ts
  frontend/cypress/integration/liquid/liquid.spec.ts
  frontend/cypress/integration/liquidtestnet/liquidtestnet.spec.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/assets/assets.component.html
  frontend/src/app/assets/assets.component.spec.ts
  frontend/src/app/assets/assets.component.ts
  frontend/src/app/components/asset/asset.component.html
  frontend/src/app/components/asset/asset.component.ts
  frontend/src/app/components/assets/asset-group/asset-group.component.html
  frontend/src/app/components/assets/asset-group/asset-group.component.scss
  frontend/src/app/components/assets/asset-group/asset-group.component.ts
  frontend/src/app/components/assets/assets-featured/assets-featured.component.html
  frontend/src/app/components/assets/assets-featured/assets-featured.component.scss
  frontend/src/app/components/assets/assets-featured/assets-featured.component.ts
  frontend/src/app/components/assets/assets-nav/assets-nav.component.html
  frontend/src/app/components/assets/assets-nav/assets-nav.component.scss
  frontend/src/app/components/assets/assets-nav/assets-nav.component.ts
  frontend/src/app/components/assets/assets.component.html
  frontend/src/app/components/assets/assets.component.scss
  frontend/src/app/components/assets/assets.component.ts
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/services/api.service.ts
  frontend/src/app/services/assets.service.ts
  production/nginx/location-api-v1-services.conf
Labels: cla-signed

#1225 Add EXTERNAL_ASSETS defaults to the Docker start script and the README
  README.md
  docker/backend/start.sh
Labels: cla-signed

#1230 Disable featured assets test for testnet
  frontend/cypress/integration/liquidtestnet/liquidtestnet.spec.ts
Labels: cla-signed

#1180 add log priority option for stdout log
  README.md
  backend/mempool-config.sample.json
  backend/src/config.ts
  backend/src/logger.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#1234 Cypress improvements
  .github/workflows/cypress.yml
  README.md
Labels: cla-signed

#1233 sync-assets: Download pool logos from github
  frontend/.gitignore
  frontend/sync-assets.js
Labels: cla-signed

#1232 Remove debug return which break the UX the first time we open mempool
  backend/src/api/blocks.ts
Labels: cla-signed

#1192 Allow TV view time span switch through url fragment
  frontend/src/app/components/television/television.component.html
  frontend/src/app/components/television/television.component.ts
Labels: cla-signed

#1220 Duplicated db blocks insertion attempts are expected
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#1240 Consider we're synced with the mempool if we cached 99% of pending txs
  backend/src/api/mempool.ts
Labels: cla-signed

#1239 Refactor docs
  frontend/src/app/components/docs/api-docs-data.ts
  frontend/src/app/components/docs/api-docs-nav.component.html
  frontend/src/app/components/docs/api-docs-nav.component.scss
  frontend/src/app/components/docs/api-docs-nav.component.ts
  frontend/src/app/components/docs/api-docs.component.html
  frontend/src/app/components/docs/api-docs.component.scss
  frontend/src/app/components/docs/api-docs.component.ts
  frontend/src/app/components/docs/code-template.component.ts
Labels: cla-signed

#1235 Added /api/v1/blocks-extras endpoint
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/index.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/PoolsRepository.ts
  backend/src/routes.ts
  docker/backend/mempool-config.json
Labels: cla-signed

#1248 implement /api/mempool for home users (romanz/electrs backend)
  backend/src/api/bitcoin/bitcoin-api.interface.ts
  backend/src/api/mempool.ts
  backend/src/routes.ts
Labels: cla-signed

#1243 Don't wait for 100% mempool sync before starting block indexing
  backend/src/api/blocks.ts
  backend/src/api/mempool.ts
Labels: cla-signed

#1252 Remove duplicated tests
  frontend/cypress/integration/mainnet/mainnet.spec.ts
Labels: cla-signed

#1250 Provide a way to completely disable block indexing and mining menu
  backend/src/api/blocks.ts
  backend/src/api/common.ts
  frontend/mempool-frontend-config.sample.json
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#1242 Created mining pool stats page
  backend/src/api/common.ts
  backend/src/api/mining.ts
  backend/src/index.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/PoolsRepository.ts
  backend/src/routes.ts
  frontend/server.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/components/pool/pool.component.html
  frontend/src/app/components/pool/pool.component.scss
  frontend/src/app/components/pool/pool.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#1253 Index more block data
  backend/src/api/database-migration.ts
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#1255 Create difficulty chart component
  backend/src/api/blocks.ts
  backend/src/api/mining.ts
  backend/src/index.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/routes.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.html
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.scss
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#1257 Change pool ranking pie chart colors
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#1254 Create mining dashboard page
  backend/src/api/blocks.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.scss
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.html
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.scss
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.ts
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.scss
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#1258 When blocks need re-indexing, truncate the table
  backend/src/api/database-migration.ts
Labels: cla-signed

#1261 Update docker default min loglevel to info
  README.md
  docker/backend/start.sh
Labels: cla-signed

#1245 Display top featured assets on Liquid dashboard
  frontend/src/app/app.module.ts
  frontend/src/app/bitcoin.utils.ts
  frontend/src/app/components/asset-circulation/asset-circulation.component.html
  frontend/src/app/components/asset-circulation/asset-circulation.component.scss
  frontend/src/app/components/asset-circulation/asset-circulation.component.ts
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.ts
Labels: cla-signed

#1266 Tweak text on About page so it can be displayed on all networks
  frontend/src/app/components/about/about.component.html
Labels: about, cla-signed

#1265 Add nix-bitcoin to Community Integrations on About page
  frontend/src/app/components/about/about.component.html
  frontend/src/resources/profile/nix-bitcoin.png
Labels: about, cla-signed

#1267 Move the Become Sponsor button higher on About page
  frontend/src/app/components/about/about.component.html
Labels: about, cla-signed

#1268 Inline all Enterprise Sponsor logos on About page
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/profile/blockstream.svg
  frontend/src/resources/profile/exodus.svg
  frontend/src/resources/profile/foundry.svg
  frontend/src/resources/profile/gemini.svg
  frontend/src/resources/profile/spiral.svg
  frontend/src/resources/profile/unchained.svg
Labels: about, cla-signed

#1223 detect lightning htlc and unilateral close + fix multisig badge
  frontend/src/app/components/address-labels/address-labels.component.ts
Labels: cla-signed

#1272 Tweak new charts design
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/HashratesRepository.ts
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.html
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.scss
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#1274 Show block reward in the mining dashboard
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
Labels: cla-signed

#1273 Display asset circulating amount more nicely fixing overflow
  frontend/src/app/app.module.ts
  frontend/src/app/components/asset-circulation/asset-circulation.component.html
  frontend/src/app/components/asset-circulation/asset-circulation.component.ts
  frontend/src/app/shared/pipes/amount-shortener.pipe.ts
Labels: cla-signed

#1275 Merge hashrate and difficulty components - Cleanup mining design overall
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/routes.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.html
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.scss
  frontend/src/app/components/difficulty-chart/difficulty-chart.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.scss
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/services/mining.service.ts
Labels: cla-signed

#1277 Remove block subsidy from mempool blocks
  backend/src/api/blocks.ts
  backend/src/mempool.interfaces.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#1278 Handle missing asset registry assets
  frontend/src/app/components/transactions-list/transactions-list.component.html
Labels: cla-signed

#1279 Add proxy support for Liquid Testnet
  frontend/proxy.conf.local.js
  frontend/proxy.conf.mixed.js
Labels: cla-signed

#1280 Show tx value sum if complete unblinding data is provided
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#1281 Fixed incoming transactions bar on the status page
  frontend/src/app/components/footer/footer.component.html
  frontend/src/app/components/footer/footer.component.ts
Labels: cla-signed

#1282 Fix status page regex
  frontend/cypress/integration/mainnet/mainnet.spec.ts
Labels: bug, cla-signed

#1283 Update Cypress to v9.5.0
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies, cla-signed

#1284 Upgrade frontend deps: Angular 13.2, echarts 5.3, fortawesome
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1288 Merge pool share and dominance into one widget
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.scss
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed
