Repository mempool/mempool, pull requests merged in 2022-09, with the labels that each got.

#2483 Fix unfurler race condition again
  frontend/src/app/components/address/address-preview.component.ts
  frontend/src/app/components/block/block-preview.component.ts
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction-preview.component.ts
  frontend/src/app/lightning/channel/channel-preview.component.ts
  frontend/src/app/lightning/node/node-preview.component.ts
  frontend/src/app/services/opengraph.service.ts
  unfurler/src/concurrency/ReusablePage.ts
  unfurler/src/index.ts
Labels: cla-signed

#2484 Use new mempool preview image as default
  unfurler/src/routes.ts
Labels: cla-signed

#2485 Restyle lightning preview titles to match main pages
  frontend/src/app/components/address/address-preview.component.html
  frontend/src/app/components/address/address-preview.component.scss
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
  frontend/src/app/components/master-page-preview/master-page-preview.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.scss
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction-preview.component.scss
  frontend/src/app/lightning/channel/channel-preview.component.html
  frontend/src/app/lightning/channel/channel-preview.component.scss
  frontend/src/app/lightning/node/node-preview.component.html
  frontend/src/app/lightning/node/node-preview.component.scss
  frontend/src/styles.scss
Labels: cla-signed

#2469 Only show active channels on world map
  backend/src/api/explorer/channels.api.ts
  frontend/src/app/lightning/node/node.component.html
Labels: cla-signed

#2472 Add lightning api docs
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#2501 Renamed capacity to liquidity
  frontend/src/app/lightning/nodes-ranking/oldest-nodes/oldest-nodes.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.html
Labels: cla-signed

#2502 Show 0 sats when country has no liquidity
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.html
Labels: cla-signed

#2500 Renamed "City" to "Location"
  backend/src/api/explorer/nodes.api.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.html
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.html
  frontend/src/app/lightning/nodes-ranking/oldest-nodes/oldest-nodes.component.html
  frontend/src/app/lightning/nodes-ranking/oldest-nodes/oldest-nodes.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.ts
Labels: cla-signed

#2096 Simplify packaging for backend
  backend/README.md
  backend/package.json
  backend/src/api/backend-info.ts
  backend/src/api/fetch-version.ts
  backend/src/config.ts
  backend/src/tasks/price-updater.ts
  docker/backend/Dockerfile
  docker/backend/start.sh
  docker/backend/wait-for-it.sh
  docker/init.sh
Labels: cla-signed, docker

#2454 Remove the mempool restart script in prod install
  production/install
  production/mempool-restart-all
Labels: ops, cla-signed

#2522 Show clearnet nodes on world map
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/components/asset-circulation/asset-circulation.component.ts
  frontend/src/app/lightning/nodes-map/nodes-map.component.html
  frontend/src/app/lightning/nodes-map/nodes-map.component.ts
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2523 Fix missing seo in lightning pages
  frontend/src/app/lightning/channel/channel.component.ts
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
  frontend/src/app/lightning/nodes-ranking/oldest-nodes/oldest-nodes.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.ts
Labels: cla-signed

#2529 Change isp pie chart threshold from 0.5% to 0.4%
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
Labels: cla-signed

#2504 Show '-' when value is not defined in channel page
  frontend/src/app/lightning/channel/channel-box/channel-box.component.html
  frontend/src/app/shared/components/sats/sats.component.html
  frontend/src/app/shared/components/sats/sats.component.ts
Labels: cla-signed

#2512 If a channel is closed, show closing date instead of last update
  backend/src/api/explorer/channels.api.ts
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/shared/components/timestamp/timestamp.component.html
  frontend/src/app/shared/components/timestamp/timestamp.component.ts
Labels: cla-signed

#2517 Add skeleton loader in node per isp/country lists
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.html
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.ts
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.html
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.ts
Labels: cla-signed

#2518 Only scan for closed channels when there is a new block
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2078 frontend: Don't copy `resources`, shrink static size
  frontend/angular.json
  frontend/package.json
  frontend/sync-assets.js
  nginx-mempool.conf
  production/mempool.crontab
  production/nginx/server-common.conf
Labels: cla-signed

#2532 Add more Community Integrations on About page
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/profile/btcpayserver.svg
  frontend/src/resources/profile/electrum.jpg
  frontend/src/resources/profile/electrum.png
  frontend/src/resources/profile/lnbits.svg
Labels: about, cla-signed

#2524 Update ISP pie chart colors
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
Labels: cla-signed

#2526 Lightning dashboard -> Lightning network
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.ts
Labels: cla-signed

#2520 Fix wrong skeleton labels
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
Labels: cla-signed

#2521 Fix preview tx diagram for zero value transactions
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2507 When using clightning, use listchannels.delay as cltv_delta
  backend/src/api/lightning/clightning/clightning-convert.ts
Labels: cla-signed

#2516 Show that we don't know where a node is because it's running on tor
  frontend/src/app/lightning/node/node.component.html
Labels: cla-signed

#2506 Fix sed command for the pools json urls
  docker/backend/start.sh
Labels: cla-signed, docker

#2367 Tooling: Eslint force triple equals
  backend/.eslintrc
  frontend/.eslintrc
Labels: cla-signed

#2534 Removing extra capacity row
  frontend/src/app/lightning/channel/channel.component.html
Labels: cla-signed

#2535 Add network to preview headers & inc font size
  frontend/src/app/components/address/address-preview.component.html
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.scss
  frontend/src/app/components/master-page-preview/preview-title.component.html
  frontend/src/app/components/master-page-preview/preview-title.component.ts
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/lightning/channel/channel-preview.component.html
  frontend/src/app/lightning/node/node-preview.component.html
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2538 Disable block viz/map loading spinners on previews
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.html
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/lightning/channel/channel-preview.component.html
  frontend/src/app/lightning/node/node-preview.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2539 Fix unfurler config set network to liquid
  production/unfurler-config.liquid.json
Labels: ops, cla-signed

#2540 Dashboard node statistics skeleton loader fix
  frontend/src/app/lightning/node-statistics/node-statistics.component.html
Labels: cla-signed

#2542 Add Lightning ISP preview
  frontend/src/app/lightning/lightning-previews.module.ts
  frontend/src/app/lightning/lightning-previews.routing.module.ts
  frontend/src/app/lightning/nodes-map/nodes-map.component.html
  frontend/src/app/lightning/nodes-map/nodes-map.component.scss
  frontend/src/app/lightning/nodes-map/nodes-map.component.ts
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp-preview.component.html
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp-preview.component.scss
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp-preview.component.ts
  unfurler/src/routes.ts
Labels: cla-signed

#2541 Refactor preview routes into separate module
  frontend/src/app/app-routing.module.ts
  frontend/src/app/lightning/node/node-preview.component.ts
  frontend/src/app/previews.module.ts
  frontend/src/app/previews.routing.module.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2543 Adjust block preview layout
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
Labels: cla-signed

#2486 Add docker lightning backend config
  contributors/WesVleuten.txt
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: docker

#2509 Show tooltip on location is truncated
  frontend/src/app/shared/components/geolocation/geolocation.component.html
  frontend/src/app/shared/components/geolocation/geolocation.component.ts
Labels: cla-signed

#2554 Add logging & syslog support to unfurler
  unfurler/config.sample.json
  unfurler/puppeteer.config.json
  unfurler/src/concurrency/ReusablePage.ts
  unfurler/src/config.ts
  unfurler/src/index.ts
  unfurler/src/logger.ts
Labels: cla-signed

#2565 Allow address label to overflow without pushing UI
  frontend/src/app/components/address-labels/address-labels.component.html
  frontend/src/app/components/address-labels/address-labels.component.scss
Labels: cla-signed

#2561 Optimize transaction diagram component
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2562 Tx page diagram
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.scss
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.html
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.scss
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.html
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.scss
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2563 Add mining pool preview
  frontend/src/app/components/pool/pool-preview.component.html
  frontend/src/app/components/pool/pool-preview.component.scss
  frontend/src/app/components/pool/pool-preview.component.ts
  frontend/src/app/previews.module.ts
  frontend/src/app/previews.routing.module.ts
  unfurler/src/routes.ts
Labels: cla-signed

#2558 Mempool node group page
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/lightning/group/group.component.html
  frontend/src/app/lightning/group/group.component.scss
  frontend/src/app/lightning/group/group.component.ts
  frontend/src/app/lightning/lightning-api.service.ts
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/lightning.routing.module.ts
  frontend/src/app/lightning/nodes-map/nodes-map.component.ts
Labels: cla-signed

#2548 Suggest block height in search result
  frontend/src/app/components/search-form/search-form.component.html
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/components/search-form/search-results/search-results.component.html
  frontend/src/app/components/search-form/search-results/search-results.component.ts
Labels: cla-signed

#2572 Adding MempoolSharedModule
  frontend/src/app/app.module.ts
Labels: cla-signed

#2510 Show zero base fee tag on channels
  frontend/src/app/lightning/channel/channel-box/channel-box.component.html
  frontend/src/app/lightning/channel/channel-box/channel-box.component.scss
  frontend/src/app/shared/pipes/amount-shortener.pipe.ts
Labels: cla-signed

#2573 Fix "undefined" location in node ranking
  frontend/src/app/shared/components/geolocation/geolocation.component.ts
Labels: cla-signed

#2568 Mempool svg logo bug fix
  frontend/src/app/components/svg-images/svg-images.component.html
Labels: cla-signed

#2576 Updating info button styling
  frontend/src/styles.scss
Labels: cla-signed

#2577 New button light color
  frontend/src/styles.scss
Labels: cla-signed

#2569 Clipboard buttons fix
  frontend/src/app/components/clipboard/clipboard.component.html
  frontend/src/app/components/clipboard/clipboard.component.ts
  frontend/src/app/lightning/group/group.component.html
  frontend/src/app/lightning/node/node.component.html
Labels: cla-signed

#2575 Improve transaction flow diagram drawing algorithm
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2574 Only show tor badge in node page if actually running on tor only
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
Labels: cla-signed

#2519 Show tor+clearnet node series in chart
  backend/src/api/explorer/statistics.api.ts
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
Labels: cla-signed

#2551 Fix spacing on websocket api examples
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/code-template/code-template.component.ts
Labels: cla-signed

#2550 Add python example for websocket api docs
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/code-template/code-template.component.html
  frontend/src/app/docs/code-template/code-template.component.ts
Labels: cla-signed

#2578 Revert info button color change
  frontend/src/styles.scss
Labels: cla-signed

#2385 Log correct maxmind mysql updates - fix stats import processed files counter
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2582 Require the resources path as input to sync assets
  frontend/package.json
  frontend/sync-assets.js
Labels: cla-signed

#2585 Updating search bar placeholder
  frontend/src/app/components/search-form/search-form.component.html
Labels: cla-signed

#2594 Add a time turner toggle
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/block-scene.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.scss
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.html
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.scss
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2593 Revert "New button light color"
  frontend/src/styles.scss
Labels: cla-signed

#2595 Fix for add class js error
  frontend/src/app/components/blockchain/blockchain.component.html
Labels: cla-signed

#2591 Toggle option for transaction flow diagram with query param
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.scss
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#2589 Add preview for lightning group pages
  frontend/src/app/lightning/group/group-preview.component.html
  frontend/src/app/lightning/group/group-preview.component.scss
  frontend/src/app/lightning/group/group-preview.component.ts
  frontend/src/app/lightning/lightning-previews.module.ts
  frontend/src/app/lightning/lightning-previews.routing.module.ts
  unfurler/src/routes.ts
Labels: cla-signed

#2596 Updating flip icon
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed
