Repository mempool/mempool, pull requests merged in 2022-08, with the labels that each got.

#2221 use lnd rest api
  backend/mempool-config.sample.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/lightning/lightning-api.interface.ts
  backend/src/api/lightning/lnd/lnd-api.ts
  backend/src/config.ts
  backend/src/tasks/lightning/node-sync.service.ts
  backend/src/tasks/lightning/stats-updater.service.ts
Labels: cla-signed

#2226 Fix missing pub key, capacity and channel count for node lists
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2227 Re-enabled channels world map click event
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2233 Set default values when pubkey, capacity and channels are missing from top nodes
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2234 Fix UX interaction with channels map
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2235 Limit matomo to mempool.space
  frontend/src/app/services/enterprise.service.ts
Labels: cla-signed

#2231 Import LN historical statistics (network wide + per node)
  backend/package-lock.json
  backend/package.json
  backend/src/api/database-migration.ts
  backend/src/config.ts
  backend/src/index.ts
  backend/src/tasks/lightning/stats-updater.service.ts
  backend/src/tasks/lightning/sync-tasks/funding-tx-fetcher.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2240 Add clightning support to the lightning backend
  backend/src/api/lightning/clightning/clightning-client.ts
  backend/src/api/lightning/clightning/clightning-convert.ts
  backend/src/api/lightning/lightning-api-abstract-factory.ts
  backend/src/api/lightning/lightning-api-factory.ts
  backend/src/config.ts
  backend/src/index.ts
  backend/src/tasks/lightning/network-sync.service.ts
  backend/src/tasks/lightning/sync-tasks/funding-tx-fetcher.ts
Labels: cla-signed

#2241 Rewrite queries to get top nodes by channels and capacity
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2237 [ops] Fix cron jobs to update liquid assets hourly
  production/elements.crontab
  production/mempool.crontab
Labels: ops, cla-signed

#2236 [ops] Fix syslog permissions for /var/log/mempool
  production/newsyslog-mempool-backend.conf
Labels: ops, cla-signed

#2253 Re-applied missing fix from https://github.com/mempool/mempool/pull/2233
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2244 Fix daily LN stats crash
  backend/src/api/lightning/clightning/clightning-convert.ts
  backend/src/index.ts
  backend/src/tasks/lightning/stats-updater.service.ts
  backend/src/tasks/lightning/sync-tasks/funding-tx-fetcher.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2255 Update latest stats every 10 minutes
  backend/src/config.ts
  backend/src/tasks/lightning/stats-updater.service.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2250 Fix node page and display real time data
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/channels.routes.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.scss
  frontend/src/app/lightning/channels-list/channels-list.component.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/shared/common.utils.ts
Labels: cla-signed

#2254 Always show channels map in node page - auto zoom on the node
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2264 Right align mempool logo on mobile with dual logos
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
Labels: cla-signed

#2252 Fix CLN channel short_id conversion
  backend/src/api/lightning/clightning/clightning-convert.ts
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2259 Make sure lightning stats are not duplicated in db
  backend/src/api/database-migration.ts
  backend/src/tasks/lightning/stats-updater.service.ts
Labels: cla-signed

#2260 Don't insert stats in the future
  backend/src/tasks/lightning/stats-updater.service.ts
Labels: cla-signed

#2251 Don't throw an exception when cln connection is down
  backend/src/api/lightning/clightning/clightning-client.ts
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2270 Rewrite channels map component using native echart
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2267 Add `nodes.status` field
  backend/src/api/common.ts
  backend/src/api/database-migration.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/config.ts
  backend/src/database.ts
  backend/src/tasks/lightning/network-sync.service.ts
  backend/src/tasks/lightning/stats-updater.service.ts
  backend/src/tasks/lightning/sync-tasks/funding-tx-fetcher.ts
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2086 Missing blocks prices
  backend/src/api/blocks.ts
  backend/src/api/mining/mining.ts
  backend/src/indexer.ts
  backend/src/repositories/PricesRepository.ts
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#2262 Add Core Lighting for FreeBSD in prod installer
  production/install
Labels: ops, cla-signed

#2268 Make mining pools url configurable
  backend/mempool-config.sample.json
  backend/src/config.ts
  backend/src/tasks/pools-updater.ts
  docker/README.md
  docker/backend/start.sh
Labels: cla-signed

#2273 Show channel on the map in channel page
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/channels.routes.ts
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channel/channel.component.ts
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2277 Add ISP chart in the dashboard - Fix mobile layout - Start polishing
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
  frontend/src/app/lightning/nodes-list/nodes-list.component.html
  frontend/src/app/lightning/nodes-list/nodes-list.component.scss
  frontend/src/app/lightning/nodes-list/nodes-list.component.ts
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.scss
Labels: cla-signed

#2265 Convert short_id to integer id with clightning backend before returning the graph
  backend/src/api/common.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/api/lightning/clightning/clightning-convert.ts
Labels: cla-signed

#2275 Fix channel rendering issue
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2278 Add nofollow to all api link examples
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#2274 Disable country highlight - Update node styling
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2280 Remove doc scroll listener after navigating away
  frontend/src/app/docs/api-docs/api-docs.component.ts
Labels: cla-signed

#2282 Fix recursive call in LN network updater
  backend/src/tasks/lightning/network-sync.service.ts
  backend/src/tasks/lightning/stats-updater.service.ts
Labels: cla-signed

#2285 Fixing broken Matomo och bisq and liquid
  frontend/src/app/components/bisq-master-page/bisq-master-page.component.ts
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.ts
  frontend/src/app/services/enterprise.service.ts
Labels: cla-signed

#2286 Fix LN stats node per network count
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2287 Show two LN network stats charts on dashboard
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.scss
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.scss
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
  frontend/src/app/shared/pipes/amount-shortener.pipe.ts
Labels: cla-signed

#2279 Avoid linking cpfp link api examples
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#2247 Faster unfurls
  frontend/src/app/components/address/address-preview.component.html
  frontend/src/app/components/address/address-preview.component.scss
  frontend/src/app/components/address/address-preview.component.ts
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
  frontend/src/app/components/block/block-preview.component.ts
  frontend/src/app/components/master-page-preview/master-page-preview.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.scss
  frontend/src/app/services/opengraph.service.ts
  frontend/src/app/services/seo.service.ts
  frontend/src/styles.scss
  unfurler/config.sample.json
  unfurler/package.json
  unfurler/puppeteer.config.json
  unfurler/src/concurrency/ReusablePage.ts
  unfurler/src/config.ts
  unfurler/src/index.ts
  unfurler/src/language/lang.ts
Labels: cla-signed

#2294 Create and populate nodes_socket table
  backend/src/api/common.ts
  backend/src/api/database-migration.ts
  backend/src/api/lightning/clightning/clightning-convert.ts
  backend/src/api/lightning/lightning-api.interface.ts
  backend/src/repositories/BlocksAuditsRepository.ts
  backend/src/repositories/NodesSocketsRepository.ts
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2295 Reduce pool ranking pie chart min slice
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#2281 Fix the OOM issue when building the frontend docker image for armv7
  .github/workflows/on-tag.yml
Labels: cla-signed, docker

#2019 Start adding unit tests to the backend
  .github/workflows/ci.yml
  backend/.gitignore
  backend/jest.config.ts
  backend/package-lock.json
  backend/package.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: cla-signed

#2289 Fix the latest backend Docker startup vars
  docker/backend/start.sh
Labels: cla-signed

#2284 Removing sponsor. Link to Enterprise sponsor
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/app/components/about/about.component.ts
  frontend/src/app/components/sponsor/sponsor.component.html
  frontend/src/app/components/sponsor/sponsor.component.scss
  frontend/src/app/components/sponsor/sponsor.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2283 Lightning unfurls
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/master-page-preview/master-page-preview.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.ts
  frontend/src/app/lightning/channel/channel-preview.component.html
  frontend/src/app/lightning/channel/channel-preview.component.scss
  frontend/src/app/lightning/channel/channel-preview.component.ts
  frontend/src/app/lightning/lightning-previews.module.ts
  frontend/src/app/lightning/lightning-previews.routing.module.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/node/node-preview.component.html
  frontend/src/app/lightning/node/node-preview.component.scss
  frontend/src/app/lightning/node/node-preview.component.ts
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/shared/shared.module.ts
  unfurler/src/index.ts
Labels: cla-signed

#2299 Fix wrong size of translators avatars
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
Labels: cla-signed

#2301 Add basic transaction link previews
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction-preview.component.scss
  frontend/src/app/components/transaction/transaction-preview.component.ts
  frontend/src/app/shared/shared.module.ts
  unfurler/src/index.ts
Labels: cla-signed

#2305 Refactor ISP pie chart to make it more consitent
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/components/toggle/toggle.component.html
  frontend/src/app/shared/components/toggle/toggle.component.ts
Labels: cla-signed

#2306 Refactor LN stats import
  backend/package-lock.json
  backend/package.json
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2315 Refactor top nodes widgets, create related top 100 nodes pages
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  backend/src/mempool.interfaces.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/lightning/lightning-api.service.ts
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/lightning.routing.module.ts
  frontend/src/app/lightning/nodes-ranking/nodes-ranking.component.html
  frontend/src/app/lightning/nodes-ranking/nodes-ranking.component.scss
  frontend/src/app/lightning/nodes-ranking/nodes-ranking.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.scss
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.scss
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.ts
Labels: cla-signed

#2327 Hide features before feature activated
  frontend/src/app/components/tx-features/tx-features.component.html
Labels: cla-signed

#2328 Removing taproot privacy claims
  frontend/src/app/components/tx-features/tx-features.component.html
Labels: cla-signed

#2304 Fix sticky error state on block page
  frontend/src/app/components/block/block.component.ts
Labels: cla-signed

#2329 Reverted wrong fix in 2300
  backend/src/api/difficulty-adjustment.ts
Labels: cla-signed

#2334 Unpublish the Github Sponsor links
  .github/FUNDING.yml
Labels: cla-signed

#2319 Import json topology
  backend/src/api/common.ts
  backend/src/tasks/lightning/sync-tasks/funding-tx-fetcher.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: ⚡Lightning, cla-signed

#2318 Make sure LN importer won't crash the backend
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: ⚡Lightning, cla-signed

#2331 Use timestamp instead of date in stats tables
  backend/src/api/database-migration.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2311 Import historical channels
  backend/src/api/database-migration.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/index.ts
  backend/src/tasks/lightning/network-sync.service.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: ⚡Lightning, cla-signed

#2335 Fix undefined public_key
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2314 Fix node channel list pagination
  backend/src/api/explorer/channels.api.ts
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.ts
Labels: ⚡Lightning, cla-signed

#2342 Display opening and closing transactions on channel page
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/lightning/channel/channel-box/channel-box.component.scss
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channel/channel.component.scss
  frontend/src/app/lightning/channel/channel.component.ts
Labels: cla-signed

#2320 Fix wrong tooltip % in isp pie chart
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
Labels: ⚡Lightning, cla-signed

#2322 Fix "indexing in progress" message in ln dashboard
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.html
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.scss
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: ⚡Lightning, cla-signed

#2323 Increase node size in channel map on node/channel pages
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: ⚡Lightning, cla-signed

#2324 Create geolocation component to format geolocation data
  backend/src/api/explorer/nodes.api.ts
  frontend/src/app/lightning/node/node-preview.component.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.ts
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.html
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.ts
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.html
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.ts
  frontend/src/app/shared/common.utils.ts
  frontend/src/app/shared/components/geolocation/geolocation.component.html
  frontend/src/app/shared/components/geolocation/geolocation.component.scss
  frontend/src/app/shared/components/geolocation/geolocation.component.ts
  frontend/src/app/shared/graphs.utils.ts
  frontend/src/app/shared/shared.module.ts
Labels: ⚡Lightning, cla-signed

#2325 Fix missing isp ids on isp pie chart
  backend/src/api/explorer/nodes.api.ts
Labels: ⚡Lightning, cla-signed

#2326 Hide map if there is not geolocation data available
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: ⚡Lightning, cla-signed

#2336 If a channel is closed, stop updating it
  backend/src/tasks/lightning/network-sync.service.ts
Labels: ⚡Lightning, cla-signed

#2338 Add missing lightning configuration variables where needed
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/config.ts
  docker/README.md
  docker/backend/start.sh
Labels: cla-signed

#2345 Node alias fulltext search
  backend/src/api/database-migration.ts
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2355 Fix network regex matching
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#2343 Fix for missing closing reason in channels list
  backend/src/api/explorer/channels.api.ts
Labels: cla-signed

#2351 Remove useless api call in channel page
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: ⚡Lightning, cla-signed

#2352 Add "Lightning node" and "Lighning channel" page title
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/node/node.component.html
Labels: ⚡Lightning, cla-signed

#2353 Add "beta" tag next to lightning menu
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
Labels: ⚡Lightning, cla-signed

#2354 Improve channels world map performances
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/channels.routes.ts
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
  frontend/src/app/services/api.service.ts
  production/nginx-cache-warmer
Labels: ⚡Lightning, cla-signed

#2361 Fix "cannot update channel list" error
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2366 Create active channel tree map component
  backend/src/api/explorer/channels.api.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/lightning-api.service.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/nodes-channels/node-channels.component.html
  frontend/src/app/lightning/nodes-channels/node-channels.component.scss
  frontend/src/app/lightning/nodes-channels/node-channels.component.ts
  frontend/src/app/shared/graphs.utils.ts
Labels: cla-signed

#2363 Wrap esplora call into try/catch when scanning channel forensics
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2371 Update node page layout
  frontend/src/app/lightning/node-statistics-chart/node-statistics-chart.component.scss
  frontend/src/app/lightning/node-statistics-chart/node-statistics-chart.component.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2362 Await mysql queries in order to avoid deadlock
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2374 Add missing closing div
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
Labels: cla-signed

#2370 Fix lightning map heights on preview pages
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
Labels: cla-signed

#2372 Hide subtitle if not widget
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: cla-signed

#2389 Add .local/bin to cln's path and install git-lfs in prod install
  production/install
Labels: ops, cla-signed

#2386 [ops] Change keybase notifications to ERR or higher priority
  production/syslog.conf
Labels: ops, cla-signed

#2375 Fix infitinite loading spinner and positioning
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2383 Import historical nodes
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2377 Node history chart full width if we can't display channel map
  frontend/src/app/lightning/node/node.component.html
Labels: cla-signed

#2381 Do not fetch node stats for channel tree graph
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/channels.routes.ts
Labels: cla-signed

#2394 Fix for empty tx value
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#2392 Numbers not included in node alias search
  backend/src/api/explorer/nodes.api.ts
Labels: ⚡Lightning, cla-signed

#2388 Fix path for newsyslog configs in prod installer
  production/install
  production/linux/rsyslog.conf
Labels: ops, cla-signed

#2397 Search bar placeholder text update
  frontend/src/app/components/search-form/search-form.component.html
Labels: cla-signed

#2399 Store capacity and channels in nodes table
  backend/src/api/database-migration.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2333 Fix: Difficulty API (REST) with frontend fixes
  backend/jest.config.ts
  backend/src/__tests__/api/difficulty-adjustment.test.ts
  backend/src/__tests__/config.test.ts
  backend/src/api/difficulty-adjustment.ts
  backend/testSetup.ts
  frontend/src/app/components/difficulty/difficulty.component.html
  frontend/src/app/components/difficulty/difficulty.component.ts
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#2402 Fix for broken SQL to load Lightning nodes on ISP page
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2404 [ops] Add nginx placeholders for unfurlbot configuration
  production/nginx/location-api-v1-services.conf
  production/nginx/location-testnet-api-v1-lightning.conf
  production/nginx/nginx.conf
  production/nginx/server-common.conf
Labels: cla-signed

#2405 [ops] Add nginx entrypoints for unfurler daemon
  production/nginx/server-common.conf
Labels: ops, cla-signed

#2410 [ops] Add production lightning backend configurations
  production/mempool-config.mainnet-lightning.json
  production/mempool-config.signet-lightning.json
  production/mempool-config.testnet-lightning.json
Labels: ops, cla-signed

#2408 Fixes multiple bugs with outspends and channels
  backend/src/api/explorer/channels.routes.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/interfaces/electrs.interface.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channel/channel.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2412 Fixing missing channel openings
  frontend/src/app/components/transactions-list/transactions-list.component.html
Labels: cla-signed

#2387 Hardcode some condition to invalidate imported topology files
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2419 [ops] Update prod scripts for unfurler and cache warmer
  production/mempool-build-all
  production/mempool-kill-all
  production/mempool-start-all
  production/nginx-cache-warmer
  production/unfurl-build
  production/unfurl-kill
  production/unfurl-start
  production/unfurler-config.liquid.json
  production/unfurler-config.mainnet.json
  unfurler/package.json
  unfurler/puppeteer.config.json
Labels: ops, cla-signed

#2414 Fix unfurls for lightning pages with no geodata
  frontend/src/app/lightning/channel/channel-preview.component.html
  frontend/src/app/lightning/node/node-preview.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2407 Start cln after Bitcoind in prod installer
  production/install
Labels: ops, cla-signed

#2413 Handle locale & preview in network detection regex
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#2360 Alternative transaction unfurl design
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction-preview.component.scss
  frontend/src/app/components/transaction/transaction-preview.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.html
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.scss
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2406 Only source mysql_credentials if present in prod install
  production/mempool-build-all
Labels: ops, cla-signed

#2422 [ops] Fix typo in build script
  production/mempool-build-all
Labels: cla-signed

#2418 Fix js crash in node page and add loading spinner to channel tree chart
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/nodes-channels/node-channels.component.html
  frontend/src/app/lightning/nodes-channels/node-channels.component.scss
  frontend/src/app/lightning/nodes-channels/node-channels.component.ts
Labels: ⚡Lightning, cla-signed

#2417 Truncate node alias if it's too long
  frontend/src/app/lightning/node/node.component.html
Labels: ⚡Lightning, cla-signed

#2421 Fix clipboard for node pubkey on channel page
  frontend/src/app/lightning/channel/channel-box/channel-box.component.html
Labels: cla-signed

#2415 Disable LN historical import if not mainnet
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: ⚡Lightning, cla-signed

#2416 Update <lightning> log tag to show the network if non mainnet
  backend/src/logger.ts
Labels: ⚡Lightning, cla-signed

#2409 Add closing type badge to channel header
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channel/channel.component.scss
Labels: ⚡Lightning, cla-signed

#2424 Possible fix for failing test
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#2420 Custom lazy loading strategy
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/app.preloading-strategy.ts
Labels: cla-signed

#2427 Add new lightning endpoints to warm cache
  production/nginx-cache-warmer
Labels: cla-signed

#2428 Use mainnet repo for nginx cache warmer script
  production/mempool-start-all
Labels: cla-signed

#2431 Disable smooth flag for LN lines charts
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: cla-signed

#2430 Use monospace font for addresses on mobile
  frontend/src/styles.scss
Labels: cla-signed

#2437 Fix open/close channel list button alignment
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.scss
Labels: cla-signed

#2440 Remove cache warmer from crontab. Now part of ./start script.
  production/mempool.crontab
Labels: cla-signed

#2423 Save proper node socket format into db
  backend/src/api/common.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: ⚡Lightning, cla-signed

#2439 Add loading animation for channel list
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
  frontend/src/app/lightning/node/node.component.ts
Labels: cla-signed

#2436 Align charts timestamp selector with charts menus
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.scss
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.scss
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.scss
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.scss
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.scss
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.scss
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.scss
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.scss
Labels: cla-signed

#2444 Fix infinite loading spinner in channel map when no active channel exists
  frontend/src/app/lightning/nodes-channels/node-channels.component.ts
Labels: cla-signed

#2446 Add mempool user to cln group and set data dirs rights on prod install
  production/install
Labels: ops, cla-signed

#2438 Add mempool lighting explorer to the prod installer
  production/install
  production/mempool-build-all
Labels: ops, cla-signed

#2449 Explore the full Bitcoin ecosystem with mempool.space
  frontend/src/index.bisq.html
  frontend/src/index.liquid.html
  frontend/src/index.mempool.html
  unfurler/src/index.ts
Labels: cla-signed

#2450 No nginx configuration for FreeBSD
  production/install
Labels: ops, cla-signed

#2445 When there is no stats for the past 7 days, don't show % changes
  backend/src/api/explorer/statistics.api.ts
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.html
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.scss
  frontend/src/app/lightning/node-statistics/node-statistics.component.html
  frontend/src/app/lightning/node-statistics/node-statistics.component.scss
Labels: cla-signed

#2425 Unfurler fallback images & bisq support
  frontend/src/resources/previews/dashboard.png
  frontend/src/resources/previews/lightning.png
  frontend/src/resources/previews/mining.png
  unfurler/package-lock.json
  unfurler/package.json
  unfurler/src/index.ts
  unfurler/src/routes.ts
Labels: cla-signed

#2453 Improve title for ISP map
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
Labels: cla-signed

#2441 Fix wrong ASN for Lunanode ip ranges
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
  backend/src/utils/ipcheck.js
  backend/tsconfig.json
  production/nginx-cache-warmer
Labels: cla-signed

#2443 Update channel map color
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2458 [ops] Add missing unfurl nginx route
  production/nginx/server-common.conf
Labels: ops

#2462 Fix: `Can't click on channel in the box view` #2459
  frontend/src/app/lightning/nodes-channels/node-channels.component.ts
Labels: cla-signed

#2403 Fix for difficulty adjustment throwing error before in sync
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/difficulty-adjustment.ts
Labels: cla-signed

#2433 Node and Channel page skeleton loaders
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channel/channel.component.scss
  frontend/src/app/lightning/channel/channel.component.ts
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.html
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
  frontend/src/app/lightning/node/node.component.ts
Labels: ⚡Lightning, cla-signed

#2468 CLN - Add brakets around ipv6
  backend/src/api/lightning/clightning/clightning-convert.ts
Labels: cla-signed

#2435 Replacing all PNGs with inline SVG
  frontend/src/app/components/bisq-master-page/bisq-master-page.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/clipboard/clipboard.component.html
  frontend/src/app/components/clipboard/clipboard.component.scss
  frontend/src/app/components/clipboard/clipboard.component.ts
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.html
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/svg-images/svg-images.component.html
  frontend/src/app/components/television/television.component.scss
  frontend/src/app/lightning/node/node.component.html
  frontend/src/resources/arrowdown.png
  frontend/src/resources/bisq-logo.png
  frontend/src/resources/bisq/bisq-markets-logo.png
  frontend/src/resources/bitcoin-logo.png
  frontend/src/resources/clippy.svg
  frontend/src/resources/divider-new.png
  frontend/src/resources/expand.png
  frontend/src/resources/liquid-logo.png
  frontend/src/resources/liquid/liquid-network-logo.png
  frontend/src/resources/liquidtestnet-logo.png
  frontend/src/resources/mempool-logo.png
  frontend/src/resources/mempool-space-logo.png
  frontend/src/resources/signet-logo.png
  frontend/src/resources/testnet-logo.png
  frontend/src/styles.scss
Labels: cla-signed

#2467 Fix unfurler navigation race condition
  unfurler/src/index.ts
Labels: cla-signed

#2466 Change unfurler puppeteer config toggle to ENABLED
  unfurler/config.sample.json
  unfurler/src/config.ts
  unfurler/src/index.ts
Labels: cla-signed

#2473 hotfix to rollback broken unfurler
  unfurler/src/index.ts
Labels: cla-signed

#2470 Consider channels updates as well for node updated at field
  backend/src/api/explorer/channels.api.ts
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#2448 Typeahead loading spinner and regex fixes
  frontend/src/app/components/search-form/search-form.component.html
  frontend/src/app/components/search-form/search-form.component.scss
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/components/search-form/search-results/search-results.component.ts
Labels: cla-signed
