Repository mempool/mempool, pull requests merged in 2022-12, with the labels that each got.

#2765 Run schema update synchronously
  backend/src/api/database-migration.ts
Labels: cla-signed

#2712 Mysql user creation fix in prod install
  production/install
Labels: ops, cla-signed

#2766 Update a few more frontend deps
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#2764 Update backend npm modules
  backend/package-lock.json
  backend/package.json
Labels: cla-signed

#2730 Don't select nodes which do not have country info
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2768 Block page audit fallback
  frontend/mempool-frontend-config.sample.json
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/shared/graphs.utils.ts
Labels: cla-signed

#2777 Make forensics node backend call rate limiting configurable
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/config.ts
  backend/src/tasks/lightning/forensics.service.ts
Labels: cla-signed

#2778 Fix bugs related to advanced GBT transaction selection
  backend/src/api/tx-selection-worker.ts
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#2779 Fix block summaries repo upsert race condition
  backend/src/api/websocket-handler.ts
  backend/src/repositories/BlocksSummariesRepository.ts
Labels: cla-signed

#2773 Update ignore rules and frequency of dependabot updates
  .github/dependabot.yml
Labels: cla-signed

#2825 Fix the dependabot ignore settings - RTFM
  .github/dependabot.yml
Labels: embarrassing, cla-signed

#2853 Update Cypress dependencies
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#2656 Update Cypress GHA to use newer checkout and setup-node actions
  .github/workflows/cypress.yml
Labels: cla-signed

#2793 Refactor advanced GBT implementation to minimize inter-thread data transfer
  backend/src/api/mempool-blocks.ts
  backend/src/api/mempool.ts
  backend/src/api/tx-selection-worker.ts
  backend/src/api/websocket-handler.ts
  backend/src/mempool.interfaces.ts
Labels: cla-signed

#2872 Fix for spelling error in indexing status
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: cla-signed

#2810 Fix & reenable cpfp indexer optimized path
  backend/src/api/blocks.ts
  backend/src/repositories/TransactionRepository.ts
Labels: cla-signed

#2771 Fix for javascript errors when navigating blocks
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#2769 Pull from transifex
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.lt.xlf
  frontend/src/locale/messages.ru.xlf
Labels: cla-signed

#2804 Handle zero-value flow diagram edge case
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.html
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#2809 fix unstable miner tag styles in block preview
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
Labels: cla-signed

#2859 display block health as badge & add loaders
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.ts
Labels: cla-signed

#2713 Add comandline options to cln on FreeBSD in prod install
  production/install
Labels: ops, cla-signed

#2714 Add symlink to bitcoin config for user cln in prod install
  production/install
Labels: ops, cla-signed

#2867 refactor block page html
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#2874 Updating VN translator
  frontend/README.md
Labels: cla-signed

#2875 Go to block optimization
  frontend/src/app/components/blocks-list/blocks-list.component.html
Labels: cla-signed

#2883 Don't try to import LN historical stats if no topology folder is set
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#2876 Adding Lithuanian
  frontend/angular.json
  frontend/src/app/app.constants.ts
  nginx.conf
  production/nginx/http-language.conf
Labels: cla-signed
