Repository mempool/mempool, pull requests merged in 2022-05, with the labels that each got.

#1579 Clean local block cache before loading dump
  backend/src/api/bisq/bisq.ts
Labels: cla-signed

#1580 Fix reward stats skeleton titles
  frontend/src/app/components/reward-stats/reward-stats.component.html
Labels: cla-signed

#1592 Show current network hashrate and difficulty using core RPC
  backend/src/routes.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
Labels: cla-signed

#1599 Revise main readme and docker install docs
  README.md
  docker/README.md
Labels: cla-signed

#1600 Add screenshot for 2.4.0 to readme
  README.md
  frontend/src/resources/screenshots/v2.4.0-dashboard.png
Labels: cla-signed

#1587 Fix datababse typo
  backend/src/api/database-migration.ts
Labels: cla-signed

#1568 Moving Docs and Faq to separate lazy loaded module
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/bisq/bisq.routing.module.ts
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs-nav.component.html
  frontend/src/app/docs/api-docs/api-docs-nav.component.scss
  frontend/src/app/docs/api-docs/api-docs-nav.component.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.scss
  frontend/src/app/docs/api-docs/api-docs.component.ts
  frontend/src/app/docs/code-template/code-template.component.html
  frontend/src/app/docs/code-template/code-template.component.scss
  frontend/src/app/docs/code-template/code-template.component.ts
  frontend/src/app/docs/docs.module.ts
  frontend/src/app/docs/docs.routing.module.ts
  frontend/src/app/docs/docs/docs.component.html
  frontend/src/app/docs/docs/docs.component.scss
  frontend/src/app/docs/docs/docs.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#1584 Upgrading npm packages and
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1565 Update pools table before fetching the first blocks
  backend/src/index.ts
Labels: cla-signed

#1610 Change faq docker link since docker docs moved
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#1609 Add back overwritten sentence to main readme
  README.md
Labels: cla-signed

#1590 Run hashrate indexing after midnight
  backend/src/api/mining.ts
  backend/src/index.ts
  backend/src/repositories/HashratesRepository.ts
Labels: cla-signed

#1598 fix lightning force close label with CSV delay <= 16
  frontend/src/app/components/address-labels/address-labels.component.ts
Labels: cla-signed

#1611 Refine production deployment doc
  production/README.md
Labels: cla-signed

#1618 Remove $ from commands in repo docs
  README.md
  docker/README.md
Labels: cla-signed

#1617 Add faq on address lookups
  frontend/src/app/components/address/address.component.html
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#1601 Add graph download feature
  frontend/src/app/app.module.ts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.scss
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.scss
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.scss
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.scss
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.scss
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
  frontend/src/app/components/incoming-transactions-graph/incoming-transactions-graph.component.html
  frontend/src/app/components/incoming-transactions-graph/incoming-transactions-graph.component.ts
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.scss
  frontend/src/app/components/statistics/statistics.component.ts
  frontend/src/app/shared/graphs.utils.ts
Labels: cla-signed

#1596 Create indexing progress sticky notification
  backend/src/api/blocks.ts
  backend/src/api/loading-indicators.ts
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
  frontend/src/app/components/indexing-progress/indexing-progress.component.html
  frontend/src/app/components/indexing-progress/indexing-progress.component.ts
  frontend/src/app/components/loading-indicator/loading-indicator.component.html
  frontend/src/app/components/loading-indicator/loading-indicator.component.scss
  frontend/src/app/components/loading-indicator/loading-indicator.component.ts
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool/pool.component.html
  frontend/src/app/components/pool/pool.component.ts
Labels: cla-signed

#1561 detect received lighting HTLC outputs
  frontend/src/app/components/address-labels/address-labels.component.html
  frontend/src/app/components/address-labels/address-labels.component.ts
Labels: cla-signed

#1597 Add block sizes vs weights graph
  backend/src/api/mining.ts
  backend/src/index.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/routes.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.html
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.scss
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#1630 Update issue templates
  .github/ISSUE_TEMPLATE/00-bug-issue.md
  .github/ISSUE_TEMPLATE/30-feature-request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#1628 [ops] Reduce electrs loop time from 5 seconds to 1 second
  production/install
  production/mempool-config.liquid.json
  production/mempool-config.liquidtestnet.json
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
Labels: ops, cla-signed

#1633 Fix the socks5 connection after updating the socks lib
  backend/src/api/fiat-conversion.ts
  backend/src/sync-assets.ts
Labels: cla-signed

#1636 Modify minfee node bitcoin.conf to connect to external peers
  production/bitcoin.minfee.conf
Labels: ops, cla-signed

#1640 Fix ELECTRUM_TLS_ENABLED Docker variable
  docker/README.md
  docker/backend/start.sh
Labels: cla-signed

#1644 Added some missing alt tags on some img
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool/pool.component.html
Labels: cla-signed

#1591 Skip missing blocks during block hash chain validation
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#1556 Update block API
  backend/src/api/blocks.ts
  backend/src/api/common.ts
  backend/src/index.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/routes.ts
  backend/src/utils/blocks-utils.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/miner/miner.component.html
  frontend/src/app/components/miner/miner.component.scss
  frontend/src/app/components/miner/miner.component.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/services/assets.service.ts
Labels: cla-signed

#1639 Add simple faq on full mempool
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#1662 Delete useless log
  backend/src/api/blocks.ts
Labels: cla-signed

#1663 Minor i18n corrections
  frontend/src/app/components/address-labels/address-labels.component.ts
  frontend/src/app/components/assets/asset-group/asset-group.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#1652 Always use BTC unit in blocks list
  frontend/src/app/components/blocks-list/blocks-list.component.html
Labels: cla-signed

#1653 Allow CTRL F an address on the transaction list component
  frontend/src/app/app.module.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.scss
  frontend/src/app/shared/pipes/cap-address-pipe/cap-address-pipe.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#1659 Cleanup mining API endpoints
  backend/src/index.ts
  backend/src/routes.ts
Labels: cla-signed

#1661 Define avg block time to 10 min until we have at least 146 block in the current epoch
  backend/src/api/difficulty-adjustment.ts
Labels: cla-signed

#1665 Fix for transaction inputs being fetched recursively
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
Labels: embarrassing, cla-signed

#1632 Reset outspends cache when switching to new tx page.
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#1637 Tweaking the websocket retry timers
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#1660 Production installation fixes
  production/install
  production/syslog.conf
Labels: cla-signed

#1664 Adding some missing i18n strings
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/locale/messages.xlf
Labels: cla-signed

#1669 [installer] Add base64 to list of OS package deps
  production/install
Labels: cla-signed

#1672 Upgrade Cypress to v9.6.1
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1670 Don't prepend apiBasePath for services backend resources
  frontend/src/app/services/api.service.ts
Labels: bug, cla-signed

#1673 Index blocks.hash
  backend/src/api/database-migration.ts
Labels: cla-signed

#1674 Cache /block API response for 10 min on user side
  backend/src/routes.ts
Labels: cla-signed

#1676 Additional expiration header for mining pool API endpoints
  backend/src/routes.ts
Labels: cla-signed

#1654 Add mining api docs
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/code-template/code-template.component.html
  frontend/src/app/docs/code-template/code-template.component.ts
Labels: cla-signed

#1682 Moving graphs and mining dashboard to a lazy loaded module
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/bisq/bisq.module.ts
  frontend/src/app/components/mining-start/mining-start.component.html
  frontend/src/app/components/mining-start/mining-start.component.ts
  frontend/src/app/graphs/graphs.module.ts
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#1680 Add feedback for mining API docs
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#1667 Improving loading indicator UX
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/block/block.component.html
  frontend/src/styles.scss
Labels: UI/UX, cla-signed

#1690 Fixes for Liquid module routing
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/graphs/graphs.routing.module.ts
Labels: cla-signed

#1677 Pull from transifex
  frontend/src/locale/messages.ar.xlf
  frontend/src/locale/messages.ca.xlf
  frontend/src/locale/messages.cs.xlf
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.en_US.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.he.xlf
  frontend/src/locale/messages.hi.xlf
  frontend/src/locale/messages.hr.xlf
  frontend/src/locale/messages.hu.xlf
  frontend/src/locale/messages.it.xlf
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.mk.xlf
  frontend/src/locale/messages.nb.xlf
  frontend/src/locale/messages.nl.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.pt.xlf
  frontend/src/locale/messages.ro.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.sl.xlf
  frontend/src/locale/messages.sv.xlf
  frontend/src/locale/messages.th.xlf
  frontend/src/locale/messages.tr.xlf
  frontend/src/locale/messages.uk.xlf
  frontend/src/locale/messages.vi.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#1694 Reward stats i18n fix
  frontend/src/app/components/reward-stats/reward-stats.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#1695 Round miners reward to full dollar
  frontend/src/app/components/reward-stats/reward-stats.component.html
Labels: cla-signed

#1697 Fix websockets tab
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#1643 Lazy load tx inputs in Bitcoin Core mode
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.interface.ts
  backend/src/api/transaction-utils.ts
  backend/src/routes.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.scss
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/interfaces/electrs.interface.ts
Labels: cla-signed

#1657 Add escaped slug into logs when slug does not match any pool
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/HashratesRepository.ts
  backend/src/repositories/PoolsRepository.ts
Labels: cla-signed

#1635 Make sure to re-index skipped block when backend is offline for too long
  backend/src/api/blocks.ts
  backend/src/api/mining.ts
  backend/src/index.ts
  backend/src/indexer.ts
Labels: cla-signed

#1708 Fix missing tx column in main dashboard on mobile
  frontend/src/app/dashboard/dashboard.component.scss
Labels: cla-signed

#1710 Add schildbach bitcoin wallet to about page
  frontend/src/app/components/about/about.component.html
  frontend/src/resources/profile/schildbach.svg
Labels: about, cla-signed

#1685 Update case in some mining API endpoint response
  backend/src/repositories/BlocksRepository.ts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#1696 Merge legacy and mining /blocks components and APIs
  backend/src/api/blocks.ts
  backend/src/index.ts
  backend/src/mempool.interfaces.ts
  backend/src/routes.ts
  backend/src/utils/blocks-utils.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.scss
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.component.html
  frontend/src/app/components/latest-blocks/latest-blocks.component.html
  frontend/src/app/components/latest-blocks/latest-blocks.component.scss
  frontend/src/app/components/latest-blocks/latest-blocks.component.ts
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/shared.module.ts
  production/nginx-cache-warmer
Labels: cla-signed

#1700 Block transactions list error handling
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
Labels: cla-signed

#1712 npm audit fix
  frontend/package-lock.json
Labels: cla-signed

#1701 Add role attributes for doc nav elements
  frontend/src/app/docs/code-template/code-template.component.html
  frontend/src/app/docs/docs/docs.component.html
Labels: cla-signed

#1687 Replace all oldestIndexedBlockTimestamp with X-total-count header
  backend/src/api/mining.ts
  backend/src/routes.ts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.components.ts
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#1727 i18n extract
  frontend/src/locale/messages.xlf
Labels: cla-signed

#1699 Liquid empty miner UX fix
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#1714 Move manual install notes to separate docs
  README.md
  backend/README.md
  docker/README.md
  frontend/README.md
Labels: documentation, cla-signed

#1717 NgBootstrap library import optimization
  frontend/src/app/bisq/bisq.module.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#1728 Add faq on empty blocks
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: documentation, cla-signed

#1718 Add loading spinner in /blocks page
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.scss
Labels: cla-signed

#1735 Remove keybase link from about page
  frontend/src/app/components/about/about.component.html
Labels: documentation, cla-signed

#1736 Adjust stuck tx faqs for angry people
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: documentation, cla-signed

#1733 Angular 13.3.10 update
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1716 Mining dashboard still runs fine if Bitcoin Core becomes unavailable
  backend/src/api/blocks.ts
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/routes.ts
Labels: cla-signed

#1719 Don't try to run pools parser if db is not enabled
  backend/src/index.ts
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#1730 Fix doc page titles
  frontend/src/app/docs/api-docs/api-docs.component.ts
  frontend/src/app/docs/docs/docs.component.ts
  frontend/src/locale/messages.xlf
Labels: documentation, cla-signed

#1739 Use block hash instead of block height in urls
  backend/src/repositories/BlocksRepository.ts
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/pool/pool.component.html
Labels: cla-signed

#1738 Add `economyFee` field in /api/fees/recommended API
  backend/src/api/fee-api.ts
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#1742 Upgrading packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#1750 Changed menu buttons to links
  frontend/src/app/components/bisq-master-page/bisq-master-page.component.html
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.html
  frontend/src/app/components/master-page/master-page.component.html
Labels: cla-signed

#1723 Save bisq aggregate exchange rates in the database for each new block
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/api/fiat-conversion.ts
  backend/src/repositories/RatesRepository.ts
Labels: cla-signed

#1764 Only attempt to save fx rate if database is enabled
  backend/src/api/blocks.ts
Labels: cla-signed

#1752 Use inline SVG for mempool.space logo
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/sponsor/sponsor.component.html
  frontend/src/app/components/sponsor/sponsor.component.scss
  frontend/src/app/components/svg-images/svg-images.component.html
  frontend/src/app/components/svg-images/svg-images.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement, cla-signed
