Repository mempool/mempool, pull requests merged in 2022-06, with the labels that each got.

#1769 Re-add hash field in the mysql block query
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#1766 Rewamp the fee widget
  frontend/src/app/components/difficulty/difficulty.component.scss
  frontend/src/app/components/fees-box/fees-box.component.html
  frontend/src/app/components/fees-box/fees-box.component.scss
  frontend/src/app/components/fees-box/fees-box.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.scss
Labels: cla-signed

#1779 Minor refactor for projected block transactions
  backend/src/api/mempool-blocks.ts
  backend/src/api/websocket-handler.ts
  frontend/src/app/components/mempool-block-overview/block-scene.ts
  frontend/src/app/components/mempool-block-overview/fast-vertex-array.ts
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.ts
  frontend/src/app/components/mempool-block-overview/sprite-types.ts
  frontend/src/app/components/mempool-block-overview/tx-sprite.ts
  frontend/src/app/components/mempool-block-overview/tx-view.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#1790 Updated new fee widget design
  frontend/src/app/components/fees-box/fees-box.component.html
  frontend/src/app/components/fees-box/fees-box.component.scss
  frontend/src/app/components/fees-box/fees-box.component.ts
Labels: cla-signed

#1784 Make node 16.15 required not recommended
  backend/README.md
  frontend/README.md
Labels: cla-signed

#1794 Extracting i18n strings
  frontend/src/locale/messages.xlf
Labels: cla-signed

#1797 Skip blocks disk cache loading after db migration
  backend/src/api/disk-cache.ts
Labels: cla-signed

#1792 Update dashboard screenshot for v2.4.0 release
  frontend/src/resources/screenshots/v2.4.0-dashboard.png
Labels: cla-signed

#1772 Refactor pool ranking rxjs observable
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#1800 Re-added missing cache version
  backend/src/api/disk-cache.ts
Labels: cla-signed

#1801 Improve disk cache logging
  backend/src/api/disk-cache.ts
Labels: cla-signed

#1809 Fix for mempool logo SVG issue
  frontend/src/app/components/svg-images/svg-images.component.html
  frontend/src/app/components/svg-images/svg-images.component.ts
Labels: cla-signed

#1808 Make sure blocks list rxjs observable triggers at least once
  frontend/src/app/components/blocks-list/blocks-list.component.ts
Labels: cla-signed

#1806 Cypress v10 upgrade
  .github/workflows/cypress.yml
  frontend/cypress.config.ts
  frontend/cypress.json
  frontend/cypress/e2e/bisq/bisq.spec.ts
  frontend/cypress/e2e/liquid/liquid.spec.ts
  frontend/cypress/e2e/liquidtestnet/liquidtestnet.spec.ts
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
  frontend/cypress/e2e/signet/signet.spec.ts
  frontend/cypress/e2e/testnet/testnet.spec.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1745 stricter multisig check + detect bare multisig when spent
  frontend/src/app/components/address-labels/address-labels.component.ts
Labels: cla-signed

#1810 Transifex pull
  frontend/src/locale/messages.ar.xlf
  frontend/src/locale/messages.ca.xlf
  frontend/src/locale/messages.cs.xlf
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.en_US.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.he.xlf
  frontend/src/locale/messages.hi.xlf
  frontend/src/locale/messages.hr.xlf
  frontend/src/locale/messages.hu.xlf
  frontend/src/locale/messages.it.xlf
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.mk.xlf
  frontend/src/locale/messages.nb.xlf
  frontend/src/locale/messages.nl.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.pt.xlf
  frontend/src/locale/messages.ro.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.sl.xlf
  frontend/src/locale/messages.sv.xlf
  frontend/src/locale/messages.th.xlf
  frontend/src/locale/messages.tr.xlf
  frontend/src/locale/messages.uk.xlf
  frontend/src/locale/messages.vi.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#1812 Use Foundry's dark theme logo on About page
  frontend/src/app/components/about/about.component.html
Labels: about, cla-signed

#1825 Add pull request template to discourage tx prs
  .github/pull_request_template.md
Labels: cla-signed

#1822 Add 'db-less' mining pool tagging support
  backend/src/api/blocks.ts
  backend/src/api/pools-parser.ts
  backend/src/database.ts
  backend/src/indexer.ts
  backend/src/tasks/pools-updater.ts
  frontend/src/app/components/blocks-list/blocks-list.component.html
Labels: cla-signed

#1827 Change 'projected blocks' to 'mempool blocks' in feerate tooltips
  frontend/src/app/components/fees-box/fees-box.component.html
Labels: cla-signed

#1829 Extracting i18n
  frontend/src/locale/messages.xlf
Labels: cla-signed

#1834 Fix pool import crash
  backend/src/api/pools-parser.ts
Labels: cla-signed

#1830 Change "projected block" to "mempool block" in feerate faq
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#1835 Pulled from Transifex
  frontend/src/locale/messages.ar.xlf
  frontend/src/locale/messages.ca.xlf
  frontend/src/locale/messages.cs.xlf
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.en_US.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.he.xlf
  frontend/src/locale/messages.hi.xlf
  frontend/src/locale/messages.hr.xlf
  frontend/src/locale/messages.hu.xlf
  frontend/src/locale/messages.it.xlf
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.mk.xlf
  frontend/src/locale/messages.nb.xlf
  frontend/src/locale/messages.nl.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.pt.xlf
  frontend/src/locale/messages.ro.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.sl.xlf
  frontend/src/locale/messages.sv.xlf
  frontend/src/locale/messages.th.xlf
  frontend/src/locale/messages.tr.xlf
  frontend/src/locale/messages.uk.xlf
  frontend/src/locale/messages.vi.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#1839 Add missing sed substitutions in docker/backend/start.sh
  docker/backend/start.sh
Labels: cla-signed

#1844 Fix one more broken sed substitution in docker/backend/start.sh
  docker/backend/start.sh
Labels: bug, cla-signed, docker

#1849 Pull from transifex
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.sl.xlf
  frontend/src/locale/messages.uk.xlf
  frontend/src/locale/messages.vi.xlf
Labels: cla-signed

#1852 Pull from transifex 202206091724
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.sl.xlf
  frontend/src/locale/messages.th.xlf
  frontend/src/locale/messages.uk.xlf
Labels: cla-signed

#1853 Pull from transifex 202206091948
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.ru.xlf
Labels: cla-signed

#1854 Pull from transifex 202206092024
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.sl.xlf
Labels: cla-signed

#1856 Pull from transifex 202206092208
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.he.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.nl.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.vi.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#1855 Use ellipsis + tooltip combo to fix layout on long string
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.scss
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/components/fees-box/fees-box.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/components/reward-stats/reward-stats.component.html
  frontend/src/app/components/reward-stats/reward-stats.component.scss
  frontend/src/app/components/reward-stats/reward-stats.component.ts
Labels: cla-signed

#1858 Release v2.4.0
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1841 Add note on rate limits to api docs
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.scss
  frontend/src/app/docs/api-docs/api-docs.component.ts
  frontend/src/app/docs/docs/docs.component.html
  frontend/src/app/docs/docs/docs.component.scss
Labels: documentation, cla-signed

#1860 Update npm install command and node.js requirements
  backend/README.md
  frontend/README.md
Labels: cla-signed

#1863 Replace "Indexing in progress" with localized "Indexing blocks"
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
  frontend/src/app/components/pool/pool.component.ts
Labels: cla-signed

#1869 Clarify that manual installs are meant for devs
  README.md
  backend/README.md
Labels: documentation, cla-signed

#1870 Fix anchor link scrolling on load (chrome)
  frontend/src/app/docs/api-docs/api-docs.component.ts
Labels: documentation, embarrassing, cla-signed

#1864 Make all mining charts tooltips uniform
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
  frontend/src/app/shared/graphs.utils.ts
Labels: cla-signed

#1866 Fix latest blocks rewards column not large enough to fit high reward
  frontend/src/app/components/blocks-list/blocks-list.component.scss
Labels: cla-signed

#1873 Fix canvas resolution on high-DPI screens
  frontend/src/app/components/mempool-block-overview/block-scene.ts
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.html
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.ts
Labels: cla-signed

#1874 Move FAQ HTML to angular templates
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.ts
  frontend/src/app/docs/docs.module.ts
  frontend/src/app/docs/faq-template/faq-template.component.ts
Labels: cla-signed

#1876 Cleanup some ops logs
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/api/mining.ts
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#1877 Listen for `stats` websocket event in the mining dashboard to get latest DA
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.ts
Labels: cla-signed

#1878 Added regtest notes to backend README
  backend/README.md
Labels: cla-signed

#1867 Only show `(1w)` on `Blocks` in pool ranking widget and add tooltips
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
Labels: cla-signed

#1890 Add k3tan video link to docker readme
  docker/README.md
Labels: cla-signed

#1889 Edit regtest docs formatting
  backend/README.md
Labels: cla-signed

#1884 Make `Latest blocks` and `Adjustments` widget title clickable
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.scss
Labels: cla-signed

#1883 Hide bottom axis label for mempool and incoming tx charts on widgets
  frontend/src/app/components/incoming-transactions-graph/incoming-transactions-graph.component.ts
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
Labels: cla-signed

#1881 Fix anchor links and typos in faq
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.ts
Labels: cla-signed

#1887 Add #{timespan} in mining charts urls for easier sharing
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.html
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#1892 Mined block visualization
  backend/src/api/bitcoin/bitcoin-api.interface.ts
  backend/src/api/blocks.ts
  backend/src/api/disk-cache.ts
  backend/src/index.ts
  backend/src/mempool.interfaces.ts
  backend/src/routes.ts
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.html
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.scss
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/block-scene.ts
  frontend/src/app/components/block-overview-graph/fast-vertex-array.ts
  frontend/src/app/components/block-overview-graph/sprite-types.ts
  frontend/src/app/components/block-overview-graph/tx-sprite.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.scss
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/mempool-block-overview/block-scene.ts
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.html
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.ts
  frontend/src/app/components/mempool-block/mempool-block.component.html
  frontend/src/app/components/mempool-block/mempool-block.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#1896 Index block summaries in db
  backend/mempool-config.sample.json
  backend/src/api/blocks.ts
  backend/src/api/common.ts
  backend/src/api/database-migration.ts
  backend/src/config.ts
  backend/src/indexer.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/BlocksSummariesRepository.ts
  backend/src/routes.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
  frontend/src/app/services/api.service.ts
  production/mempool-config.mainnet.json
  production/nginx/location-api.conf
Labels: cla-signed

#1893 Remove dashboard row collasping feature
  frontend/src/app/components/language-selector/language-selector.component.html
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.ts
Labels: cla-signed

#1907 Disable mined block animations
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.scss
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/block-scene.ts
  frontend/src/app/components/block/block.component.ts
Labels: cla-signed

#1905 Preload the previous block summary
  frontend/src/app/components/block/block.component.ts
Labels: cla-signed

#1908 Batch outspends requests
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/index.ts
  backend/src/routes.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#1895 Add moving average to the hashrate & difficulty chart
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
Labels: cla-signed

#1850 Compute our own price index and save into database every 1 hour
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/index.ts
  backend/src/repositories/PricesRepository.ts
  backend/src/repositories/RatesRepository.ts
  backend/src/tasks/pools-updater.ts
  backend/src/tasks/price-feeds/bitfinex-api.ts
  backend/src/tasks/price-feeds/bitflyer-api.ts
  backend/src/tasks/price-feeds/coinbase-api.ts
  backend/src/tasks/price-feeds/ftx-api.ts
  backend/src/tasks/price-feeds/gemini-api.ts
  backend/src/tasks/price-feeds/kraken-api.ts
  backend/src/tasks/price-feeds/mtgox-weekly.json
  backend/src/tasks/price-updater.ts
  backend/src/utils/axios-query.ts
Labels: cla-signed

#1917 [ops] Fix prod nginx perma-cache URL patterns
  production/nginx/location-api.conf
Labels: ops, cla-signed

#1918 [ops] Add mononaut's fork repo to list of trusted repos
  production/mempool-build-all
Labels: ops, cla-signed

#1920 Fix typo in docker docs
  docker/README.md
Labels: cla-signed

#1929 Minimum transaction fee is 0
  backend/src/api/common.ts
Labels: cla-signed

#1922 Fix block visualization color for txs with 0 < feerate < 1 sat/vb
  frontend/src/app/components/block-overview-graph/tx-view.ts
Labels: cla-signed

#1945 Fix js crash when loading faq - fix crash when switching tabs with an active fragment
  frontend/src/app/docs/api-docs/api-docs.component.ts
Labels: cla-signed
