Repository mempool/mempool, pull requests merged in 2022-07, with the labels that each got.

#1923 Skip tests when the ops label is used
  .github/workflows/cypress.yml
Labels: ops, cla-signed

#1955 [ops] Upgrade prod install to use Bitcoin v23
  production/install
Labels: ops, cla-signed

#1960 Enable zmq for bitcoind, fix ./configure opts
  production/bitcoin.conf
  production/install
Labels: ops, cla-signed

#1962 Skip tests if branch name starts with ops
  .github/workflows/cypress.yml
Labels: cla-signed

#1946 Various typing and build fixes to enable CI
  .github/workflows/ci.yml
  backend/package-lock.json
  backend/package.json
  backend/src/api/bitcoin/electrum-api.ts
  backend/src/api/disk-cache.ts
  backend/src/api/websocket-handler.ts
  backend/src/index.ts
  backend/tsconfig.json
  frontend/package.json
Labels: cla-signed

#1958 Fixed dialog error in production installer
  production/install
Labels: ops, cla-signed

#1963 Update python version for FreeBSD 13 in prod install
  production/install
Labels: ops, cla-signed

#1964 User creation for linux in the prod install script
  production/install
Labels: ops, cla-signed

#1965 Create directories for Linux in prod install
  production/install
Labels: ops, cla-signed

#1944 Add 'usually' to feerate tooltips
  frontend/src/app/components/fees-box/fees-box.component.html
Labels: cla-signed

#1942 Remove fade animation when switching docs tabs
  frontend/src/app/docs/docs/docs.component.html
Labels: cla-signed

#1948 Tell git to ignore .swp files
  .gitignore
Labels: cla-signed

#1885 Don't run the indexer unless Bitcoin Core is fully synced
  backend/src/api/blocks.ts
  backend/src/indexer.ts
Labels: cla-signed

#1901 Adding missing Block Tip Hash API
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/index.ts
  backend/src/routes.ts
Labels: cla-signed

#1968 Fix sed command for Linux systems in the prod install script
  production/install
Labels: ops, cla-signed

#1970 Fix Linux packages, usernames and path in prod install script
  production/install
Labels: ops, cla-signed

#1971 Install packages, Bitcoin and Liquid core services in prod install script
  production/linux/bitcoin-signet.service
  production/linux/bitcoin-testnet.service
  production/linux/bitcoin.service
  production/linux/liquid.service
Labels: ops, cla-signed

#1972 Ops/linux install java Bitcoin core and Liquid in prod install script
  production/install
Labels: ops, cla-signed

#1973 Only patch electrs for FreeBSD in prod install script
  production/install
Labels: ops, cla-signed

#1969 Add eslint to the backend and frontend
  .github/workflows/ci.yml
  backend/.eslintignore
  backend/.eslintrc
  backend/package-lock.json
  backend/package.json
  frontend/.eslintignore
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/bisq/bisq-transfers/bisq-transfers.component.ts
  frontend/src/app/docs/api-docs/api-docs-nav.component.ts
Labels: cla-signed

#1925 Index difficulty adjustments
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/api/mining.ts
  backend/src/index.ts
  backend/src/indexer.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/DifficultyAdjustmentsRepository.ts
  backend/src/routes.ts
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.component.html
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.components.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/services/api.service.ts
  production/nginx-cache-warmer
Labels: cla-signed

#1936 Handle electrs error 504
  frontend/src/app/components/address/address.component.html
Labels: cla-signed

#1934 Remove the condition to show `All` timespan on mining charts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
Labels: cla-signed

#1983 Refactor nginx.conf and other ops scripts for lightning
  production/mempool-build-all
  production/mempool-start-all
  production/nginx/http-basic.conf
  production/nginx/location-api-v1-lightning.conf
  production/nginx/location-api.conf
  production/nginx/location-liquid-api.conf
  production/nginx/location-liquidtestnet-api.conf
  production/nginx/location-signet-api-v1-lightning.conf
  production/nginx/location-signet-api.conf
  production/nginx/location-testnet-api-v1-lightning.conf
  production/nginx/location-testnet-api.conf
  production/nginx/nginx.conf
  production/nginx/server-bisq.conf
  production/nginx/server-esplora.conf
  production/nginx/server-mempool.conf
  production/nginx/upstream-esplora.conf
  production/nginx/upstream-mempool.conf
Labels: ops, cla-signed

#1977 Disable confirmation prompt for rust and change shebang in scripts to be universal for prod install
  production/electrs-start-liquid
  production/electrs-start-mainnet
  production/electrs-start-signet
  production/electrs-start-testnet
  production/install
  production/mempool-build-all
  production/mempool-start-all
  production/test-nginx
Labels: ops, cla-signed

#1979 Limit make to max cpus in prod install
  production/install
Labels: ops, cla-signed

#1931 fix various RTL layout issues
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/components/push-transaction/push-transaction.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/styles.scss
Labels: cla-signed

#1938 Upgrading npm packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1947 Add faq on vb, wu, and sat/vb
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#1940 Replace json `prices.avg_prices` with table columns - update prices logs
  backend/src/api/database-migration.ts
  backend/src/repositories/PricesRepository.ts
  backend/src/tasks/price-feeds/kraken-api.ts
  backend/src/tasks/price-updater.ts
  backend/src/utils/axios-query.ts
Labels: cla-signed

#1993 Remove frontend dependencies and old tests
  frontend/angular.json
  frontend/karma.conf.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/address-labels/address-labels.component.spec.ts
  frontend/src/app/components/amount/amount.component.spec.ts
  frontend/src/app/components/app/app.component.spec.ts
  frontend/src/app/components/clipboard/clipboard.component.spec.ts
  frontend/src/app/components/mempool-block/mempool-block.component.spec.ts
  frontend/src/app/components/qrcode/qrcode.component.spec.ts
  frontend/src/app/components/search-form/search-form.component.spec.ts
  frontend/src/app/components/start/start.component.spec.ts
  frontend/src/app/fiat/fiat.component.spec.ts
  frontend/src/app/shared/pipes/absolute/absolute.pipe.spec.ts
  frontend/src/app/shared/pipes/asm-styler/asm-styler.pipe.spec.ts
  frontend/src/app/shared/pipes/fee-rounding/fee-rounding.pipe.spec.ts
  frontend/src/app/shared/pipes/hex2ascii/hex2ascii.pipe.spec.ts
  frontend/src/app/shared/pipes/relative-url/relative-url.pipe.spec.ts
  frontend/src/test.ts
  frontend/tslint.json
Labels: cla-signed

#1952 set error correction level to low for qr codes
  frontend/src/app/components/qrcode/qrcode.component.ts
Labels: cla-signed

#1991 Fix electrum API encoding
  backend/package-lock.json
  backend/package.json
  backend/src/api/bitcoin/electrum-api.ts
Labels: bug, cla-signed

#1994 Update Cypress related dependencies
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#1996 Remove TSLint from the backend
  backend/package-lock.json
  backend/package.json
  backend/tslint.json
Labels: cla-signed

#1997 Update CI to trigger on PRs and exclude from ops activities
  .github/workflows/ci.yml
Labels: cla-signed

#2005 Extracting i18n strings
  frontend/src/locale/messages.xlf
Labels: cla-signed

#2001 Fix startup scripts in prod install
  production/linux/bitcoin-signet.service
  production/linux/bitcoin-testnet.service
  production/linux/elements-testnet.service
  production/linux/elements.service
Labels: ops, cla-signed

#2006 Merging the 3 "block predictions" i18n string into 1
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.html
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.scss
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.ts
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/graphs/graphs.module.ts
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/locale/messages.xlf
Labels: cla-signed

#2009 Auto resize graphs on window resize
  frontend/src/app/bisq/lightweight-charts-area/lightweight-charts-area.component.ts
  frontend/src/app/bisq/lightweight-charts/lightweight-charts.component.ts
Labels: network:Bisq, cla-signed

#2004 Set pagination font to monospace
  frontend/src/styles.scss
Labels: cla-signed

#2003 Add `--prod` to `npm install` in ops scripts
  production/mempool-build-all
Labels: ops, cla-signed

#1998 Make user crontab reliable in prod install script
  production/install
Labels: ops, cla-signed

#2013 Set ulimit highter for all users in prod install
  production/install
Labels: ops, cla-signed

#2011 Fix npm install commands in Dockerfiles and ops scripts
  .github/workflows/ci.yml
  docker/backend/Dockerfile
  docker/frontend/Dockerfile
  production/mempool-build-all
Labels: cla-signed

#2020 [Hashrate indexing] - Signet started in 2020 and not in 2009
  backend/src/api/mining.ts
Labels: cla-signed

#2031 Quote echo output in prod install
  production/install
Labels: ops, cla-signed

#2032 Fix service name to elements and add elements testnet for prod install
  production/install
  production/linux/elements-liquid.service
  production/linux/elements-liquidtestnet.service
Labels: ops, cla-signed

#2030 Angular 14 Upgrade
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/docs/docs.routing.module.ts
  frontend/src/app/graphs/graphs.routing.module.ts
Labels: cla-signed

#2035 Add mempool build as final step on prod install
  production/install
Labels: ops, cla-signed

#2039 Use bitcoin core to fetch blocks
  backend/src/api/blocks.ts
  backend/src/utils/blocks-utils.ts
Labels: cla-signed

#2040 Remove the dialog for now on prod install
  production/install
Labels: ops, cla-signed

#2042 Revert: Angular 14 upgrade
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/docs/docs.routing.module.ts
  frontend/src/app/graphs/graphs.routing.module.ts
Labels: cla-signed

#2036 Renaming value -> amount
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#2045 Update to Node.js v16.16.0, use shared zlib for prod
  .nvmrc
  docker/backend/Dockerfile
  docker/frontend/Dockerfile
  production/README.md
  production/install
Labels: cla-signed

#2046 Fix missing dependencies
  frontend/package-lock.json
Labels: cla-signed

#2002 Automatic block re-indexing upon pools.json update
  backend/src/api/pools-parser.ts
Labels: cla-signed

#2041 Install nginx config also for freebsd on prod install
  production/install
Labels: ops, cla-signed

#1999 Run the mining indexer every hour to index missing/updated data
  backend/src/indexer.ts
Labels: cla-signed

#2033 Fix hashrate indexing, log difficulty adjustment progress
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/HashratesRepository.ts
Labels: cla-signed

#2056 Disable automatic block re-indexing by default
  backend/mempool-config.sample.json
  backend/src/api/pools-parser.ts
  backend/src/config.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#2054 Ignore prices without USD exchange rate
  backend/src/repositories/PricesRepository.ts
Labels: cla-signed

#2051 Fix diff adj table using raw db value
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/DifficultyAdjustmentsRepository.ts
  backend/src/routes.ts
Labels: cla-signed

#2052 Fix pagination issue in blocks list
  backend/src/api/blocks.ts
  backend/src/routes.ts
Labels: cla-signed

#2057 Pull from transifex
  frontend/src/locale/messages.ar.xlf
  frontend/src/locale/messages.ca.xlf
  frontend/src/locale/messages.cs.xlf
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.en_US.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.he.xlf
  frontend/src/locale/messages.hi.xlf
  frontend/src/locale/messages.hr.xlf
  frontend/src/locale/messages.hu.xlf
  frontend/src/locale/messages.it.xlf
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.mk.xlf
  frontend/src/locale/messages.nl.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.pt.xlf
  frontend/src/locale/messages.ro.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.sl.xlf
  frontend/src/locale/messages.sv.xlf
  frontend/src/locale/messages.th.xlf
  frontend/src/locale/messages.tr.xlf
  frontend/src/locale/messages.uk.xlf
  frontend/src/locale/messages.vi.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#2059 Don't round signet difficulty in table and chart
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.components.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
Labels: cla-signed

#1978 Add nodes per network chart component
  backend/src/api/database-migration.ts
  backend/src/api/explorer/statistics.api.ts
  backend/src/tasks/lightning/stats-updater.service.ts
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.scss
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.html
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: ⚡Lightning, cla-signed

#1980 Index LN channels stats and show them in dashboard widget
  backend/src/api/database-migration.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/statistics.api.ts
  backend/src/tasks/lightning/stats-updater.service.ts
  frontend/src/app/components/change/change.component.ts
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.html
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.scss
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.ts
  frontend/src/app/lightning/lightning-api.service.ts
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/node-statistics/node-statistics.component.html
Labels: ⚡Lightning, cla-signed

#1981 Add LN charts into `/graphs` and add timespan selection
  backend/src/api/explorer/general.routes.ts
  backend/src/api/explorer/statistics.api.ts
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/lightning/lightning-api.service.ts
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.html
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: ⚡Lightning, cla-signed

#2065 Liquid always uses esplora (regression of #2039)
  backend/src/api/blocks.ts
  backend/src/api/common.ts
Labels: cla-signed

#2066 Fix graphs button layout
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/components/graphs/graphs.component.ts
Labels: cla-signed

#2067 Set /block API cache duration according to block age
  backend/src/routes.ts
Labels: cla-signed

#2069 [Indexer] Set log level accordingly - Remove indexing ETAs
  backend/src/api/blocks.ts
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#2076 Refactoring backend routes code
  backend/src/api/bisq/bisq.routes.ts
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/blocks.ts
  backend/src/api/liquid/liquid.routes.ts
  backend/src/api/mining/mining-routes.ts
  backend/src/api/mining/mining.ts
  backend/src/api/statistics/statistics-api.ts
  backend/src/api/statistics/statistics.routes.ts
  backend/src/api/statistics/statistics.ts
  backend/src/index.ts
  backend/src/indexer.ts
  backend/src/routes.ts
Labels: cla-signed

#2077 CONTRIBUTING.md: Ask contributors to sign their commits
  CONTRIBUTING.md
Labels: cla-signed

#2088 [LN] Add `as_organization` in nodes table
  backend/src/api/database-migration.ts
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
Labels: cla-signed

#2095 Show maxming data when available is nodes page
  backend/src/api/explorer/nodes.api.ts
  frontend/src/app/lightning/node/node.component.html
Labels: ⚡Lightning, cla-signed

#1817 Add USD serie in block fee/reward charts
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/api/mining/mining.ts
  backend/src/index.ts
  backend/src/indexer.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/PricesRepository.ts
  backend/src/tasks/price-feeds/bitfinex-api.ts
  backend/src/tasks/price-feeds/bitflyer-api.ts
  backend/src/tasks/price-feeds/coinbase-api.ts
  backend/src/tasks/price-feeds/ftx-api.ts
  backend/src/tasks/price-feeds/gemini-api.ts
  backend/src/tasks/price-feeds/kraken-api.ts
  backend/src/tasks/price-updater.ts
  backend/src/utils/blocks-utils.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/shared/pipes/fiat-shortener.pipe.ts
Labels: cla-signed

#2099 Re-add missing migration that was dropped during merge conflict
  backend/src/api/database-migration.ts
Labels: cla-signed

#2093 Fix LN dashboard layout during indexing
  frontend/src/app/lightning/node-statistics/node-statistics.component.html
Labels: ⚡Lightning, cla-signed

#2094 Make sure we have initial channel stats to display after fresh run
  backend/src/tasks/lightning/stats-updater.service.ts
Labels: ⚡Lightning, cla-signed

#2068 Block audit page
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/api/mining/mining-routes.ts
  backend/src/api/websocket-handler.ts
  backend/src/repositories/BlocksAuditsRepository.ts
  backend/src/repositories/BlocksSummariesRepository.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/block-audit/block-audit.component.html
  frontend/src/app/components/block-audit/block-audit.component.scss
  frontend/src/app/components/block-audit/block-audit.component.ts
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/interfaces/websocket.interface.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/graphs.utils.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2114 Fix graph titles layout and text
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.html
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.html
Labels: cla-signed

#2098 Add nodes per country table page
  backend/src/api/database-migration.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/lightning.routing.module.ts
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.html
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.scss
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/components/timestamp/timestamp.component.html
  frontend/src/app/shared/components/timestamp/timestamp.component.ts
Labels: ⚡Lightning, cla-signed

#2121 Nodes list per ISP
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/lightning.routing.module.ts
  frontend/src/app/lightning/nodes-per-as-chart/nodes-per-as-chart.component.html
  frontend/src/app/lightning/nodes-per-as-chart/nodes-per-as-chart.component.ts
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.html
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.scss
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2120 Fix naming convention "as" => "isp"
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2118 LN nodes per country pie chart
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.html
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.scss
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.ts
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.html
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.scss
  frontend/src/app/lightning/nodes-per-country/nodes-per-country.component.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/graphs.utils.ts
Labels: cla-signed

#2113 Move TV button to `/graphs/mempool` graph page
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.ts
Labels: cla-signed

#2123 Fix error 500 for `Isle of Man` nodes list
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#2085 [Hashrate chart] Fix javascript error if difficulty array is empty
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
Labels: cla-signed

#2112 Ignore Kraken historical price without USD
  backend/src/tasks/price-feeds/kraken-api.ts
Labels: cla-signed

#2117 Fix nodes per network chart localization
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
Labels: cla-signed

#2119 Fix node per as table css
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
Labels: cla-signed

#2110 Fix block prediction chart when there is few or no data available
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.ts
Labels: cla-signed

#2131 Reduce nginx cache time for production homepage
  production/nginx/server-common.conf
Labels: ops, cla-signed

#2136 [Indexer] Set log level accordingly - Remove indexing ETAs
  backend/src/api/blocks.ts
  backend/src/api/mining.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#2139 Create lightning nodes world heat map (clearnet)
  frontend/proxy.conf.js
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/nodes-map/nodes-map.component.html
  frontend/src/app/lightning/nodes-map/nodes-map.component.scss
  frontend/src/app/lightning/nodes-map/nodes-map.component.ts
  frontend/src/app/lightning/nodes-per-isp/nodes-per-isp.component.ts
  frontend/src/app/services/assets.service.ts
  frontend/src/resources/worldmap.json
Labels: cla-signed

#2145 Route new APIs to services backend
  production/nginx/location-api-v1-services.conf
Labels: ops, cla-signed

#2146 Subdomain enterprise logo
  frontend/src/app/app.module.ts
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
  frontend/src/app/components/master-page/master-page.component.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/services/enterprise.service.ts
  frontend/src/app/services/seo.service.ts
  frontend/src/index.bisq.html
  frontend/src/index.liquid.html
  frontend/src/index.mempool.html
Labels: cla-signed

#2147 Create world map of clearnet LN nodes and channels
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/channels.routes.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
  frontend/src/app/lightning/nodes-map/nodes-map.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2140 Remove gitignore json wildcard
  backend/.gitignore
Labels: cla-signed

#2138 Fix block predition graph x axis labels
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.ts
Labels: cla-signed

#2109 Block audit code refactor
  backend/src/api/blocks.ts
  backend/src/api/websocket-handler.ts
  backend/src/repositories/BlocksSummariesRepository.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
Labels: cla-signed

#2141 Always show taproot button
  frontend/src/app/components/tx-features/tx-features.component.html
Labels: cla-signed

#2148 Enterprise logo container
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
Labels: cla-signed

#2151 Navbar logos fix
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
Labels: cla-signed

#2149 Fix Cypress TV tests
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
  frontend/cypress/e2e/signet/signet.spec.ts
  frontend/cypress/e2e/testnet/testnet.spec.ts
  frontend/src/app/components/statistics/statistics.component.html
Labels: cla-signed

#2150 Refactor Cypress GHA
  .github/workflows/cypress.yml
Labels: cla-signed

#2152 Draft: Open Graph link previews
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
  frontend/src/app/components/block/block-preview.component.ts
  frontend/src/app/components/master-page-preview/master-page-preview.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.scss
  frontend/src/app/components/master-page-preview/master-page-preview.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2154 Fix wrong i18n key
  frontend/src/app/components/graphs/graphs.component.html
Labels: cla-signed

#2153 Fix block predition graph x axis labels
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.ts
Labels: cla-signed

#2158 Show LN map on the LN dashboard
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2155 Make flags clickable
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.html
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.scss
Labels: cla-signed

#2157 Add channels map to the node page
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/channels.routes.ts
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2166 Integrate GeoIP2 ISP database
  backend/mempool-config.sample.json
  backend/src/api/explorer/nodes.api.ts
  backend/src/config.ts
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
Labels: cla-signed

#2168 [Node page] Update channels count when switching between open/closed
  backend/src/api/explorer/nodes.api.ts
  frontend/src/app/lightning/channels-list/channels-list.component.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
Labels: cla-signed

#2169 [Node page] Handle empty channels list
  frontend/src/app/lightning/channels-list/channels-list.component.html
Labels: cla-signed

#2170 [Node page] Handle non existing node
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
Labels: cla-signed

#2171 Remove duplicated nodes from the world map
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2167 Add Taproot transaction feature tooltip with fee saving information
  frontend/src/app/bitcoin.utils.ts
  frontend/src/app/components/address-labels/address-labels.component.ts
  frontend/src/app/components/tx-features/tx-features.component.html
  frontend/src/app/components/tx-features/tx-features.component.ts
Labels: cla-signed

#2172 Fix for mempool logo jumping with various sizes of enterprise logo
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
Labels: cla-signed

#2188 Address @Xekyo's comments on #2167
  frontend/src/app/bitcoin.utils.ts
  frontend/src/app/components/tx-features/tx-features.component.html
  frontend/src/app/components/tx-features/tx-features.component.ts
Labels: cla-signed

#2185 [Node page] Add link to node list per country/isp in node page
  backend/src/api/explorer/nodes.api.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/shared/graphs.utils.ts
Labels: ⚡Lightning, cla-signed

#2186 [Node page] Remove node chart 1mb line and fix y axis
  frontend/src/app/lightning/node-statistics-chart/node-statistics-chart.component.ts
Labels: ⚡Lightning, cla-signed

#2187 [LN Dashboard] - Show 3y charts instead of 1y
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: ⚡Lightning, cla-signed

#2194 Fix zmq ports in prod bitcoin.conf
  production/bitcoin.conf
Labels: ops, cla-signed

#2193 Add random generated mysql passwords on prod install
  production/install
  production/mempool-build-all
  production/mempool-config.bisq.json
  production/mempool-config.liquid.json
  production/mempool-config.liquidtestnet.json
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
Labels: ops, cla-signed

#2190 [LN stats] Order lightning_stats by added timestamp instead of id
  backend/src/api/explorer/statistics.api.ts
Labels: ⚡Lightning, cla-signed

#2192 Fix for mempool logo not being centered vertically
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
Labels: cla-signed

#2183 A couple of new eslint rules
  backend/.eslintrc
  frontend/.eslintrc
Labels: cla-signed

#2200 Create shared toggle component to re-use
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
  frontend/src/app/lightning/node/node.component.ts
  frontend/src/app/shared/components/toggle/toggle.component.html
  frontend/src/app/shared/components/toggle/toggle.component.scss
  frontend/src/app/shared/components/toggle/toggle.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2201 Add capacity/nodes, include/exclude Tor from ISP chart
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/explorer/nodes.routes.ts
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/components/toggle/toggle.component.html
  frontend/src/app/shared/components/toggle/toggle.component.ts
Labels: ⚡Lightning, cla-signed

#2202 Ony consider channel stats = 1 for stats calculation
  backend/src/api/explorer/nodes.api.ts
  backend/src/tasks/lightning/stats-updater.service.ts
Labels: ⚡Lightning, cla-signed

#2203 Don't set all channels to inactive when the updater runs
  backend/src/tasks/lightning/node-sync.service.ts
Labels: ⚡Lightning, cla-signed

#2204 Silence LN db migration is CONFIG.LIGHTNING.ENABLED = false
  backend/src/api/database-migration.ts
Labels: cla-signed

#2173 Open Graph link unfurler service
  unfurler/.editorconfig
  unfurler/.eslintignore
  unfurler/.eslintrc
  unfurler/.gitignore
  unfurler/.prettierignore
  unfurler/.prettierrc
  unfurler/README.md
  unfurler/config.sample.json
  unfurler/package-lock.json
  unfurler/package.json
  unfurler/puppeteer.config.json
  unfurler/src/config.ts
  unfurler/src/index.ts
  unfurler/tsconfig.json
Labels: cla-signed

#2205 Better block unfurls
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/app/app.component.ts
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
  frontend/src/app/components/master-page-preview/master-page-preview.component.scss
  frontend/src/app/services/opengraph.service.ts
  frontend/src/app/services/seo.service.ts
  unfurler/src/index.ts
Labels: cla-signed

#2206 Address unfurls
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/address/address-preview.component.html
  frontend/src/app/components/address/address-preview.component.scss
  frontend/src/app/components/address/address-preview.component.ts
  frontend/src/app/components/block/block-preview.component.scss
  frontend/src/app/services/opengraph.service.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles.scss
  unfurler/src/index.ts
Labels: cla-signed

#2207 Reduce mobile menus padding
  frontend/src/app/components/master-page/master-page.component.scss
Labels: cla-signed

#2208 Update mouse UX on LN map in dashboard
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#2209 Remove useless view more links that does not link to anywhere
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
Labels: cla-signed

#2212 Convert nodes per network chart to stack style
  backend/src/api/explorer/statistics.api.ts
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
Labels: cla-signed

#2217 Add options for components to be installed in prod install script
  production/install
Labels: ops, cla-signed

#2220 Add Unfurl to the prod installer
  production/install
  production/mempool-config.unfurl.json
  production/unfurl-build
  production/unfurl-kill
  production/unfurl-start
Labels: ops, cla-signed

#2222 Fix tor config for FreeBSD on prod installer
  production/install
  production/torrc
Labels: ops, cla-signed

#2224 Redirect with path
  frontend/src/app/services/enterprise.service.ts
Labels: cla-signed
