Repository mempool/mempool, pull requests merged in 2023-02, with the labels that each got.

#3001 Add block health faq
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.scss
Labels: cla-signed

#2993 Credit nepalese translator
  frontend/README.md
Labels: cla-signed

#2999 fix block visualization getting out of sync
  backend/src/api/mempool-blocks.ts
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#3010 More robust error checking & handling in CPFP repositories
  backend/src/repositories/CpfpRepository.ts
  backend/src/repositories/TransactionRepository.ts
Labels: cla-signed

#3030 safer mempool cloning for different GBT algorithms
  backend/src/api/websocket-handler.ts
  backend/src/utils/clone.ts
Labels: cla-signed

#3038 Fix firefox blockchain scroll reset bug
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#3045 Add block audit faq
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs-nav.component.html
  frontend/src/app/docs/api-docs/api-docs-nav.component.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.scss
Labels: documentation, cla-signed

#3047 Change 'projected' to 'expected' for block audit label
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#3049 Update staging hosts to fra
  frontend/proxy.conf.staging.js
Labels: cla-signed

#3053 Add info icon on audit linking to audit faq
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
Labels: cla-signed

#3054 Extracting i18n
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3055 Updating a few i18n strings
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/start/start.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3039 Add audit / block health config feature flag
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/blocks.ts
  backend/src/api/websocket-handler.ts
  backend/src/config.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
  docker/frontend/entrypoint.sh
  frontend/mempool-frontend-config.sample.json
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs-nav.component.html
  frontend/src/app/docs/api-docs/api-docs-nav.component.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.ts
  frontend/src/app/services/state.service.ts
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
  production/mempool-frontend-config.mainnet.json
Labels: cla-signed

#3058 Remove colon from block overview table
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#3062 Fix database usage when database is disabled
  backend/src/api/blocks.ts
  backend/src/api/fiat-conversion.ts
  backend/src/api/pools-parser.ts
  backend/src/api/websocket-handler.ts
  backend/src/index.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/PricesRepository.ts
  backend/src/tasks/price-updater.ts
  frontend/src/app/app.constants.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/amount/amount.component.html
  frontend/src/app/components/amount/amount.component.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/fiat-selector/fiat-selector.component.html
  frontend/src/app/components/fiat-selector/fiat-selector.component.scss
  frontend/src/app/components/fiat-selector/fiat-selector.component.ts
  frontend/src/app/components/language-selector/language-selector.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.scss
  frontend/src/app/components/pool/pool.component.html
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/fiat/fiat.component.html
  frontend/src/app/fiat/fiat.component.ts
  frontend/src/app/lightning/channel/channel-box/channel-box.component.html
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.scss
  frontend/src/app/lightning/node-statistics/node-statistics.component.html
  frontend/src/app/services/state.service.ts
  frontend/src/app/shared/pipes/fiat-currency.pipe.ts
  frontend/src/app/shared/pipes/fiat-shortener.pipe.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#3073 Migrated transifex and fetched latest translations
  frontend/.tx/config
  frontend/src/locale/messages.ar.xlf
  frontend/src/locale/messages.cs.xlf
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.lt.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.sv.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#3075 ops: Fix mempool build script lightning variables
  production/mempool-build-all
Labels: ops, cla-signed

#3043 Fixes blocks api (missing fee range)
  backend/src/api/blocks.ts
  backend/src/utils/blocks-utils.ts
Labels: cla-signed

#2770 Make sure exchange API response format is valid before using it
  backend/src/tasks/price-feeds/bitfinex-api.ts
  backend/src/tasks/price-feeds/bitflyer-api.ts
  backend/src/tasks/price-feeds/coinbase-api.ts
  backend/src/tasks/price-feeds/gemini-api.ts
  backend/src/tasks/price-feeds/kraken-api.ts
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#3063 fix liquid address table overflow
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/address/address.component.scss
Labels: cla-signed

#3009 Update cpfp faq for stored relationships
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#3022 Reuse HTTP connections for esplora backend requests
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/index.ts
Labels: cla-signed

#3066 Add size per weight graph and ts type for `getHistoricalBlockSizesAndWeights`
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#3041 Add `--reindex` doc to backend README
  backend/README.md
Labels: cla-signed

#3064 Remove `config.MEMPOOL.PRICE_FEED_UPDATE_INTERVAL`
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/config.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#3078 Remove hardcoded mining pools colors as it's not relevant
  frontend/src/app/app.constants.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#3048 Update mainnet tests
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
Labels: cla-signed

#3079 Only add clearfix on block list widget
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
Labels: cla-signed

#3080 Fix database usage when database is disabled
  backend/src/api/blocks.ts
Labels: cla-signed

#3089 ops: Fix another typo in build script credentials sed
  production/mempool-build-all
Labels: ops, cla-signed

#3090 ops: Fix typo in mainnet lightning backend config
  production/mempool-config.mainnet-lightning.json
Labels: ops, cla-signed

#3081 Remove included in block
  frontend/src/app/components/transaction/transaction.component.html
Labels: cla-signed

#3091 Show average block health in pool ranking
  backend/src/api/mining/mining.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/PoolsRepository.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#3096 Fix liquid infinite scrolling
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
Labels: cla-signed

#3097 ops: Add 250ms delay between warm cache requests
  production/nginx-cache-warmer
Labels: ops, cla-signed

#3098 Use mempool chart color palette on hashrate history
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
Labels: cla-signed

#3092 Use historical price in older blocks / transactions
  backend/src/api/mining/mining-routes.ts
  backend/src/repositories/PricesRepository.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/amount/amount.component.html
  frontend/src/app/components/amount/amount.component.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/fiat/fiat.component.html
  frontend/src/app/fiat/fiat.component.ts
  frontend/src/app/interfaces/electrs.interface.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/services/price.service.ts
Labels: cla-signed

#3099 Fix timespan UX in mining charts
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.html
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.scss
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.html
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.scss
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.html
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.scss
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.html
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.scss
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.html
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.scss
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.html
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.scss
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.html
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#3076 Fix map not being updated when switching between channel pages
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#3110 Fix 'NaN' price for unconfirmed transaction since we have no block timestamp
  frontend/src/app/services/price.service.ts
Labels: cla-signed

#3106 Unknown pool color #FDD835
  frontend/src/app/app.constants.ts
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#3103 increase size of mempool_byte_weight db column
  backend/src/api/database-migration.ts
Labels: cla-signed

#3100 Fixes a syntax error with certain keywords
  backend/src/api/explorer/nodes.api.ts
Labels: cla-signed

#3068 Raise production memory limits
  backend/package.json
  production/bitcoin.conf
Labels: cla-signed

#3101 pixel perfect flow diagrams
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#3113 Show only USD in block fees/rewards charts
  backend/src/repositories/BlocksRepository.ts
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.ts
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.ts
Labels: cla-signed

#3007 Fix blockchain scroll jumping on resize on mobile
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#3115 Fix lightning widgets layout
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
Labels: cla-signed

#3111 Redo/Fix completely failed PR #3092 + add PR #3105
  backend/src/api/database-migration.ts
  backend/src/api/mining/mining-routes.ts
  backend/src/repositories/PricesRepository.ts
  backend/src/tasks/price-updater.ts
  frontend/src/app/components/amount/amount.component.html
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.html
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.html
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
  frontend/src/app/fiat/fiat.component.html
  frontend/src/app/services/api.service.ts
  frontend/src/app/services/price.service.ts
Labels: cla-signed

#3117 Fit translator avatars neatly on 2 lines
  frontend/src/app/components/about/about.component.scss
Labels: cla-signed

#3084 Update node v16, LTS and current for CI
  .github/workflows/ci.yml
Labels: cla-signed

#3118 Fix DB migration 54 breaking liquid
  backend/src/api/database-migration.ts
Labels: cla-signed

#3109 Add border to qr code because it's a best practice
  frontend/src/app/components/qrcode/qrcode.component.html
  frontend/src/app/components/qrcode/qrcode.component.ts
Labels: cla-signed

#3119 Only query historical price if we're running mempool BASE_MODULE
  frontend/src/app/services/price.service.ts
Labels: cla-signed

#3025 Handling for network interruptions in scrollable blockchain
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.scss
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/components/start/start.component.ts
  frontend/src/app/services/cache.service.ts
Labels: cla-signed

#3126 ops: Enable CPFP indexing for mainnet
  production/mempool-config.mainnet.json
Labels: cla-signed

#3070 Index coinstatsindex - Add bulk block query api
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/bitcoin/esplora-api.interface.ts
  backend/src/api/blocks.ts
  backend/src/api/chain-tips.ts
  backend/src/api/database-migration.ts
  backend/src/api/disk-cache.ts
  backend/src/api/mining/mining.ts
  backend/src/api/transaction-utils.ts
  backend/src/config.ts
  backend/src/database.ts
  backend/src/index.ts
  backend/src/indexer.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/BlocksSummariesRepository.ts
  backend/src/rpc-api/commands.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
  production/bitcoin.conf
Labels: cla-signed

#2869 Rewrite mining pools parser
  backend/src/__tests__/config.test.ts
  backend/src/api/database-migration.ts
  backend/src/api/pools-parser.ts
  backend/src/config.ts
  backend/src/repositories/PoolsRepository.ts
  backend/src/tasks/pools-updater.ts
Labels: enhancement, cla-signed

#3132 Update legal notices for 2023
  LICENSE
  frontend/src/app/components/about/about.component.html
Labels: cla-signed

#3133 Localizing search box strings
  frontend/src/app/components/search-form/search-results/search-results.component.html
  frontend/src/app/lightning/channel/closing-type/closing-type.component.ts
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3134 Add i18n tag for big faq disclaimer
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#3137 Extracting i18n with new faq disclaimer
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3138 Fix for duplicate i18n strings
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3143 Fixing some i18n strings.
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/lightning/node-fee-chart/node-fee-chart.component.ts
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3151 Remove node 19 from the CI test matrix
  .github/workflows/ci.yml
Labels: cla-signed

#3077 Log warning when pools are out of date
  backend/README.md
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#3152 Transifex pull 26/2
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.hu.xlf
  frontend/src/locale/messages.ro.xlf
Labels: cla-signed

#3155 Update `backend/src/__fixtures__/mempool-config.template.json` to match default config.ts value
  backend/src/__fixtures__/mempool-config.template.json
Labels: cla-signed

#3149 Update missing "pools.json" -> "pools-v2.json"
  backend/README.md
  backend/mempool-config.sample.json
  backend/src/api/pools-parser.ts
  backend/src/repositories/PoolsRepository.ts
  docker/README.md
  docker/backend/start.sh
Labels: cla-signed

#3153 Enable GBT mempool in all production configs
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
Labels: cla-signed

#3154 Replace `--reindex=xxx,xxx` command line with `--reindex-blocks`
  backend/src/api/database-migration.ts
  backend/src/index.ts
Labels: cla-signed

#3150 ops: Update nginx-cache-warmer for new pool slugs API
  production/nginx-cache-warmer
Labels: ops, cla-signed

#3102 Ignore coinbase transaction in block health calculation
  backend/src/api/audit.ts
Labels: cla-signed

#3130 Improve error handling on channel component
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/channel/channel.component.ts
  frontend/src/app/lightning/node/node.component.html
Labels: cla-signed

#3158 Truncate `coinbase_signature` and `coinbase_signature_ascii` before insertion if needed
  backend/src/index.ts
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#3170 Transifex pull (2)
  frontend/src/locale/messages.ar.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.it.xlf
  frontend/src/locale/messages.nb.xlf
  frontend/src/locale/messages.pt.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.uk.xlf
Labels: cla-signed

#3171 Use relative path to import price service
  frontend/src/app/components/amount/amount.component.ts
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.ts
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.ts
Labels: cla-signed
