Repository mempool/mempool, pull requests merged in 2023-07, with the labels that each got.

#3916 Fix transaction component ETA
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#3855 Fix inconsistent websocket responses
  backend/src/api/blocks.ts
  backend/src/api/websocket-handler.ts
  backend/src/index.ts
  frontend/src/app/interfaces/websocket.interface.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#3878 Add 'all time' option for mempool graph
  backend/src/api/statistics/statistics-api.ts
  backend/src/api/statistics/statistics.routes.ts
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.scss
  frontend/src/app/components/statistics/statistics.component.ts
  frontend/src/app/services/api.service.ts
  production/nginx-cache-warmer
Labels: cla-signed

#3881 Separate summary and audit-summary API endpoints
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/blocks.ts
  backend/src/repositories/BlocksAuditsRepository.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#3883 Update ronindojo link on about page
  frontend/src/app/components/about/about.component.html
Labels: cla-signed

#3887 Atomic CPFP database operations
  backend/src/api/blocks.ts
  backend/src/database.ts
  backend/src/repositories/CpfpRepository.ts
  backend/src/repositories/TransactionRepository.ts
Labels: cla-signed

#3843 Better projected fee graph
  backend/src/api/mempool-blocks.ts
  frontend/src/app/components/fee-distribution-graph/fee-distribution-graph.component.ts
  frontend/src/app/components/mempool-block/mempool-block.component.html
  frontend/src/app/components/mempool-block/mempool-block.component.ts
  frontend/src/app/services/state.service.ts
  frontend/src/styles.scss
Labels: cla-signed

#3917 Save effective rates to templates & summaries
  backend/src/api/blocks.ts
  backend/src/api/common.ts
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#3863 scroll to see all mempool blocks
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/start/start.component.html
  frontend/src/app/components/start/start.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#3919 Add average fee delta to pool ranking
  backend/src/api/mining/mining.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/PoolsRepository.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#3915 More precise relative block times
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/time/time.component.ts
  frontend/src/app/shared/components/timestamp/timestamp.component.html
  frontend/src/app/shared/components/timestamp/timestamp.component.ts
Labels: cla-signed

#3889 Rust GBT
  .github/workflows/ci.yml
  .gitignore
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  backend/README.md
  backend/mempool-config.sample.json
  backend/package-lock.json
  backend/package.json
  backend/rust-gbt/.gitignore
  backend/rust-gbt/Cargo.toml
  backend/rust-gbt/README.md
  backend/rust-gbt/build.rs
  backend/rust-gbt/index.d.ts
  backend/rust-gbt/index.js
  backend/rust-gbt/package-lock.json
  backend/rust-gbt/package.json
  backend/rust-gbt/src/audit_transaction.rs
  backend/rust-gbt/src/gbt.rs
  backend/rust-gbt/src/lib.rs
  backend/rust-gbt/src/thread_transaction.rs
  backend/rust-gbt/src/u32_hasher_types.rs
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/__tests__/gbt/gbt-tests.ts
  backend/src/__tests__/gbt/test-data/target-template.json
  backend/src/__tests__/gbt/test-data/test-buffer.bin
  backend/src/__tests__/gbt/test-data/test-data-ids.json
  backend/src/api/blocks.ts
  backend/src/api/disk-cache.ts
  backend/src/api/mempool-blocks.ts
  backend/src/api/mempool.ts
  backend/src/api/transaction-utils.ts
  backend/src/api/websocket-handler.ts
  backend/src/config.ts
  backend/src/mempool.interfaces.ts
  docker/backend/Dockerfile
  docker/backend/mempool-config.json
  docker/backend/start.sh
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
  rust-toolchain
Labels: cla-signed

#3869 Weight unit preference
  frontend/src/app/bisq/bisq-transaction/bisq-transaction.component.html
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/clock/clock.component.html
  frontend/src/app/components/fee-distribution-graph/fee-distribution-graph.component.ts
  frontend/src/app/components/fees-box/fees-box.component.html
  frontend/src/app/components/footer/footer.component.html
  frontend/src/app/components/incoming-transactions-graph/incoming-transactions-graph.component.ts
  frontend/src/app/components/mempool-block/mempool-block.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/mempool-graph/mempool-graph.component.ts
  frontend/src/app/components/rate-unit-selector/rate-unit-selector.component.html
  frontend/src/app/components/rate-unit-selector/rate-unit-selector.component.scss
  frontend/src/app/components/rate-unit-selector/rate-unit-selector.component.ts
  frontend/src/app/components/rbf-timeline/rbf-timeline-tooltip.component.html
  frontend/src/app/components/rbf-timeline/rbf-timeline.component.html
  frontend/src/app/components/rbf-timeline/rbf-timeline.component.scss
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/services/state.service.ts
  frontend/src/app/shared/components/fee-rate/fee-rate.component.html
  frontend/src/app/shared/components/fee-rate/fee-rate.component.scss
  frontend/src/app/shared/components/fee-rate/fee-rate.component.ts
  frontend/src/app/shared/components/global-footer/global-footer.component.html
  frontend/src/app/shared/components/weight-directives/weight-directives.ts
  frontend/src/app/shared/pipes/bytes-pipe/wubytes.pipe.ts
  frontend/src/app/shared/pipes/fee-rounding/fee-rounding.pipe.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles.scss
Labels: cla-signed

#3932 Stale blocks
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.interface.ts
  backend/src/api/blocks.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksAuditsRepository.ts
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
  frontend/src/app/interfaces/electrs.interface.ts
Labels: cla-signed

#3946 Upgrade bitcoin core to v25.0
  production/install
Labels: cla-signed

#3879 exclude fullrbf txs from audit and label in visualization
  backend/src/api/audit.ts
  backend/src/api/database-migration.ts
  backend/src/api/rbf-cache.ts
  backend/src/api/websocket-handler.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksAuditsRepository.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/interfaces/websocket.interface.ts
Labels: cla-signed

#3947 fix price updater loop on testnet/signet
  backend/src/indexer.ts
Labels: cla-signed

#3669 Fix RTL issues
  frontend/src/app/components/change/change.component.html
  frontend/src/styles.scss
Labels: cla-signed

#3945 Fix mined rbf conflict prevention
  backend/src/api/common.ts
Labels: cla-signed

#3955 Fix production rust GBT build
  backend/package-lock.json
Labels: cla-signed

#3953 always show latest difficulty on hashrate chart
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
Labels: cla-signed

#3941 reset blocks$ and transactions$ observables when network changes
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#3620 Fix RTL locale unfurls
  unfurler/src/index.ts
Labels: cla-signed

#3693 prevent table overflow in unfurl previews
  frontend/src/app/components/address/address-preview.component.html
  frontend/src/app/components/address/address-preview.component.scss
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
  frontend/src/app/lightning/channel/channel-preview.component.html
  frontend/src/app/lightning/channel/channel-preview.component.scss
  frontend/src/app/lightning/node/node-preview.component.scss
Labels: cla-signed

#3943 Add spacer for missing fiat values
  frontend/src/app/fiat/fiat.component.html
Labels: cla-signed

#3937 Replace client-side stale blocks
  backend/src/api/blocks.ts
  backend/src/api/websocket-handler.ts
  frontend/src/app/bisq/bisq-transaction/bisq-transaction.component.ts
  frontend/src/app/bisq/bisq-transfers/bisq-transfers.component.ts
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/components/clock-face/clock-face.component.ts
  frontend/src/app/components/clock/clock.component.ts
  frontend/src/app/components/difficulty-mining/difficulty-mining.component.ts
  frontend/src/app/components/difficulty/difficulty.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/pool/pool.component.ts
  frontend/src/app/components/reward-stats/reward-stats.component.ts
  frontend/src/app/components/start/start.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/services/cache.service.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#3948 show "loading" message while checking for cached txs
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#3940 Unknown avg miner health
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#3957 highlight & tag fullrbf replacements in RBF timeline
  backend/src/api/rbf-cache.ts
  frontend/src/app/components/rbf-timeline/rbf-timeline-tooltip.component.html
  frontend/src/app/components/rbf-timeline/rbf-timeline-tooltip.component.ts
  frontend/src/app/components/rbf-timeline/rbf-timeline.component.html
  frontend/src/app/components/rbf-timeline/rbf-timeline.component.scss
  frontend/src/app/components/rbf-timeline/rbf-timeline.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#3670 Push TX: Include validation to prevent DoS
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/common.ts
  backend/src/config.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
Labels: cla-signed

#3952 Connectivity ranking title fix
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.ts
Labels: cla-signed

#3961 Fix difficulty chart off-by-one bug
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
Labels: cla-signed

#3951 Highlight searched transactions in the block visualizations
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/block-scene.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#3962 Switch "Latest blocks" to "Latest replacements"
  backend/src/api/rbf-cache.ts
  backend/src/api/websocket-handler.ts
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/interfaces/websocket.interface.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#3621 Pixel-aligned grids for sharper block visualizations
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.html
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.scss
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/block-scene.ts
  frontend/src/app/components/block/block-preview.component.html
  frontend/src/app/components/block/block-preview.component.scss
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
  frontend/src/app/components/clock/clock.component.html
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.html
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.ts
Labels: cla-signed

#3875 Bitcoin-Fiat calculator tool
  frontend/src/app/app-routing.module.ts
  frontend/src/app/components/calculator/calculator.component.html
  frontend/src/app/components/calculator/calculator.component.scss
  frontend/src/app/components/calculator/calculator.component.ts
  frontend/src/app/shared/pipes/bitcoinsatoshis.pipe.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#3967 [price updater] update latestPrices timestamp before pushing to websocket
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#3964 Calculator validation improvements
  frontend/src/app/components/calculator/calculator.component.html
  frontend/src/app/components/calculator/calculator.component.ts
Labels: cla-signed

#3974 Set missing websocket init data
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#3971 Add "recently cpfpd" exception to audits
  backend/src/api/audit.ts
  backend/src/api/mempool-blocks.ts
  backend/src/mempool.interfaces.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/interfaces/websocket.interface.ts
Labels: cla-signed

#3976 always send 6 latest transactions to websocket clients
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#3882 Audit data synchronization
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/config.ts
  backend/src/indexer.ts
  backend/src/mempool.interfaces.ts
  backend/src/replication/AuditReplication.ts
  backend/src/replication/replicator.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
  production/mempool-config.mainnet.json
Labels: cla-signed

#3978 unbork mining pool blocks list
  frontend/src/app/components/pool/pool.component.ts
Labels: embarrassing, cla-signed

#3959 Load more mempool transactions
  backend/src/api/bitcoin/bitcoin.routes.ts
  frontend/src/app/components/address/address.component.ts
  frontend/src/app/services/electrs-api.service.ts
Labels: cla-signed

#3982 Fix mempool update poll delay
  backend/src/index.ts
Labels: cla-signed

#3979 get chain tip direct from Bitcoin Core to avoid race conditions
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/blocks.ts
Labels: cla-signed

#3983 Hide confirmations badge if height unknown
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/shared/components/confirmations/confirmations.component.html
Labels: cla-signed

#3867 It's time (Enable fullrbf)
  production/bitcoin.conf
  production/bitcoin.minfee.conf
Labels: cla-signed

#3988 Fix clock horizontal scroll bug
  frontend/src/app/components/clock/clock.component.scss
Labels: cla-signed

#3989 Remove frontend FULL_RBF_ENABLED flag
  docker/frontend/entrypoint.sh
  frontend/mempool-frontend-config.sample.json
  frontend/src/app/components/rbf-list/rbf-list.component.html
  frontend/src/app/components/rbf-list/rbf-list.component.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#3992 Angular 16
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/styles.scss
Labels: cla-signed

#3965 [network selection] fix some align issues
  frontend/src/app/components/bisq-master-page/bisq-master-page.component.html
  frontend/src/app/components/bisq-master-page/bisq-master-page.component.scss
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.html
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.scss
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
Labels: cla-signed

#3993 Bumping backend deps
  backend/package-lock.json
  backend/package.json
  backend/src/api/bisq/bisq.ts
Labels: cla-signed

#3990 Removing unused rbf frontend code
  frontend/src/app/components/rbf-list/rbf-list.component.html
  frontend/src/app/components/rbf-list/rbf-list.component.ts
  frontend/src/app/dashboard/dashboard.component.ts
Labels: cla-signed

#3935 Add lightning justice page
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/channels.routes.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/lightning/justice-list/justice-list.component.html
  frontend/src/app/lightning/justice-list/justice-list.component.scss
  frontend/src/app/lightning/justice-list/justice-list.component.ts
  frontend/src/app/lightning/lightning-api.service.ts
  frontend/src/app/lightning/lightning.module.ts
  frontend/src/app/lightning/lightning.routing.module.ts
  frontend/src/app/shared/components/truncate/truncate.component.html
  frontend/src/app/shared/components/truncate/truncate.component.scss
  frontend/src/app/shared/components/truncate/truncate.component.ts
Labels: cla-signed

#3996 Fix for 0 sat minimum fee
  frontend/src/app/dashboard/dashboard.component.html
Labels: cla-signed

#3997 restore latest blocks on liquid
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.ts
Labels: cla-signed

#3607 Clip overflowing labels in pool component on mobile
  frontend/src/app/components/pool/pool.component.html
  frontend/src/app/components/pool/pool.component.scss
Labels: cla-signed

#3194 Specify manual deployment support for enterprise sponsors
  backend/README.md
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  production/README.md
Labels: cla-signed

#3949 Add node v20 to the test matrix
  .github/workflows/ci.yml
Labels: cla-signed

#3773 [search bar] fix alignment issue
  frontend/src/app/components/master-page/master-page.component.scss
  frontend/src/app/components/search-form/search-form.component.scss
Labels: cla-signed

#4002 [mining] add missing empty td at the bottom of pool ranking
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
Labels: cla-signed

#4016 Tweak dependabot settings
  .github/dependabot.yml
Labels: cla-signed

#3934 Fix backend docker build for armv7
  backend/.dockerignore
  docker/backend/Dockerfile
Labels: cla-signed

#4014 Fix blocks list observable
  frontend/src/app/components/blocks-list/blocks-list.component.ts
Labels: cla-signed

#4013 Fix some icon css color changes
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/nodes-rankings-dashboard/nodes-rankings-dashboard.component.html
Labels: UI/UX, cla-signed

#4021 apply blockchain scroll offset as soon as element is ready
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#4030 Use more reliable Github Action for Rust toolchain install
  .github/workflows/ci.yml
Labels: cla-signed

#4031 Es2022 fixes
  frontend/.browserslistrc
  frontend/tsconfig.base.json
Labels: cla-signed

#4027 Support P2PK address types
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/bitcoin/electrum-api.ts
  backend/src/api/bitcoin/esplora-api.interface.ts
  backend/src/api/bitcoin/esplora-api.ts
  frontend/src/app/bitcoin.utils.ts
  frontend/src/app/components/address/address-preview.component.ts
  frontend/src/app/components/address/address.component.scss
  frontend/src/app/components/address/address.component.ts
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.scss
  frontend/src/app/interfaces/electrs.interface.ts
  frontend/src/app/services/electrs-api.service.ts
Labels: cla-signed

#4039 Fix missing sigops
  backend/src/api/mempool.ts
  backend/src/api/transaction-utils.ts
Labels: cla-signed

#4041 Sanitize channel id search
  backend/src/api/explorer/channels.api.ts
Labels: cla-signed

#4035 Lightning channel balance progress bars
  frontend/src/app/lightning/channel/channel-close-box/channel-close-box.component.html
  frontend/src/app/lightning/channel/channel-close-box/channel-close-box.component.scss
  frontend/src/app/lightning/channel/channel-close-box/channel-close-box.component.ts
  frontend/src/app/lightning/channel/channel.component.html
Labels: cla-signed

#4043 Mempool inSync status
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/api/mempool.ts
  backend/src/api/websocket-handler.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#4025 load mempool txs in bulk from esplora
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/api/mempool.ts
Labels: cla-signed

#4045 Faster blocks
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/api/blocks.ts
  backend/src/api/transaction-utils.ts
Labels: cla-signed

#4028 [search bar] only autofocus when in `/`, `/mining` and `/lightning`
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.ts
  frontend/src/app/components/search-form/search-form.component.html
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/shared/pipes/bytes-pipe/utils.ts
Labels: cla-signed

#4046 Exclude all conflicting transactions from audit score
  backend/src/api/audit.ts
  backend/src/api/rbf-cache.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/interfaces/websocket.interface.ts
Labels: cla-signed

#4048 Fix key navigation subscription leak
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
Labels: cla-signed

#4049 Support p2pk track-address websocket subscriptions
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#4054 Show new mined transactions on the address page
  frontend/src/app/components/address/address.component.ts
Labels: cla-signed

#4059 fix websocket connection state observable
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#4053 [mining] use .slug to load pool logo
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/components/pool/pool-preview.component.ts
  frontend/src/app/components/pool/pool.component.ts
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/mining.service.ts
Labels: cla-signed

#4050 Handle failures while fetching block transactions
  backend/src/api/blocks.ts
  backend/src/api/transaction-utils.ts
Labels: cla-signed

#4056 Add support for compressed p2pk addresses
  backend/src/api/websocket-handler.ts
  frontend/src/app/components/address/address-preview.component.ts
  frontend/src/app/components/address/address.component.ts
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/services/electrs-api.service.ts
Labels: cla-signed

#4026 [graphs] fix min height in mobile landscape
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.scss
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.scss
  frontend/src/app/components/block-health-graph/block-health-graph.component.scss
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.scss
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.scss
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.scss
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.scss
  frontend/src/app/lightning/nodes-map/nodes-map.component.scss
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.scss
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.scss
Labels: cla-signed

#3905 Update mosp strings from tm to r
  LICENSE
  README.md
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/privacy-policy/privacy-policy.component.html
  frontend/src/app/components/trademark-policy/trademark-policy.component.html
  frontend/src/app/shared/components/global-footer/global-footer.component.html
  frontend/src/index.bisq.html
  frontend/src/index.liquid.html
  frontend/src/index.mempool.html
  unfurler/src/index.ts
Labels: legal, cla-signed

#4034 Fix difficulty tooltip position
  frontend/src/app/components/difficulty/difficulty.component.ts
Labels: cla-signed

#4066 Remove text from mempool.space preview image
  frontend/src/resources/mempool-space-preview.png
  frontend/src/resources/previews/dashboard.png
Labels: cla-signed

#4063 Simple Redis
  backend/mempool-config.sample.json
  backend/package-lock.json
  backend/package.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/blocks.ts
  backend/src/api/disk-cache.ts
  backend/src/api/mempool.ts
  backend/src/api/rbf-cache.ts
  backend/src/api/redis-cache.ts
  backend/src/api/transaction-utils.ts
  backend/src/config.ts
  backend/src/index.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#4070 Misc Redis fixes
  backend/src/api/redis-cache.ts
Labels: cla-signed

#4072 Fix scripthash lookup for Electrum*
  backend/src/api/bitcoin/bitcoin.routes.ts
Labels: cla-signed
