Repository mempool/mempool, pull requests merged in 2023-04, with the labels that each got.

#3375 Update some logs
  backend/src/api/blocks.ts
  backend/src/api/disk-cache.ts
  backend/src/api/mining/mining.ts
  backend/src/tasks/lightning/forensics.service.ts
  backend/src/tasks/lightning/network-sync.service.ts
  backend/src/tasks/pools-updater.ts
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#3443 Update backend NPM deps
  backend/package-lock.json
  backend/package.json
  backend/tsconfig.json
Labels: cla-signed

#3608 Use window.location object instead of angular router for default graph window preference setting
  frontend/src/app/services/storage.service.ts
Labels: cla-signed

#3618 Wrap lightning stats importer into try/catch
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
Labels: cla-signed

#3326 Show warning on testnet/signet
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
  frontend/src/app/components/master-page/master-page.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#3404 Fix % on heap limit warn
  backend/src/index.ts
Labels: cla-signed

#3568 Fix anchor link expand on mobile for mempool faq
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#3586 Add missing sanity check when fetching single price datapoint
  backend/src/repositories/PricesRepository.ts
Labels: cla-signed

#3599 Fix node unfurl row overflow
  frontend/src/app/lightning/node/node-preview.component.html
  frontend/src/app/lightning/node/node-preview.component.scss
Labels: cla-signed

#3600 Fix unfurl cpfp badge
  frontend/src/app/components/transaction/transaction-preview.component.html
Labels: cla-signed

#3442 When a re-org happens, keep the block templates for audit
  backend/src/api/blocks.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/BlocksSummariesRepository.ts
  backend/src/repositories/HashratesRepository.ts
Labels: cla-signed

#3601 Fix broken tx diagram for non-LBTC liquid assets
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.html
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#3587 Update mynode profile on about page
  frontend/src/app/components/about/about.component.html
  frontend/src/resources/profile/mynodebtc.jpg
  frontend/src/resources/profile/mynodebtc.png
Labels: cla-signed

#3247 ops: Use unix sockets to query esplora from nginx
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/config.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
  production/electrs-start-liquid
  production/electrs-start-liquidtestnet
  production/electrs-start-mainnet
  production/electrs-start-signet
  production/electrs-start-testnet
  production/install
  production/mempool-config.liquid.json
  production/mempool-config.liquidtestnet.json
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
  production/newsyslog-mempool-nginx.conf
  production/nginx/upstream-esplora.conf
Labels: enhancement, blockstream/electrs, ops, cla-signed

#3622 Key modifiers to open transaction in new tab from visualization
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/mempool-block-overview/mempool-block-overview.component.ts
Labels: cla-signed

#3630 Switch phoenix wallet logo to dark mode
  frontend/src/app/components/about/about.component.html
  frontend/src/resources/profile/phoenix.jpg
  frontend/src/resources/profile/phoenix.svg
Labels: cla-signed

#3631 Redesigned testnet alert
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.html
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
  frontend/src/app/components/master-page/master-page.component.ts
  frontend/src/app/shared/components/testnet-alert/testnet-alert.component.html
  frontend/src/app/shared/components/testnet-alert/testnet-alert.component.scss
  frontend/src/app/shared/components/testnet-alert/testnet-alert.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#3634 Make fiat component color class customizable
  frontend/src/app/fiat/fiat.component.html
  frontend/src/app/fiat/fiat.component.scss
  frontend/src/app/fiat/fiat.component.ts
Labels: cla-signed

#3640 ops: Use unix sockets for MySQL
  production/mempool-config.bisq.json
  production/mempool-config.liquid.json
  production/mempool-config.liquidtestnet.json
  production/mempool-config.mainnet-lightning.json
  production/mempool-config.mainnet.json
  production/mempool-config.signet-lightning.json
  production/mempool-config.signet.json
  production/mempool-config.testnet-lightning.json
  production/mempool-config.testnet.json
Labels: ops, cla-signed

#3643 [esplora] fallback to tcp socket if unix socket fails
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/config.ts
  backend/src/index.ts
  production/mempool-config.mainnet-lightning.json
Labels: cla-signed

#3649 Fix indexing error
  backend/src/api/blocks.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/BlocksSummariesRepository.ts
Labels: cla-signed

#3656 [config] add missing RETRY_UNIX_SOCKET_AFTER
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#3644 Perform full cpfp calculations for the entire mempool
  backend/src/api/tx-selection-worker.ts
Labels: cla-signed

#3633 Disable blockchain drag for middle/right click
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#3652 Disable mempool block animations except when new block is mined
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
Labels: cla-signed

#3694 Revert TCP socket fallback
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/index.ts
Labels: cla-signed

#3687 Backend block tip height endpoint
  backend/src/api/bitcoin/bitcoin.routes.ts
Labels: cla-signed

#3696 Add explicit timeout to mysql DB queries
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/config.ts
  backend/src/database.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#3689 detect and log stalls in the main loop
  backend/src/api/blocks.ts
  backend/src/api/mempool.ts
Labels: cla-signed

#3700 await for mempool change handler after loading disk cache
  backend/src/api/disk-cache.ts
  backend/src/api/mempool-blocks.ts
  backend/src/api/mempool.ts
  backend/src/api/websocket-handler.ts
  backend/src/index.ts
Labels: cla-signed
