Repository mempool/mempool, pull requests merged in 2023-01, with the labels that each got.

#2339 Logs cleanup
  backend/src/api/blocks.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/lightning/clightning/clightning-client.ts
  backend/src/api/lightning/clightning/clightning-convert.ts
  backend/src/api/mining/mining.ts
  backend/src/api/pools-parser.ts
  backend/src/logger.ts
  backend/src/tasks/lightning/network-sync.service.ts
  backend/src/tasks/lightning/stats-updater.service.ts
  backend/src/tasks/lightning/sync-tasks/funding-tx-fetcher.ts
  backend/src/tasks/lightning/sync-tasks/node-locations.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
  backend/src/tasks/pools-updater.ts
  backend/src/tasks/price-feeds/kraken-api.ts
  backend/src/tasks/price-updater.ts
Labels: cla-signed

#2851 Fix error 500 when querying /blocks using `"INDEXING_BLOCKS_AMOUNT": 0`
  backend/src/api/blocks.ts
Labels: cla-signed

#2907 Set `LIGHTNING: true` in prod frontend config
  production/mempool-frontend-config.mainnet.json
Labels: ops, cla-signed

#2909 Fix Docker GHA again. Update deps and increase swap size
  .github/workflows/on-tag.yml
Labels: cla-signed

#2910 Add the missing block audit variables to the Docker script
  docker/frontend/entrypoint.sh
Labels: cla-signed

#2918 ops: fix mysql_credentials path in install/build scripts
  production/install
  production/mempool-build-all
Labels: ops, cla-signed

#2919 ops: add tk7 nodes to prod bitcoin.conf
  production/bitcoin.conf
Labels: ops, cla-signed

#2920 ops: add mempool-reset-all script with ./reset symlink
  production/install
  production/mempool-reset-all
Labels: cla-signed

#2921 ops: fix wildcards in mempool-reset-all script
  production/mempool-reset-all
Labels: ops, cla-signed

#2916 Fetch coinbase tx with core when esplora fails to do so
  backend/src/api/audit.ts
  backend/src/api/bitcoin/bitcoin-api-factory.ts
  backend/src/api/blocks.ts
  backend/src/api/transaction-utils.ts
Labels: cla-signed

#2933 Add new mempool lightning nodes and format the array so it's human readable
  backend/src/api/explorer/nodes.routes.ts
Labels: cla-signed

#2937 Fallback alias name to pubkey
  frontend/src/app/components/address-labels/address-labels.component.ts
Labels: cla-signed

#2923 Ignore pool logo download failure as it's not a critical error
  frontend/sync-assets.js
Labels: cla-signed

#2940 Expose whether Lightning is enabled on the backend
  backend/src/api/backend-info.ts
  backend/src/mempool.interfaces.ts
Labels: enhancement, ⚡Lightning, cla-signed, docker

#2941 Dark mode inputs
  frontend/src/app/components/search-form/search-form.component.html
  frontend/src/app/components/search-form/search-form.component.scss
  frontend/src/styles.scss
Labels: cla-signed

#2939 CPFP Optimizations
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/CpfpRepository.ts
  backend/src/repositories/TransactionRepository.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#2884 Infinitely scrolling blockchain
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/blocks.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/app/app.component.ts
  frontend/src/app/components/block/block.component.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.scss
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/components/start/start.component.html
  frontend/src/app/components/start/start.component.ts
  frontend/src/app/components/transaction/transaction-preview.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/cache.service.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#2852 Remove pools.json download from the frontend
  frontend/cypress/e2e/liquid/liquid.spec.ts
  frontend/cypress/e2e/liquidtestnet/liquidtestnet.spec.ts
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
  frontend/proxy.conf.js
  frontend/sync-assets.js
Labels: cla-signed

#2885 Add FAQ link to empty blocks
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
Labels: cla-signed

#2947 Fix missing audit Docker config
  docker/backend/start.sh
Labels: cla-signed, docker

#2946 Dependabot: Monitor only production dependencies and add frontend Docker dir
  .github/dependabot.yml
Labels: ops, cla-signed

#2886 Update frontend packages to please dependabot
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#2887 Updating backend dependencies to please dependabot
  backend/package-lock.json
  backend/package.json
Labels: cla-signed

#2953 Pull from transifex 01-15
  frontend/src/locale/messages.cs.xlf
  frontend/src/locale/messages.lt.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#2943 Node AS table overflow fix
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.ts
Labels: cla-signed

#2917 Show `Avg fees per block` instead of `Reward Per Tx`
  frontend/src/app/components/reward-stats/reward-stats.component.html
  frontend/src/app/components/reward-stats/reward-stats.component.ts
Labels: cla-signed

#2914 dynamic CSS text truncation component
  frontend/src/app/bisq/bisq-address/bisq-address.component.html
  frontend/src/app/bisq/bisq-transaction/bisq-transaction.component.html
  frontend/src/app/components/address/address-preview.component.html
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/asset/asset.component.html
  frontend/src/app/components/master-page-preview/master-page-preview.component.scss
  frontend/src/app/components/transaction/transaction-preview.component.html
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.scss
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.scss
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.html
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.scss
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/lightning/channel/channel-box/channel-box.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
  frontend/src/app/shared/components/truncate/truncate.component.html
  frontend/src/app/shared/components/truncate/truncate.component.scss
  frontend/src/app/shared/components/truncate/truncate.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#2955 Fix cpfp observable error
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#2956 Fix missing clipboard buttons
  frontend/src/app/components/transaction/transaction.component.scss
  frontend/src/app/shared/components/truncate/truncate.component.html
Labels: cla-signed

#2957 Support inner links in truncated string component
  frontend/src/app/bisq/bisq-address/bisq-address.component.html
  frontend/src/app/bisq/bisq-transaction/bisq-transaction.component.html
  frontend/src/app/components/address/address-preview.component.html
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/asset/asset.component.html
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/lightning/channel/channel-box/channel-box.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/shared/components/truncate/truncate.component.html
  frontend/src/app/shared/components/truncate/truncate.component.scss
  frontend/src/app/shared/components/truncate/truncate.component.ts
Labels: cla-signed

#2959 reduce prominence of marginal fee rate audit txs
  frontend/src/app/components/block-overview-graph/tx-view.ts
Labels: cla-signed

#2960 Fix mempool block gradients
  backend/src/api/common.ts
Labels: cla-signed

#2966 Removing absolute path import
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
Labels: cla-signed

#2964 better frontend handling for very large witnesses
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.scss
Labels: cla-signed

#2824 cache, serve & display more comprehensive RBF info
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/common.ts
  backend/src/api/mempool.ts
  backend/src/api/rbf-cache.ts
  backend/src/api/websocket-handler.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.scss
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#2969 Extracting i18n strings
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/reward-stats/reward-stats.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/lightning/node/node.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#2950 Correctly drop legacy cpfp db tables
  backend/src/api/database-migration.ts
Labels: cla-signed

#2808 Fix hexadecimal conversion to show leading zeros
  frontend/src/app/shared/pipes/decimal2hex/decimal2hex.pipe.ts
Labels: cla-signed

#2833 Fix routing for top-nav doc button
  frontend/src/app/docs/docs.routing.module.ts
Labels: cla-signed

#2951 Fix page elements obscured by bottom navbar on mobile
  frontend/src/app/bisq/bisq-blocks/bisq-blocks.component.html
  frontend/src/app/components/assets/assets.component.html
  frontend/src/app/components/block-fee-rates-graph/block-fee-rates-graph.component.scss
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.scss
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.scss
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.scss
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.scss
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.scss
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.scss
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.scss
  frontend/src/app/components/statistics/statistics.component.scss
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/docs/docs/docs.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.scss
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.scss
Labels: cla-signed

#2974 Fix node chart legend position error
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.ts
Labels: cla-signed

#2981 Fix for disabling block audit below block height
  frontend/src/app/components/block/block.component.ts
Labels: cla-signed

#2978 Only show block audit highlighting when audit is enabled
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.html
  frontend/src/app/components/block-overview-graph/block-overview-graph.component.ts
  frontend/src/app/components/block-overview-graph/block-scene.ts
  frontend/src/app/components/block-overview-graph/tx-view.ts
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.ts
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#2988 Fix navigation-breaking JS error on liquid block page
  frontend/src/app/components/block/block.component.ts
Labels: cla-signed

#2987 Fix blockchain gaps when KEEP_BLOCKS_AMOUNT > INITIAL_BLOCKS_AMOUNT
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#2992 More prominent audit status badges
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
Labels: cla-signed

#2996 Block health string update
  frontend/src/app/components/block/block.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#2908 Removing Lightning Beta tag
  frontend/src/app/components/block/block.component.html
  frontend/src/app/components/block/block.component.scss
  frontend/src/app/components/master-page/master-page.component.html
Labels: cla-signed
