Repository mempool/mempool, pull requests merged in 2023-03, with the labels that each got.

#3044 Fix node socket parsing with LND
  backend/src/api/common.ts
Labels: cla-signed

#3040 [LND] Nullify zeroed timestamps
  backend/src/api/common.ts
  backend/src/api/database-migration.ts
  backend/src/api/explorer/channels.api.ts
  backend/src/api/explorer/nodes.api.ts
  backend/src/api/lightning/lightning-api.interface.ts
  backend/src/tasks/lightning/network-sync.service.ts
Labels: cla-signed

#3178 Reset scrolling blockchain cache when network changes
  frontend/src/app/services/cache.service.ts
Labels: cla-signed

#3179 Center-align blockchain when resetting scroll position
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#3116 Align dashboards
  backend/src/api/explorer/nodes.api.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
  frontend/src/app/lightning/lightning-dashboard/lightning-dashboard.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.scss
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.scss
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.ts
Labels: cla-signed

#3160 Run Cypress tests on master after merging
  .github/workflows/cypress.yml
Labels: cla-signed

#3184 Only run migration 57 if bitcoin
  backend/src/api/database-migration.ts
Labels: cla-signed

#3187 Pull from transifex 1/3
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.mk.xlf
  frontend/src/locale/messages.vi.xlf
Labels: cla-signed

#3186 Ignore negative USD prices
  backend/src/repositories/PricesRepository.ts
Labels: cla-signed

#3166 Always return the same block structure for endpoints which return blocks data
  backend/src/api/bitcoin/bitcoin-api.interface.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.interface.ts
  backend/src/api/blocks.ts
  backend/src/api/chain-tips.ts
  backend/src/api/disk-cache.ts
  backend/src/api/mining/mining.ts
  backend/src/api/pools-parser.ts
  backend/src/index.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/PoolsRepository.ts
  backend/src/utils/blocks-utils.ts
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#3161 Use bitcoinApiFactory when we don't need verbose blocks or confirmation number
  backend/src/api/blocks.ts
  backend/src/api/chain-tips.ts
  backend/src/api/mining/mining.ts
Labels: cla-signed

#3189 Don't try to fetch cpfp when database is disabled
  backend/src/api/bitcoin/bitcoin.routes.ts
Labels: cla-signed

#3190 Remove useless code
  backend/src/api/blocks.ts
Labels: cla-signed

#3191 Don't run CI on "review_requested" event
  .github/workflows/cypress.yml
Labels: cla-signed

#3181 Run ln forensics last
  backend/src/index.ts
Labels: cla-signed

#3185 Add frontend config flag to toggle historical price fetching
  docker/frontend/entrypoint.sh
  frontend/mempool-frontend-config.sample.json
  frontend/src/app/services/price.service.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#3157 Add api documentation for blocks-bulk
  frontend/src/app/docs/api-docs/api-docs-data.ts
Labels: cla-signed

#3174 Link API rate limit note to /enterprise
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#3175 Add anchor links for about page sections
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/app/components/about/about.component.ts
Labels: cla-signed

#3195 Add promo video to about page
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/mempool-promo.jpg
  frontend/sync-assets.js
Labels: cla-signed

#3196 Only show electrum tab on desktop
  frontend/src/app/docs/docs/docs.component.html
  frontend/src/app/docs/docs/docs.component.scss
Labels: cla-signed

#3199 Pull transifex (nl)
  frontend/src/locale/messages.nl.xlf
Labels: cla-signed

#3198 About page video improvements
  frontend/.gitignore
  frontend/src/app/components/about/about.component.scss
Labels: cla-signed

#3148 When we re-index blocks due to mining pools change, wipe the nodejs backend cache
  backend/src/api/disk-cache.ts
  backend/src/api/pools-parser.ts
Labels: cla-signed

#3208 Fix import paths
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-capacity/top-nodes-per-capacity.component.ts
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.ts
Labels: cla-signed

#3204 Default relative paths in VsCode
  .vscode/settings.json
Labels: cla-signed

#3206 Update Cypress to v12.7.0
  frontend/cypress.config.ts
  frontend/cypress/e2e/bisq/bisq.spec.ts
  frontend/cypress/e2e/liquid/liquid.spec.ts
  frontend/cypress/e2e/liquidtestnet/liquidtestnet.spec.ts
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
  frontend/cypress/e2e/mainnet/mining.spec.ts
  frontend/cypress/e2e/signet/signet.spec.ts
  frontend/cypress/e2e/testnet/testnet.spec.ts
  frontend/cypress/plugins/index.js
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#3209 Wipe nodejs backend cache for any mining pool change - Update pools before loading disk cache
  backend/src/api/pools-parser.ts
  backend/src/index.ts
Labels: cla-signed

#3211 Fix blockchain scrolling on iOS devices
  frontend/src/app/components/start/start.component.html
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#3203 Define owners for the DB migration file
  .github/CODEOWNERS
Labels: cla-signed

#3213 Always show BTC amount in block tooltips
  frontend/src/app/components/block-overview-tooltip/block-overview-tooltip.component.html
Labels: cla-signed

#3072 Optimize mempool block 7 data
  backend/src/api/mempool-blocks.ts
Labels: cla-signed

#3202 Use core to fetch block because esplora/electrs still return integer difficulty
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/api/mining/mining.ts
  backend/src/repositories/DifficultyAdjustmentsRepository.ts
Labels: cla-signed

#3219 blockchain momentum scrolling
  frontend/src/app/components/start/start.component.ts
Labels: cla-signed

#3224 ops: Add missing /api/address-prefix nginx route for bisq
  production/nginx/server-bisq.conf
Labels: 💹 Bisq, ops, cla-signed

#2995 Bisq markets search bar fix
  frontend/src/app/components/search-form/search-form.component.ts
Labels: cla-signed

#3122 Remove mining db stats - replaced by runtime state variable
  backend/src/api/database-migration.ts
  backend/src/api/mining/mining.ts
  backend/src/index.ts
  backend/src/indexer.ts
  backend/src/repositories/HashratesRepository.ts
Labels: cla-signed

#3220 drop decimal places from large fiat values
  frontend/src/app/shared/pipes/fiat-currency.pipe.ts
Labels: cla-signed

#3222 Correct incoming transaction progress colors
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/dashboard/dashboard.component.ts
Labels: cla-signed

#3223 Fix overlapping columns in cpfp table on small screens
  frontend/src/app/components/transaction/transaction.component.scss
Labels: cla-signed

#3125 Update some mining indexer log
  backend/src/api/database-migration.ts
  backend/src/api/mining/mining.ts
  backend/src/indexer.ts
  backend/src/repositories/DifficultyAdjustmentsRepository.ts
  backend/src/repositories/HashratesRepository.ts
  backend/src/tasks/lightning/sync-tasks/stats-importer.ts
  backend/src/tasks/pools-updater.ts
  backend/src/tasks/price-feeds/kraken-api.ts
Labels: cla-signed

#3215 Handle missing price (show 0)
  backend/src/api/websocket-handler.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/PricesRepository.ts
  backend/src/tasks/price-feeds/bitfinex-api.ts
  backend/src/tasks/price-updater.ts
  frontend/src/app/components/amount/amount.component.html
  frontend/src/app/fiat/fiat.component.html
  frontend/src/app/services/price.service.ts
Labels: cla-signed

#3212 Fix initial pool update when db is empty
  backend/src/api/disk-cache.ts
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#3230 Monitor heap memory usage
  backend/src/index.ts
  backend/src/utils/format.ts
Labels: cla-signed

#3231 I18n extract. Some minor fixes.
  frontend/src/app/lightning/channel/channel.component.html
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/nodes-ranking/top-nodes-per-channels/top-nodes-per-channels.component.html
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3235 Update clearnet i18n string
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3234 Show ln channel world map using 100% height
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.scss
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#3237 unify time rendering components
  frontend/src/app/bisq/bisq-block/bisq-block.component.html
  frontend/src/app/bisq/bisq-blocks/bisq-blocks.component.html
  frontend/src/app/bisq/bisq-transaction/bisq-transaction.component.html
  frontend/src/app/bisq/bisq-transactions/bisq-transactions.component.html
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.component.html
  frontend/src/app/components/difficulty/difficulty.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/pool/pool.component.html
  frontend/src/app/components/time-since/time-since.component.ts
  frontend/src/app/components/time-span/time-span.component.ts
  frontend/src/app/components/time-until/time-until.component.ts
  frontend/src/app/components/time/time.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/dashboard/dashboard.component.html
  frontend/src/app/shared/components/timestamp/timestamp.component.html
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#3239 don't cache tx data for rbf replacements
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#3225 Make faq disclaimer responsive
  frontend/src/app/components/svg-images/svg-images.component.html
  frontend/src/app/components/svg-images/svg-images.component.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
  frontend/src/app/docs/api-docs/api-docs.component.scss
  frontend/src/app/docs/api-docs/api-docs.component.ts
Labels: cla-signed

#3238 Fix unnecessary cpfp/rbf 404 responses
  backend/src/api/bitcoin/bitcoin.routes.ts
  backend/src/api/mining/mining-routes.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#3243 Pull from transifex
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.lt.xlf
  frontend/src/locale/messages.sv.xlf
Labels: cla-signed

#3244 Fix miscellaneous RTL layout bugs
  frontend/src/app/components/block-fees-graph/block-fees-graph.component.scss
  frontend/src/app/components/block-prediction-graph/block-prediction-graph.component.scss
  frontend/src/app/components/block-rewards-graph/block-rewards-graph.component.scss
  frontend/src/app/components/block-sizes-weights-graph/block-sizes-weights-graph.component.scss
  frontend/src/app/components/graphs/graphs.component.html
  frontend/src/app/components/graphs/graphs.component.scss
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.scss
  frontend/src/app/components/hashrates-chart-pools/hashrate-chart-pools.component.scss
  frontend/src/app/components/pool-ranking/pool-ranking.component.scss
  frontend/src/app/lightning/channel/channel.component.scss
  frontend/src/app/lightning/channels-list/channels-list.component.scss
  frontend/src/app/lightning/group/group.component.html
  frontend/src/app/lightning/group/group.component.scss
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/nodes-networks-chart/nodes-networks-chart.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.scss
  frontend/src/styles.scss
Labels: cla-signed

#3249 Fix typo in bulk config variable
  docker/backend/mempool-config.json
Labels: cla-signed, docker

#3227 Adding 4 year button to mempool graph
  backend/src/api/common.ts
  backend/src/api/mining/mining.ts
  backend/src/api/statistics/statistics-api.ts
  backend/src/api/statistics/statistics.routes.ts
  frontend/src/app/components/statistics/statistics.component.html
  frontend/src/app/components/statistics/statistics.component.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/shared/graphs.utils.ts
  production/nginx-cache-warmer
Labels: cla-signed

#3259 Fix memory-intensive getCPFPUnindexedBlocks mysql query
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#3262 Pull from transifex 8/3
  frontend/src/locale/messages.ar.xlf
  frontend/src/locale/messages.cs.xlf
  frontend/src/locale/messages.da.xlf
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.lt.xlf
  frontend/src/locale/messages.nb.xlf
  frontend/src/locale/messages.nl.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.pt.xlf
  frontend/src/locale/messages.ro.xlf
  frontend/src/locale/messages.ru.xlf
  frontend/src/locale/messages.uk.xlf
  frontend/src/locale/messages.vi.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#3241 Remove fiat plus space
  frontend/src/app/components/amount/amount.component.html
Labels: cla-signed

#3277 i18n: Enable Danish, disable Catalan
  frontend/src/app/app.constants.ts
  nginx-mempool.conf
  nginx.conf
  production/nginx/http-language.conf
Labels: i18n, cla-signed

#3284 Pull from transifex
  frontend/src/locale/messages.fa.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.he.xlf
  frontend/src/locale/messages.ka.xlf
  frontend/src/locale/messages.nb.xlf
  frontend/src/locale/messages.sv.xlf
Labels: cla-signed

#3264 Fix stale mining dashboard data
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#3285 Add old special block events to app constants
  frontend/src/app/app.constants.ts
Labels: cla-signed

#3290 Bump axios from 0.27.2 -> 1.3.4
  backend/package-lock.json
  backend/package.json
Labels: cla-signed

#3291 Revert "Bump axios from 0.27.2 -> 1.3.4"
  backend/package-lock.json
  backend/package.json
Labels: cla-signed

#3298 fix missing cpfp fee ratings on mobile
  frontend/src/app/components/transaction/transaction.component.html
Labels: cla-signed

#3301 pixel-perfect flow diagrams (again)
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#3299 Save cache to disk on SIGTERM/SIGINT
  backend/src/api/disk-cache.ts
Labels: cla-signed

#3305 Remove search bar focus border
  frontend/src/app/components/search-form/search-form.component.scss
Labels: cla-signed

#3300 Fixes changed after checked error in transaction page
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#3304 Fixes arrow position on confirmed blocks
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#3307 Updated regtest example
  backend/README.md
Labels: cla-signed

#3297 Fixes duplicate block in latest block component
  frontend/src/app/components/blocks-list/blocks-list.component.ts
Labels: cla-signed

#3308 Pull from transifex 2023-03-11
  frontend/src/locale/messages.da.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fi.xlf
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.he.xlf
Labels: cla-signed

#3296 Sort asn numerically - add few more top 10 isp in warm cache
  backend/src/api/explorer/nodes.api.ts
  production/nginx-cache-warmer
Labels: cla-signed

#3309 Fixes i18n duplicate warning
  frontend/src/app/components/difficulty/difficulty-tooltip.component.html
  frontend/src/app/components/difficulty/difficulty-tooltip.component.scss
Labels: cla-signed

#3310 next block lower case css fix
  frontend/src/app/components/difficulty/difficulty-tooltip.component.scss
Labels: cla-signed

#3303 batch address outspend lookups into <50 txids per request
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#3288 Log a warn if there are lot of 404 from esplora tx api while updating nodejs backend mempool
  backend/src/api/mempool.ts
Labels: cla-signed

#3312 Fix epoch length in new difficulty widget
  frontend/src/app/components/difficulty/difficulty.component.html
  frontend/src/app/components/difficulty/difficulty.component.ts
Labels: cla-signed

#3314 Fix some responsive issue on the node component
  frontend/src/app/components/mining-dashboard/mining-dashboard.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.html
  frontend/src/app/lightning/channels-list/channels-list.component.scss
  frontend/src/app/lightning/node/node.component.html
  frontend/src/app/lightning/node/node.component.scss
Labels: cla-signed

#3318 Pull from transifex
  frontend/src/locale/messages.ja.xlf
  frontend/src/locale/messages.lt.xlf
  frontend/src/locale/messages.mk.xlf
  frontend/src/locale/messages.pl.xlf
  frontend/src/locale/messages.pt.xlf
  frontend/src/locale/messages.sv.xlf
Labels: cla-signed

#3311 Lightning dashboard overflow titles fixes
  frontend/src/app/lightning/channels-statistics/channels-statistics.component.scss
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.html
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.scss
Labels: cla-signed

#3306 Display same fee span on blocks
  frontend/src/app/components/block/block.component.html
Labels: cla-signed

#3248 Add youtube and peertube links to about page
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
Labels: cla-signed

#3319 Show tx fee ratings for older blocks
  frontend/src/app/components/tx-fee-rating/tx-fee-rating.component.ts
Labels: cla-signed

#3322 Fix new block animations
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
Labels: cla-signed

#3324 Add 4 community integrations to about page
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/profile/bitcoin-s.svg
  frontend/src/resources/profile/boltz.svg
  frontend/src/resources/profile/edge.svg
  frontend/src/resources/profile/galoy.svg
Labels: cla-signed

#3325 Fix units in flow diagram tooltips for liquid assets
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.html
  frontend/src/app/components/tx-bowtie-graph-tooltip/tx-bowtie-graph-tooltip.component.ts
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.html
  frontend/src/app/components/tx-bowtie-graph/tx-bowtie-graph.component.ts
Labels: cla-signed

#3327 Show cumulated fee on last mempool block
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
Labels: cla-signed

#3330 Save cache to disk every 6 blocks
  backend/src/api/blocks.ts
Labels: cla-signed

#3341 Fix difficulty skeleton width on firefox
  frontend/src/app/components/difficulty-mining/difficulty-mining.component.scss
  frontend/src/app/components/difficulty/difficulty.component.scss
Labels: cla-signed

#3344 Pull from transifex
  frontend/src/locale/messages.de.xlf
  frontend/src/locale/messages.mk.xlf
  frontend/src/locale/messages.pt.xlf
Labels: cla-signed

#3346 i18n extract
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3347 Ninja i18n pull
  frontend/src/locale/messages.sv.xlf
Labels: cla-signed

#3349 Fixing more missing i18n keys
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/lightning/nodes-per-country-chart/nodes-per-country-chart.component.ts
  frontend/src/app/lightning/nodes-per-isp-chart/nodes-per-isp-chart.component.ts
  frontend/src/app/lightning/statistics-chart/lightning-statistics-chart.component.ts
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3352 Fixes i18n string error
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/locale/messages.xlf
Labels: cla-signed

#3350 Correct video height on mobile
  frontend/src/app/components/about/about.component.scss
Labels: cla-signed

#3351 Disable pool update when running lightning only
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#3376 i18n: Enable Danish
  frontend/angular.json
Labels: cla-signed

#3345 Hide features row if tx has no features
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/tx-features/tx-features.component.html
  frontend/src/app/components/tx-features/tx-features.component.ts
Labels: cla-signed

#3329 Add mutiny as community integration
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/profile/mutiny.svg
Labels: cla-signed

#3331 Add network versioning to disk cache
  backend/src/api/disk-cache.ts
Labels: cla-signed

#3373 Network-specific activation heights for transaction feature badges
  frontend/src/app/bitcoin.utils.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/tx-features/tx-features.component.ts
Labels: cla-signed

#3413 Pull from transifex
  frontend/src/locale/messages.ca.xlf
  frontend/src/locale/messages.es.xlf
  frontend/src/locale/messages.fr.xlf
  frontend/src/locale/messages.hi.xlf
  frontend/src/locale/messages.hr.xlf
  frontend/src/locale/messages.it.xlf
  frontend/src/locale/messages.ko.xlf
  frontend/src/locale/messages.sv.xlf
  frontend/src/locale/messages.th.xlf
  frontend/src/locale/messages.uk.xlf
  frontend/src/locale/messages.zh.xlf
Labels: cla-signed

#3408 Docker digest GHA
  .github/workflows/get_image_digest.yml
Labels: cla-signed

#3353 Improve mempool block animations
  backend/src/api/audit.ts
  backend/src/api/common.ts
  backend/src/api/websocket-handler.ts
  backend/src/mempool.interfaces.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.html
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/interfaces/websocket.interface.ts
Labels: cla-signed

#3407 Add faqs on mempool size and memory usage
  frontend/src/app/docs/api-docs/api-docs-data.ts
  frontend/src/app/docs/api-docs/api-docs-nav.component.html
  frontend/src/app/docs/api-docs/api-docs-nav.component.ts
  frontend/src/app/docs/api-docs/api-docs.component.html
Labels: cla-signed

#3402 Add subtitles for promo video
  frontend/.gitignore
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.ts
  frontend/src/resources/promo-video/mempool-promo.jpg
  frontend/sync-assets.js
Labels: cla-signed

#3104 Fix missing fees in liquid block tooltips
  backend/src/api/blocks.ts
Labels: cla-signed

#3405 Show block health in pool block list
  backend/src/api/mining/mining.ts
  backend/src/repositories/BlocksRepository.ts
  frontend/src/app/components/pool/pool-preview.component.ts
  frontend/src/app/components/pool/pool.component.html
  frontend/src/app/components/pool/pool.component.scss
  frontend/src/app/components/pool/pool.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
Labels: cla-signed

#3440 ops: Bump elementsd to v22.1
  production/elements.conf
  production/install
Labels: ops, cla-signed

#3378 Fix block list component responsive
  frontend/src/app/components/blocks-list/blocks-list.component.html
  frontend/src/app/components/blocks-list/blocks-list.component.scss
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.component.html
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.component.scss
Labels: cla-signed

#3444 Update docker configs
  backend/src/__tests__/config.test.ts
  docker/README.md
  docker/backend/Dockerfile
  docker/backend/mempool-config.json
  docker/backend/start.sh
  docker/init.sh
Labels: cla-signed

#3449 Fix maxmind tests
  backend/src/__tests__/config.test.ts
Labels: cla-signed

#3445 Fixing broken liquid blinding tests
  frontend/cypress/e2e/liquid/liquid.spec.ts
  frontend/cypress/e2e/liquidtestnet/liquidtestnet.spec.ts
Labels: cla-signed

#3448 Fix missing temp cache in disk cache
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/blocks.ts
  backend/src/api/disk-cache.ts
  backend/src/config.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
  production/mempool-config.liquid.json
  production/mempool-config.liquidtestnet.json
  production/mempool-config.mainnet.json
  production/mempool-config.signet.json
  production/mempool-config.testnet.json
Labels: cla-signed

#3447 Add poster image for readme video
  README.md
Labels: cla-signed

#3450 Make core and lnd rpc calls timeout configurable
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/bitcoin/bitcoin-client.ts
  backend/src/api/bitcoin/bitcoin-second-client.ts
  backend/src/api/lightning/lnd/lnd-api.ts
  backend/src/config.ts
  docker/README.md
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#3487 Catch exeptions in Lightning stats
  backend/src/index.ts
  backend/src/tasks/lightning/stats-updater.service.ts
Labels: cla-signed

#3490 Auto disable LN on macaroon fail
  backend/src/api/lightning/lnd/lnd-api.ts
  backend/src/logger.ts
  docker/frontend/entrypoint.sh
Labels: cla-signed

#3491 Audit disabled related UX fixes
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
  frontend/src/app/components/pool/pool.component.html
Labels: cla-signed

#3547 Removing "d" from node fee chart loading
  frontend/src/app/lightning/node-fee-chart/node-fee-chart.component.html
Labels: cla-signed

#3548 Update channels map indexing indicator
  frontend/src/app/lightning/node-fee-chart/node-fee-chart.component.ts
  frontend/src/app/lightning/node-statistics-chart/node-statistics-chart.component.ts
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.html
  frontend/src/app/lightning/nodes-channels-map/nodes-channels-map.component.ts
Labels: cla-signed

#3553 Reconnect to electrum an unlimited amount of times every 1 seconds upon disconnection
  backend/src/api/bitcoin/electrum-api.ts
Labels: cla-signed

#3554 Bumping electrum-client
  backend/package-lock.json
  backend/package.json
Labels: cla-signed

#3555 Change raspibolt logo to raspiblitz logo
  frontend/src/app/components/about/about.component.html
  frontend/src/resources/profile/raspiblitz.svg
  frontend/src/resources/profile/raspibolt.jpg
Labels: cla-signed

#3576 Fix difficulty adjustment bugs
  backend/src/api/difficulty-adjustment.ts
  backend/src/api/websocket-handler.ts
  backend/src/mempool.interfaces.ts
Labels: cla-signed

#3578 Revert regression introduced in #1320
  backend/src/api/blocks.ts
Labels: cla-signed

#3581 Enabling mempool in lightning prod
  production/mempool-config.mainnet-lightning.json
  production/mempool-config.signet-lightning.json
  production/mempool-config.testnet-lightning.json
Labels: cla-signed

#3560 Fix thread inconsistency / lazy deletion race condition bugs
  backend/src/api/audit.ts
  backend/src/api/disk-cache.ts
  backend/src/api/mempool-blocks.ts
  backend/src/api/mempool.ts
  backend/src/index.ts
Labels: cla-signed

#3585 Reset pools sha db state
  backend/src/api/database-migration.ts
Labels: cla-signed

#3584 Release v2.5.0
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: cla-signed

#3315 Use effective fee rate heuristics for block fee span
  backend/src/api/blocks.ts
  backend/src/api/common.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
  backend/src/repositories/CpfpRepository.ts
  frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.html
Labels: cla-signed

#3316 New median fee calculation for mempool blocks
  backend/src/api/mempool-blocks.ts
Labels: cla-signed

#3611 Fix infinite scroll transaction list component
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#3610 Fix search 1wizS test
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
Labels: cla-signed
