Repository mempool/mempool, pull requests merged in 2024-06, with the labels that each got.

#5122 Fix pool ranking table
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
Labels: cla-signed

#5123 Improve search results ordering
  frontend/src/app/components/search-form/search-form.component.ts
  frontend/src/app/components/search-form/search-results/search-results.component.html
  frontend/src/app/components/search-form/search-results/search-results.component.ts
Labels: cla-signed

#5124 Searchbar: wait for 3 characters before requesting lightning data
  frontend/src/app/services/api.service.ts
Labels: cla-signed

#5132 Experimental auto-push URL support
  frontend/src/app/components/push-transaction/push-transaction.component.ts
  frontend/src/app/master-page.module.ts
Labels: cla-signed

#5135 research images
  frontend/src/app/components/svg-images/svg-images.component.html
  frontend/src/resources/previews/research.jpg
  frontend/src/resources/previews/research.png
  unfurler/src/routes.ts
Labels: cla-signed

#5137 Pizza tracker RBF support
  frontend/src/app/components/tracker/tracker-bar.component.ts
  frontend/src/app/components/tracker/tracker.component.html
  frontend/src/app/components/tracker/tracker.component.scss
  frontend/src/app/components/tracker/tracker.component.ts
  frontend/src/app/shared/shared.module.ts
Labels: cla-signed

#5120 Multi-pool ETA
  backend/src/api/mempool-blocks.ts
  backend/src/api/mempool.ts
  backend/src/api/services/acceleration.ts
  backend/src/api/websocket-handler.ts
  backend/src/database.ts
  backend/src/index.ts
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#5125 Make address chart prefer "recent" mode by default
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/address/address.component.ts
Labels: cla-signed

#5141 [liquid] don't fetch pools
  backend/src/api/mempool-blocks.ts
Labels: cla-signed

#5136 research footer link
  frontend/src/app/shared/components/global-footer/global-footer.component.html
  frontend/src/app/shared/components/global-footer/global-footer.component.ts
Labels: cla-signed

#5145 Refactor "show all" toggle for long witnesses and witness scripts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.scss
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/shared/pipes/asm-styler/asm-styler.pipe.ts
Labels: cla-signed

#5149 Accurate timestamps on hover
  frontend/src/app/app.module.ts
  frontend/src/app/components/acceleration/accelerations-list/accelerations-list.component.html
  frontend/src/app/components/address-transactions-widget/address-transactions-widget.component.html
  frontend/src/app/components/custom-dashboard/custom-dashboard.component.html
  frontend/src/app/components/difficulty-adjustments-table/difficulty-adjustments-table.component.html
  frontend/src/app/components/liquid-reserves-audit/federation-utxos-list/federation-utxos-list.component.html
  frontend/src/app/components/liquid-reserves-audit/recent-pegs-list/recent-pegs-list.component.html
  frontend/src/app/components/pool/pool.component.html
  frontend/src/app/components/rbf-list/rbf-list.component.html
  frontend/src/app/components/time/time.component.html
  frontend/src/app/components/time/time.component.ts
  frontend/src/app/components/tracker/tracker.component.html
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/dashboard/dashboard.component.html
Labels: cla-signed

#5062 Configurable threshold for esplora tip check
  backend/mempool-config.sample.json
  backend/src/__fixtures__/mempool-config.template.json
  backend/src/__tests__/config.test.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/config.ts
  docker/backend/mempool-config.json
  docker/backend/start.sh
Labels: cla-signed

#5157 [about page] use grumpy guy instead of boring placeholder
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/profile/grumpy.svg
Labels: cla-signed

#5171 [accelerator] always show last 6 completed accelerations in accel dashboard
  frontend/src/app/components/acceleration/accelerator-dashboard/accelerator-dashboard.component.ts
Labels: cla-signed

#5134 Improve price conversions fetching from free API
  backend/src/tasks/price-feeds/free-currency-api.ts
  backend/src/tasks/price-updater.ts
  backend/src/utils/axios-query.ts
Labels: cla-signed

#5151 Address page redesign phase 1
  frontend/cypress/e2e/liquid/liquid.spec.ts
  frontend/src/app/components/address-labels/address-labels.component.html
  frontend/src/app/components/address-labels/address-labels.component.ts
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/address/address.component.scss
  frontend/src/app/components/address/address.component.ts
  frontend/src/app/components/clipboard/clipboard.component.html
  frontend/src/app/components/clipboard/clipboard.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/shared/address-utils.ts
  frontend/src/app/shared/components/address-type/address-type.component.html
  frontend/src/app/shared/components/address-type/address-type.component.ts
  frontend/src/app/shared/components/truncate/truncate.component.scss
  frontend/src/app/shared/regex.utils.ts
  frontend/src/app/shared/script.utils.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement, cla-signed

#5169 Implement $getTxsForBlock for Core backends
  backend/src/api/bitcoin/bitcoin-api.ts
Labels: cla-signed

#5159 Handle services backend failures in block component
  frontend/src/app/components/block/block.component.ts
Labels: cla-signed

#5156 Root frontend network setting
  docker/frontend/entrypoint.sh
  frontend/mempool-frontend-config.sample.json
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.ts
  frontend/src/app/lightning/lightning-api.service.ts
  frontend/src/app/services/api.service.ts
  frontend/src/app/services/electrs-api.service.ts
  frontend/src/app/services/navigation.service.ts
  frontend/src/app/services/state.service.ts
  frontend/src/app/services/websocket.service.ts
  frontend/src/app/shared/pipes/relative-url/relative-url.pipe.ts
Labels: cla-signed

#5160 Fix incorrect non-standard label on reserved segwit output types
  backend/src/api/common.ts
  frontend/src/app/shared/transaction.utils.ts
Labels: cla-signed

#5182 Unit tests: nonstandard
  backend/src/__tests__/api/common.ts
  backend/src/__tests__/api/test-data/non-standard-txs.json
  backend/src/__tests__/api/test-data/transactions-random.json
Labels: cla-signed

#5183 Missing difficulty adjustment causes invalid json response
  backend/src/api/websocket-handler.ts
Labels: cla-signed

#5176 Fix monitoring table layout & text wrapping
  frontend/src/app/components/server-health/server-health.component.html
  frontend/src/app/components/server-health/server-health.component.scss
  frontend/src/app/components/server-health/server-health.component.ts
Labels: cla-signed

#5185 configurable block size & count in rust gbt
  backend/src/__tests__/gbt/gbt-tests.ts
  backend/src/api/mempool-blocks.ts
  rust/gbt/src/gbt.rs
  rust/gbt/src/lib.rs
Labels: cla-signed

#5186 Fix hardcoded median weight units in calcEffectiveFeeStatistics
  backend/src/api/common.ts
Labels: cla-signed

#5184 Always show clearing rate line on incoming tx chart
  frontend/src/app/components/incoming-transactions-graph/incoming-transactions-graph.component.ts
Labels: cla-signed

#5188 Adapt address page skeleton
  frontend/src/app/components/address/address.component.html
Labels: cla-signed

#5153 Add USD to address balance history chart
  frontend/src/app/components/address-graph/address-graph.component.html
  frontend/src/app/components/address-graph/address-graph.component.scss
  frontend/src/app/components/address-graph/address-graph.component.ts
  frontend/src/app/components/address-transactions-widget/address-transactions-widget.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.ts
  frontend/src/app/interfaces/electrs.interface.ts
  frontend/src/app/services/price.service.ts
  frontend/src/app/shared/pipes/fiat-shortener.pipe.ts
Labels: cla-signed

#5189 Twitter -> X
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/twitter-widget/twitter-widget.component.ts
  frontend/src/app/shared/components/global-footer/global-footer.component.html
  unfurler/views/footer.ejs
Labels: cla-signed

#5190 Address page ux updates
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/address/address.component.scss
  frontend/src/app/components/address/address.component.ts
Labels: cla-signed

#5194 Fix mempool transactions being stripped
  backend/src/api/redis-cache.ts
Labels: cla-signed

#5193 Refactor address table to improve cell wrapping
  frontend/src/app/components/address/address.component.html
  frontend/src/styles.scss
Labels: cla-signed

#5147 Acceleration preview hashrate pie chart
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.html
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.scss
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.ts
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.html
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.ts
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
  frontend/src/app/components/pool-ranking/pool-ranking.component.ts
  frontend/src/app/components/tracker/tracker.component.html
  frontend/src/app/components/tracker/tracker.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
  frontend/src/app/components/transaction/transaction.module.ts
  frontend/src/app/interfaces/node-api.interface.ts
  frontend/src/app/services/eta.service.ts
  frontend/src/app/services/mining.service.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/app/shared/transaction.utils.ts
Labels: cla-signed

#5178 Recover from esplora failover after a reorg to lower height
  backend/src/api/bitcoin/esplora-api.ts
Labels: cla-signed

#5007 [accelerator] change default bid prepaid
  frontend/src/app/components/accelerate-checkout/accelerate-checkout.component.ts
Labels: cla-signed

#5195 Address balance graph: hide usd on non-mainnet networks
  frontend/src/app/components/address-graph/address-graph.component.ts
Labels: cla-signed

#5200 no trailing spaces
  backend/.eslintrc
  frontend/.eslintrc
Labels: cla-signed

#5198 Fix "Confirmed after" transaction field
  frontend/src/app/components/transaction/transaction.component.html
Labels: cla-signed

#5197 Sha256 P2PK secure context workaround
  frontend/src/app/bitcoin.utils.ts
  frontend/src/app/shared/sha256.ts
Labels: cla-signed

#5202 Round 24h pools hashrate
  frontend/src/app/components/pool-ranking/pool-ranking.component.html
Labels: cla-signed

#5187 Prevent websocket reconnect on custom root instances
  frontend/src/app/services/websocket.service.ts
Labels: cla-signed

#5204 Fix tx position frontend error
  frontend/src/app/components/mempool-blocks/mempool-blocks.component.ts
Labels: cla-signed

#5205 Add coinbase_addresses to extended blocks & table
  backend/src/api/bitcoin/bitcoin-api-abstract-factory.ts
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.ts
  backend/src/api/blocks.ts
  backend/src/api/database-migration.ts
  backend/src/indexer.ts
  backend/src/mempool.interfaces.ts
  backend/src/repositories/BlocksRepository.ts
Labels: cla-signed

#5206 Fix address prefix for non esplora backend
  backend/src/api/bitcoin/bitcoin-api.ts
  backend/src/api/bitcoin/esplora-api.interface.ts
Labels: cla-signed

#5209 Fix coinbase address type error
  backend/src/api/blocks.ts
Labels: cla-signed

#5203 Romanz support for address page
  frontend/src/app/components/address/address.component.html
Labels: cla-signed

#5199 Add projected acceleration ETA to tracker page
  frontend/src/app/components/accelerate-checkout/accelerate-checkout.component.html
  frontend/src/app/components/accelerate-checkout/accelerate-checkout.component.ts
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.html
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/services/eta.service.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#5210 Force amounts to BTC unit in pool page
  frontend/src/app/components/amount/amount.component.html
  frontend/src/app/components/amount/amount.component.ts
  frontend/src/app/components/pool/pool.component.html
Labels: cla-signed

#5212 Fix ETA loading error
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.html
  frontend/src/app/components/time/time.component.ts
  frontend/src/app/services/eta.service.ts
Labels: cla-signed

#5213 Add page in URL to accelerations table
  frontend/src/app/components/acceleration/accelerations-list/accelerations-list.component.ts
  frontend/src/app/components/blocks-list/blocks-list.component.ts
  frontend/src/app/components/liquid-reserves-audit/recent-pegs-list/recent-pegs-list.component.ts
  frontend/src/app/graphs/graphs.routing.module.ts
  frontend/src/app/liquid/liquid-master-page.module.ts
  frontend/src/app/master-page.module.ts
Labels: cla-signed

#5214 Show loading indicator on toggle in RBF list
  frontend/src/app/components/rbf-list/rbf-list.component.html
  frontend/src/app/components/rbf-list/rbf-list.component.ts
Labels: cla-signed

#5215 Minor style & layout tweaks for the acceleration preview
  frontend/src/app/components/accelerate-preview/accelerate-fee-graph.component.scss
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.html
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.scss
Labels: cla-signed

#5211 Simplify advanced acceleration
  frontend/src/app/components/accelerate-preview/accelerate-fee-graph.component.scss
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.html
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.scss
  frontend/src/app/components/accelerate-preview/accelerate-preview.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
Labels: UI/UX, cla-signed

#5219 Show accelerator estimates on local instances
  backend/src/api/acceleration/acceleration.routes.ts
  frontend/src/app/components/tracker/tracker.component.ts
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#5216 Align "Accelerated to / by" fields on mobile
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.html
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.scss
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.ts
Labels: cla-signed

#5224 Replace bitcoin-s with coldcard on about page
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/about/about.component.scss
  frontend/src/resources/profile/coldcard.png
Labels: cla-signed

#5222 Show more detail in acceleration pools pie chart
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.scss
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.ts
Labels: cla-signed

#5225 Fix acceleration preview showing with fragment on accel txs
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#5229 Redirect user to `/` when user goes to `/tx` without any transaction `id`
  frontend/src/app/components/transaction/transaction.module.ts
Labels: cla-signed

#5226 Fix logic for pool pie chart position
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.html
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.scss
  frontend/src/app/components/acceleration/active-acceleration-box/active-acceleration-box.component.ts
  frontend/src/app/components/transaction/transaction.component.html
Labels: cla-signed

#5230 Docs root network support
  frontend/src/app/docs/api-docs/api-docs.component.ts
  frontend/src/app/docs/code-template/code-template.component.ts
Labels: cla-signed

#5231 Update foundry logo on about page
  frontend/src/app/components/about/about.component.html
Labels: cla-signed

#5227 Juggle community integration listings
  frontend/src/app/components/about/about.component.html
Labels: cla-signed

#5234 [btcpay] fix displayed amount
  frontend/src/app/components/bitcoin-invoice/bitcoin-invoice.component.html
  frontend/src/app/components/bitcoin-invoice/bitcoin-invoice.component.ts
Labels: cla-signed

#5236 Fix dust limit for undefined witness program outputs
  backend/src/__tests__/api/test-data/transactions-random.json
  backend/src/api/common.ts
  frontend/src/app/shared/transaction.utils.ts
Labels: cla-signed
