Repository mempool/mempool, pull requests merged in 2025-04, with the labels that each got.

#5835 Add support for running tests against any PR or branch
  .github/workflows/e2e_parameterized.yml
Labels: cla-signed

#5837 misc changes
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/blockchain/blockchain.component.ts
Labels: cla-signed

#5840 more misc changes
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#5843 Add E2E tests for address poisoning highlighting and the RBF tx tracker
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
  frontend/cypress/fixtures/details_rbf/api_accelerator_estimate.json
  frontend/cypress/fixtures/details_rbf/api_accelerator_version.json
  frontend/cypress/fixtures/details_rbf/api_block_history.json
  frontend/cypress/fixtures/details_rbf/api_mining_pools_1w.json
  frontend/cypress/fixtures/details_rbf/tx01_api_cached.json
  frontend/cypress/fixtures/details_rbf/tx01_api_rbf.json
  frontend/cypress/fixtures/details_rbf/tx01_ws_blocks_01.json
  frontend/cypress/fixtures/details_rbf/tx01_ws_mempool_blocks_01.json
  frontend/cypress/fixtures/details_rbf/tx01_ws_stratum_jobs.json
  frontend/cypress/fixtures/details_rbf/tx01_ws_tx_replaced.json
  frontend/cypress/fixtures/details_rbf/tx02_api_cpfp.json
  frontend/cypress/fixtures/details_rbf/tx02_api_rbf.json
  frontend/cypress/fixtures/details_rbf/tx02_api_tx.json
  frontend/cypress/fixtures/details_rbf/tx02_api_tx_times.json
  frontend/cypress/fixtures/details_rbf/tx02_ws_block.json
  frontend/cypress/fixtures/details_rbf/tx02_ws_block_confirmation.json
  frontend/cypress/fixtures/details_rbf/tx02_ws_mempool_blocks_01.json
  frontend/cypress/fixtures/details_rbf/tx02_ws_next_block.json
  frontend/cypress/fixtures/details_rbf/tx02_ws_tx_position.json
  frontend/cypress/support/commands.ts
  frontend/cypress/support/index.d.ts
  frontend/cypress/support/websocket.ts
Labels: cla-signed

#5844 Run CI workflow after merging too
  .github/workflows/ci.yml
Labels: cla-signed

#5842 Fix loose screws on the blockchain bar
  frontend/src/app/components/blockchain/blockchain.component.html
  frontend/src/app/components/blockchain/blockchain.component.scss
  frontend/src/app/components/blockchain/blockchain.component.ts
  frontend/src/app/services/state.service.ts
Labels: cla-signed

#5845 Bump node version to v22
  .github/workflows/ci.yml
  .github/workflows/e2e_parameterized.yml
  .nvmrc
  production/README.md
  production/install
  production/mempool-start-all
Labels: cla-signed

#5847 Add a test for the RBF page updates
  frontend/cypress/e2e/mainnet/mainnet.spec.ts
  frontend/cypress/fixtures/rbf_page/rbf_01.json
  frontend/cypress/fixtures/rbf_page/rbf_02.json
Labels: cla-signed

#5850 FIx pool page CSS
  frontend/src/app/components/pool/pool.component.scss
Labels: cla-signed

#5852 Bump package.json versions ahead of the official release
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  unfurler/package-lock.json
  unfurler/package.json
Labels: cla-signed

#5824 Fix database disabled
  backend/src/api/blocks.ts
  backend/src/api/common.ts
  backend/src/api/websocket-handler.ts
  backend/src/index.ts
Labels: cla-signed

#5838 polish pool updates
  backend/src/api/pools-parser.ts
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#5853 pump up monitoring frequency
  backend/src/api/bitcoin/esplora-api.ts
Labels: cla-signed

#5854 Fix axios unix sockets
  backend/src/api/bitcoin/esplora-api.ts
Labels: cla-signed

#5855 Pin node 22 to 22.14.0
  .github/workflows/ci.yml
  .github/workflows/e2e_parameterized.yml
  docker/backend/Dockerfile
  docker/frontend/Dockerfile
Labels: cla-signed

#5856 Set automatic pool updates on by default
  docker/backend/start.sh
Labels: cla-signed

#5860 portlandhodl/ckpool-install-support
  production/install
Labels: enhancement, cla-signed

#5863 Continue to tag Docker builds as latest
  .github/workflows/on-tag.yml
Labels: cla-signed

#5848 Fix false positive address poisoning warnings on wallet page
  frontend/src/app/components/transactions-list/transactions-list.component.ts
Labels: cla-signed

#5830 wallet cache
  backend/src/api/services/services-routes.ts
  backend/src/api/services/wallets.ts
Labels: cla-signed

#5831 wallet 404
  frontend/src/app/components/wallet/wallet.component.ts
Labels: cla-signed

#5862 [accelerator] ui polish
  frontend/src/app/components/accelerate-checkout/accelerate-checkout.component.html
  frontend/src/app/components/accelerate-checkout/accelerate-checkout.component.ts
  frontend/src/app/components/tracker/tracker.component.html
  frontend/src/app/components/tracker/tracker.component.ts
  frontend/src/app/components/transaction/transaction.component.html
  frontend/src/app/components/transaction/transaction.component.ts
Labels: cla-signed

#5846 River dashboard
  frontend/custom-river-config.json
  frontend/src/index.mempool.river.html
  frontend/src/resources/river/android-chrome-192x192.png
  frontend/src/resources/river/android-chrome-512x512.png
  frontend/src/resources/river/apple-touch-icon.png
  frontend/src/resources/river/favicon-16x16.png
  frontend/src/resources/river/favicon-32x32.png
  frontend/src/resources/river/favicon.ico
  frontend/src/resources/river/river-preview.png
  frontend/src/resources/river/site.webmanifest
  frontend/src/resources/riverlogo.svg
  production/mempool-build-all
  production/mempool-frontend-config.river.json
  production/mempool-start-all
  production/unfurler-config.river.json
  unfurler/src/routes.ts
Labels: cla-signed

#5870 Replace mempool liquidity with mempool wallet
  LICENSE
  frontend/src/app/components/about/about.component.html
  frontend/src/app/components/trademark-policy/trademark-policy.component.html
Labels: cla-signed

#5869 Replace skinny pickaxe with fat pickaxe
  frontend/src/app/components/svg-images/svg-images.component.html
Labels: cla-signed

#5871 Fix liquid scroll overflow
  frontend/src/app/components/timezone-selector/timezone-selector.component.html
Labels: cla-signed

#5825 Taptree widget on addresss page
  frontend/src/app/components/address/address.component.html
  frontend/src/app/components/address/address.component.ts
  frontend/src/app/components/taproot-address-scripts/taproot-address-scripts.component.html
  frontend/src/app/components/taproot-address-scripts/taproot-address-scripts.component.scss
  frontend/src/app/components/taproot-address-scripts/taproot-address-scripts.component.ts
  frontend/src/app/components/transactions-list/transactions-list.component.html
  frontend/src/app/graphs/echarts.ts
  frontend/src/app/graphs/graphs.module.ts
  frontend/src/app/shared/address-utils.ts
  frontend/src/app/shared/pipes/asm-styler/asm-styler.pipe.ts
  frontend/src/app/shared/script.utils.ts
  frontend/src/app/shared/transaction.utils.ts
Labels: cla-signed

#5758 [indexing] make `blocks.definition_hash` nullable and exit early if appropriate
  backend/src/api/database-migration.ts
  backend/src/index.ts
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#5873 backport blocks sha fix
  backend/src/api/database-migration.ts
  backend/src/index.ts
  backend/src/tasks/pools-updater.ts
Labels: cla-signed

#5872 Update copyright year to 2025
  LICENSE
  frontend/src/app/components/about/about.component.html
Labels: cla-signed

#5874 [Fix] CKSolo FreeBSD Production Installer Script
  production/install
Labels: bug, cla-signed

#5877 autobuild template scaffolding
  frontend/src/index.mempool.html
Labels: cla-signed

#5878 maybe fix pickaxe svg bug
  frontend/src/app/components/svg-images/svg-images.component.html
Labels: cla-signed

#5879 Remove Bisq from Production Install Script
  production/install
Labels: ops, cla-signed

#5880 Reset taptree widget on address change
  frontend/src/app/components/address/address.component.ts
Labels: cla-signed

#5876 Fix cropped difficulty series in hashrate chart
  frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts
Labels: cla-signed

#5882 Switch all nav icons to svg
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.html
  frontend/src/app/components/liquid-master-page/liquid-master-page.component.scss
  frontend/src/app/components/master-page/master-page.component.html
  frontend/src/app/components/master-page/master-page.component.scss
  frontend/src/app/components/svg-images/svg-images.component.html
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles.scss
Labels: cla-signed

#5888 Add new enterprise sponsor
  frontend/src/app/components/about/about.component.html
Labels: cla-signed

#5892 update custom dashboard configs
  frontend/custom-strategy-config.json
  frontend/src/index.mempool.strategy.html
  frontend/src/resources/strategy/favicons/android-chrome-192x192.png
  frontend/src/resources/strategy/favicons/android-chrome-512x512.png
  frontend/src/resources/strategy/favicons/apple-touch-icon.png
  frontend/src/resources/strategy/favicons/favicon-16x16.png
  frontend/src/resources/strategy/favicons/favicon-32x32.png
  frontend/src/resources/strategy/favicons/favicon.ico
  frontend/src/resources/strategy/favicons/site.webmanifest
  frontend/src/resources/strategy/strategy-preview.png
  frontend/src/resources/strategylogo.png
  production/mempool-build-all
  production/mempool-frontend-config.strategy.json
  production/mempool-start-all
  production/unfurler-config.strategy.json
  unfurler/src/routes.ts
Labels: cla-signed

#5894 revert borked svg fix
  frontend/src/app/components/svg-images/svg-images.component.scss
  frontend/src/app/components/svg-images/svg-images.component.ts
  frontend/src/styles.scss
Labels: cla-signed
